import builtins
import sys
from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from griddy.nfl.models.combineevents import (
        BenchPress,
        BenchPressTypedDict,
        BroadJump,
        BroadJumpTypedDict,
        FortyYardDash,
        FortyYardDashTypedDict,
        TenYardSplit,
        TenYardSplitTypedDict,
        ThreeConeDrill,
        ThreeConeDrillTypedDict,
        TwentyYardShuffle,
        TwentyYardShuffleTypedDict,
        VerticalJump,
        VerticalJumpTypedDict,
    )
    from griddy.nfl.models.combineprofile import (
        CombinePerson,
        CombinePersonTypedDict,
        CombineProfile,
        CombineProfileTypedDict,
    )
    from griddy.nfl.models.combineprofilesresponse import (
        CombineProfilesResponse,
        CombineProfilesResponseTypedDict,
    )
    from griddy.nfl.models.enums.combineenums import (
        CollegeClassEnum,
        DesignationEnum,
        EventFilterEnum,
    )
    from griddy.nfl.models.getcombineprofilesop import (
        GetCombineProfilesRequest,
        GetCombineProfilesRequestTypedDict,
    )
    from griddy.nfl.models.getdefensivenearestdefenderstatsbyseasonop import (
        GetDefensiveNearestDefenderStatsBySeasonRequest,
        GetDefensiveNearestDefenderStatsBySeasonRequestTypedDict,
        GetDefensiveNearestDefenderStatsBySeasonSortKey,
    )
    from griddy.nfl.models.getdefensivenearestdefenderstatsbyweekop import (
        GetDefensiveNearestDefenderStatsByWeekRequest,
        GetDefensiveNearestDefenderStatsByWeekRequestTypedDict,
        GetDefensiveNearestDefenderStatsByWeekSortKey,
    )
    from griddy.nfl.models.getdefensiveoverviewstatsbyweekop import (
        GetDefensiveOverviewStatsByWeekRequest,
        GetDefensiveOverviewStatsByWeekRequestTypedDict,
        GetDefensiveOverviewStatsByWeekSortKey,
    )
    from griddy.nfl.models.getdefensivepassrushstatsbyweekop import (
        GetDefensivePassRushStatsByWeekRequest,
        GetDefensivePassRushStatsByWeekRequestTypedDict,
        GetDefensivePassRushStatsByWeekSortKey,
    )
    from griddy.nfl.models.getdraftpicksreportop import (
        GetDraftPicksReportRequest,
        GetDraftPicksReportRequestTypedDict,
    )
    from griddy.nfl.models.getplaylist import (
        GetPlayListRequest,
        GetPlayListRequestTypedDict,
    )
    from griddy.nfl.models.getteamneedsop import (
        GetTeamNeedsRequest,
        GetTeamNeedsRequestTypedDict,
    )
    from griddy.nfl.models.getteamoffenserushstatsbyseasonop import (
        GetTeamOffenseRushStatsBySeasonRequest,
        GetTeamOffenseRushStatsBySeasonRequestTypedDict,
        GetTeamOffenseRushStatsBySeasonSortKey,
    )
    from griddy.nfl.models.getteamoffenserushstatsbyweekop import (
        GetTeamOffenseRushStatsByWeekRequest,
        GetTeamOffenseRushStatsByWeekRequestTypedDict,
        GetTeamOffenseRushStatsByWeekSortKey,
    )
    from griddy.nfl.models.requests.get_week_of_date_op import (
        GetWeekOfDateRequest,
        GetWeekOfDateRequestTypedDict,
    )
    from griddy.nfl.models.requests.getcombinerankingsop import (
        GetCombineRankingsRequest,
        GetCombineRankingsRequestTypedDict,
    )
    from griddy.nfl.models.responses.combinerankingsresponse import (
        CombineRankingsResponse,
        CombineRankingsResponseTypedDict,
    )
    from griddy.nfl.models.teamneedsresponse import (
        TeamNeedsResponse,
        TeamNeedsResponseTypedDict,
    )
    from griddy.nfl.models.teamoffenserushstats import (
        TeamOffenseRushStats,
        TeamOffenseRushStatsTypedDict,
    )
    from griddy.nfl.models.teamoffenserushstatsresponse import (
        TeamOffenseRushStatsResponse,
        TeamOffenseRushStatsResponseTypedDict,
    )

    from .award import Award, AwardType, AwardTypedDict
    from .binaryflagenum import BinaryFlagEnum
    from .boxscoreresponse import BoxscoreResponse, BoxscoreResponseTypedDict
    from .boxscoreresponse_2 import (
        Away,
        AwayTypedDict,
        BoxScoreResponse2,
        BoxScoreResponse2TypedDict,
        Home,
        HomeTypedDict,
        PlayerStats,
        PlayerStatsTypedDict,
        TeamStats,
        TeamStatsTypedDict,
    )
    from .boxscoreschedule import BoxscoreSchedule, BoxscoreScheduleTypedDict
    from .boxscorescore import BoxscoreScore, BoxscoreScoreTypedDict
    from .boxscoresite import BoxscoreSite, BoxscoreSiteRoofType, BoxscoreSiteTypedDict
    from .boxscoreteam import BoxscoreTeam, BoxscoreTeamTypedDict
    from .broadcastinfo import (
        BroadcastInfo,
        BroadcastInfoTypedDict,
        InternationalWatchOption,
        InternationalWatchOptionTypedDict,
        StreamingNetwork,
        StreamingNetworkTypedDict,
        Territory,
    )
    from .careerstats import CareerStats, CareerStatsTypedDict
    from .clinched import Clinched, ClinchedTypedDict
    from .coachesfilmresponse import CoachesFilmResponse, CoachesFilmResponseTypedDict
    from .coachesfilmvideo import (
        Background,
        BackgroundTypedDict,
        CameraSource,
        CoachesFilmVideo,
        CoachesFilmVideoType,
        CoachesFilmVideoTypedDict,
        Cta,
        CtaTypedDict,
        Image,
        ImageTypedDict,
        PromoAsset,
        PromoAssetTypedDict,
        SubType,
        Video,
        VideoTypedDict,
    )
    from .conference import Conference, ConferenceTypedDict
    from .conferenceenum import ConferenceEnum
    from .contractinfo import ContractInfo, ContractInfoTypedDict
    from .currentgame import (
        CurrentGame,
        CurrentGameCategory,
        CurrentGameExtension,
        CurrentGameExtensionTypedDict,
        CurrentGameTypedDict,
    )
    from .currentgamesresponse import (
        CurrentGamesResponse,
        CurrentGamesResponseTypedDict,
    )
    from .defensivenearestdefenderstats import (
        DefensiveNearestDefenderStats,
        DefensiveNearestDefenderStatsTypedDict,
    )
    from .defensiveoverviewstatsresponse import (
        DefensiveOverviewStatsResponse,
        DefensiveOverviewStatsResponseTypedDict,
    )
    from .defensivepassrushstats import (
        DefensivePassRushStats,
        DefensivePassRushStatsNgsPosition,
        DefensivePassRushStatsPosition,
        DefensivePassRushStatsTypedDict,
    )
    from .defensiveplayeroverviewstats import (
        DefensivePlayerOverviewStats,
        DefensivePlayerOverviewStatsNgsPosition,
        DefensivePlayerOverviewStatsPosition,
        DefensivePlayerOverviewStatsTypedDict,
    )
    from .defensivepositiongroupenum import DefensivePositionGroupEnum
    from .defensivestats import DefensiveStats, DefensiveStatsTypedDict
    from .division import Division, DivisionTypedDict
    from .draftpick import DraftPick, DraftPickTypedDict
    from .draftresponse import (
        DraftResponse,
        DraftResponseTypedDict,
        Round,
        RoundTypedDict,
    )
    from .drive import Drive, DriveTypedDict, Result
    from .enums.defensive_splits_enum import DefenseNGSSplitEnum
    from .enums.downenum import DownEnum
    from .enums.gamelocationenum import GameLocationEnum
    from .enums.positionenums import (
        DefenseNGSPositionEnum,
        DefenseNGSPositionGroupEnum,
        DefensePositionEnum,
        DefensePositionGroupEnum,
    )
    from .enums.quarterenum import QuarterEnum
    from .enums.yardstogoenum import YardsToGoEnum
    from .experiencegamesresponse import (
        ExperienceGamesResponse,
        ExperienceGamesResponseTypedDict,
    )
    from .experienceteamsresponse import (
        ExperienceTeamsResponse,
        ExperienceTeamsResponseTypedDict,
    )
    from .externalid import ExternalID, ExternalIDTypedDict
    from .fantasyplayerstats import (
        FantasyPlayerStats,
        FantasyPlayerStatsPosition,
        FantasyPlayerStatsTypedDict,
        PositionGroup,
    )
    from .fantasystatsresponse import (
        FantasyStatsResponse,
        FantasyStatsResponseTypedDict,
    )
    from .filmcard import FilmCard, FilmCardTypedDict, LinkParams, LinkParamsTypedDict
    from .filmroomplay import FilmroomPlay, FilmroomPlayTypedDict
    from .filmroomplaysresponse import (
        FilmroomPlaysResponse,
        FilmroomPlaysResponseTypedDict,
    )
    from .footballgamesresponse import (
        FootballGamesResponse,
        FootballGamesResponseTypedDict,
    )
    from .futuresmarket import (
        Fixture,
        FixtureTypedDict,
        FuturesMarket,
        FuturesMarketTypedDict,
    )
    from .futuresoddsresponse import (
        FuturesOddsResponse,
        FuturesOddsResponseData,
        FuturesOddsResponseDataTypedDict,
        FuturesOddsResponseTypedDict,
    )
    from .game import (
        Game,
        GameCategory,
        GameExtension,
        GameExtensionTypedDict,
        GameStatus,
        GameTypedDict,
    )
    from .gamecenterresponse import (
        GamecenterResponse,
        GamecenterResponseTypedDict,
        Leaders,
        LeadersTypedDict,
        LeagueAverageReceiverSeparation,
        LeagueAverageReceiverSeparationTypedDict,
        LeagueAverageSeparationToQb,
        LeagueAverageSeparationToQbTypedDict,
        PassDistanceLeaders,
        PassDistanceLeadersTypedDict,
        Passers,
        PassersTypedDict,
        PassRushers,
        PassRushersTypedDict,
        Receivers,
        ReceiversTypedDict,
        Rushers,
        RushersTypedDict,
        SpeedLeaders,
        SpeedLeadersTypedDict,
        TimeToSackLeaders,
        TimeToSackLeadersTypedDict,
    )
    from .gamecenterschedule import GamecenterSchedule, GamecenterScheduleTypedDict
    from .gamedetail import GameDetail, GameDetailTypedDict
    from .gameinsight import (
        Content,
        ContentTypedDict,
        GameInsight,
        GameInsightTypedDict,
    )
    from .gameodds import GameOdds, GameOddsTypedDict
    from .gamepreviewresponse import (
        GamePreviewResponse,
        GamePreviewResponseTypedDict,
        Preview,
        PreviewTypedDict,
    )
    from .gameresultenum import GameResultEnum
    from .gameschedule import GameSchedule, GameScheduleTypedDict
    from .gamescore import GameScore, GameScoreTypedDict, Phase
    from .gamesite import GameSite, GameSiteRoofType, GameSiteTypedDict
    from .gamesresponse import GamesResponse, GamesResponseTypedDict
    from .gamestatsresponse import (
        GameStatsResponse,
        GameStatsResponseData,
        GameStatsResponseDataTypedDict,
        GameStatsResponseTypedDict,
    )
    from .gamestatusenum import GameStatusEnum
    from .gameteam import GameTeam, GameTeamTypedDict, Score, ScoreTypedDict
    from .getcoachesfilmvideosop import (
        GetCoachesFilmVideosRequest,
        GetCoachesFilmVideosRequestTypedDict,
    )
    from .getdefensiveoverviewstatsbyseasonop import (
        GetDefensiveOverviewStatsBySeasonRequest,
        GetDefensiveOverviewStatsBySeasonRequestTypedDict,
        GetDefensiveOverviewStatsBySeasonSortKey,
    )
    from .getdefensivepassrushstatsbyseasonop import (
        GetDefensivePassRushStatsBySeasonRequest,
        GetDefensivePassRushStatsBySeasonRequestTypedDict,
        GetDefensivePassRushStatsBySeasonSortKey,
    )
    from .getdefensivestatsbyseasonop import (
        GetDefensiveStatsBySeasonRequest,
        GetDefensiveStatsBySeasonRequestTypedDict,
        GetDefensiveStatsBySeasonSortKey,
    )
    from .getdraftinfoop import GetDraftInfoRequest, GetDraftInfoRequestTypedDict
    from .getexperiencegamesop import (
        GetExperienceGamesRequest,
        GetExperienceGamesRequestTypedDict,
    )
    from .getexperienceteamsop import (
        GetExperienceTeamsRequest,
        GetExperienceTeamsRequestTypedDict,
    )
    from .getfantasystatsbyseasonop import (
        GetFantasyStatsBySeasonPositionGroup,
        GetFantasyStatsBySeasonRequest,
        GetFantasyStatsBySeasonRequestTypedDict,
        GetFantasyStatsBySeasonSortKey,
    )
    from .getfilmroomplaysop import (
        AirYardType,
        DefCoverageType,
        DefendersInTheBoxType,
        DropbackTimeType,
        GetFilmroomPlaysRequest,
        GetFilmroomPlaysRequestTypedDict,
        Personnel,
        QbAlignment,
        ReceiverAlignment,
        RushDirection,
        SeparationType,
        TargetLocation,
        YardsToGoType,
    )
    from .getfootballboxscoreop import (
        GetFootballBoxScoreRequest,
        GetFootballBoxScoreRequestTypedDict,
    )
    from .getfootballgamesop import (
        GetFootballGamesRequest,
        GetFootballGamesRequestTypedDict,
    )
    from .getgamecenterop import GetGamecenterRequest, GetGamecenterRequestTypedDict
    from .getgameinsightsop import (
        GetGameInsightsRequest,
        GetGameInsightsRequestTypedDict,
    )
    from .getgamematchuprankingsop import (
        GetGameMatchupRankingsRequest,
        GetGameMatchupRankingsRequestTypedDict,
    )
    from .getgamepreviewop import GetGamePreviewRequest, GetGamePreviewRequestTypedDict
    from .getgameteamrankingsop import (
        GetGameTeamRankingsRequest,
        GetGameTeamRankingsRequestTypedDict,
    )
    from .getinjuryreportsop import (
        GetInjuryReportsRequest,
        GetInjuryReportsRequestTypedDict,
    )
    from .getlivegamescoresop import (
        GetLiveGameScoresRequest,
        GetLiveGameScoresRequestTypedDict,
    )
    from .getlivegamestatsop import (
        GetLiveGameStatsRequest,
        GetLiveGameStatsRequestTypedDict,
    )
    from .getmultiplerankingsallteamsop import (
        GetMultipleRankingsAllTeamsRequest,
        GetMultipleRankingsAllTeamsRequestTypedDict,
    )
    from .getplaybyplayop import GetPlayByPlayRequest, GetPlayByPlayRequestTypedDict
    from .getplayerdetailsop import (
        GetPlayerDetailsRequest,
        GetPlayerDetailsRequestTypedDict,
    )
    from .getplayerop import GetPlayerRequest, GetPlayerRequestTypedDict
    from .getplayerpassingstatsbyseasonop import (
        GetPlayerPassingStatsBySeasonRequest,
        GetPlayerPassingStatsBySeasonRequestTypedDict,
    )
    from .getplayerpassingstatsbyweekop import (
        GetPlayerPassingStatsByWeekRequest,
        GetPlayerPassingStatsByWeekRequestTypedDict,
    )
    from .getplayerreceivingstatsbyseasonop import (
        GetPlayerReceivingStatsBySeasonRequest,
        GetPlayerReceivingStatsBySeasonRequestTypedDict,
    )
    from .getplayerreceivingstatsbyweekop import (
        GetPlayerReceivingStatsByWeekRequest,
        GetPlayerReceivingStatsByWeekRequestTypedDict,
    )
    from .getplayerrushingstatsbyseasonop import (
        GetPlayerRushingStatsBySeasonRequest,
        GetPlayerRushingStatsBySeasonRequestTypedDict,
        GetPlayerRushingStatsBySeasonSortKey,
    )
    from .getplayerrushingstatsbyweekop import (
        GetPlayerRushingStatsByWeekRequest,
        GetPlayerRushingStatsByWeekRequestTypedDict,
        GetPlayerRushingStatsByWeekSortKey,
    )
    from .getplayersteamrosterop import (
        GetPlayersTeamRosterRequest,
        GetPlayersTeamRosterRequestTypedDict,
    )
    from .getplayswinprobabilityop import (
        GameID,
        GameIDTypedDict,
        GetPlaysWinProbabilityRequest,
        GetPlaysWinProbabilityRequestTypedDict,
        GetPlaysWinProbabilityResponse,
        GetPlaysWinProbabilityResponseTypedDict,
    )
    from .getprojectedstatsop import (
        GetProjectedStatsRequest,
        GetProjectedStatsRequestTypedDict,
    )
    from .getscheduledgameop import (
        GetScheduledGameRequest,
        GetScheduledGameRequestTypedDict,
    )
    from .getscheduledgamesop import (
        GetScheduledGamesRequest,
        GetScheduledGamesRequestTypedDict,
    )
    from .getscheduleseasonweeksop import (
        GetScheduleSeasonWeeksRequest,
        GetScheduleSeasonWeeksRequestTypedDict,
    )
    from .getseasoncontentinsightsop import (
        GetSeasonContentInsightsRequest,
        GetSeasonContentInsightsRequestTypedDict,
        Tag,
    )
    from .getseasonplayerstatsop import (
        GetSeasonPlayerStatsPosition,
        GetSeasonPlayerStatsRequest,
        GetSeasonPlayerStatsRequestTypedDict,
        StatCategory,
    )
    from .getseasonweeksop import GetSeasonWeeksRequest, GetSeasonWeeksRequestTypedDict
    from .getstandingsop import GetStandingsRequest, GetStandingsRequestTypedDict
    from .getstatsboxscoreop import (
        GetStatsBoxscoreRequest,
        GetStatsBoxscoreRequestTypedDict,
    )
    from .getsummaryplayop import GetSummaryPlayRequest, GetSummaryPlayRequestTypedDict
    from .getteamdefensepassstatsbyseasonop import (
        GetTeamDefensePassStatsBySeasonRequest,
        GetTeamDefensePassStatsBySeasonRequestTypedDict,
        GetTeamDefensePassStatsBySeasonSortKey,
    )
    from .getteamdefensepassstatsbyweekop import (
        GetTeamDefensePassStatsByWeekRequest,
        GetTeamDefensePassStatsByWeekRequestTypedDict,
        GetTeamDefensePassStatsByWeekSortKey,
    )
    from .getteamdefenserushstatsbyseasonop import (
        GetTeamDefenseRushStatsBySeasonRequest,
        GetTeamDefenseRushStatsBySeasonRequestTypedDict,
        GetTeamDefenseRushStatsBySeasonSortKey,
    )
    from .getteamdefenserushstatsbyweekop import (
        GetTeamDefenseRushStatsByWeekRequest,
        GetTeamDefenseRushStatsByWeekRequestTypedDict,
        GetTeamDefenseRushStatsByWeekSortKey,
    )
    from .getteamdefensestatsbyseasonop import (
        GetTeamDefenseStatsBySeasonRequest,
        GetTeamDefenseStatsBySeasonRequestTypedDict,
        GetTeamDefenseStatsBySeasonSortKey,
        GetTeamDefenseStatsBySeasonSplit,
    )
    from .getteamdefensestatsbyweekop import (
        GetTeamDefenseStatsByWeekRequest,
        GetTeamDefenseStatsByWeekRequestTypedDict,
        GetTeamDefenseStatsByWeekSortKey,
        GetTeamDefenseStatsByWeekSplit,
    )
    from .getteaminjuriesop import (
        GetTeamInjuriesRequest,
        GetTeamInjuriesRequestTypedDict,
    )
    from .getteamoffenseoverviewstatsbyseasonop import (
        GetTeamOffenseStatsBySeasonRequest,
        GetTeamOffenseStatsBySeasonRequestTypedDict,
        GetTeamOffenseStatsBySeasonSortKey,
        GetTeamOffenseStatsBySeasonSplit,
    )
    from .getteamoffenseoverviewstatsbyweekop import (
        GetTeamOffenseStatsByWeekRequest,
        GetTeamOffenseStatsByWeekRequestTypedDict,
        GetTeamOffenseStatsByWeekSortKey,
        GetTeamOffenseStatsByWeekSplit,
    )
    from .getteamoffensepassstatsbyseasonop import (
        GetTeamOffensePassStatsBySeasonRequest,
        GetTeamOffensePassStatsBySeasonRequestTypedDict,
        GetTeamOffensePassStatsBySeasonSortKey,
    )
    from .getteamoffensepassstatsbyweekop import (
        GetTeamOffensePassStatsByWeekRequest,
        GetTeamOffensePassStatsByWeekRequestTypedDict,
        GetTeamOffensePassStatsByWeekSortKey,
    )
    from .getteamrosterop import GetTeamRosterRequest, GetTeamRosterRequestTypedDict
    from .getteamscheduleop import (
        GetTeamScheduleRequest,
        GetTeamScheduleRequestTypedDict,
    )
    from .getteamstandingsop import (
        GetTeamStandingsRequest,
        GetTeamStandingsRequestTypedDict,
    )
    from .gettransactionsop import (
        GetTransactionsRequest,
        GetTransactionsRequestTypedDict,
        GetTransactionsTransactionType,
    )
    from .getvenuesop import GetVenuesRequest, GetVenuesRequestTypedDict
    from .getweeklybettingoddsop import (
        GetWeeklyBettingOddsRequest,
        GetWeeklyBettingOddsRequestTypedDict,
    )
    from .getweeklygamedetailsop import (
        GetWeeklyGameDetailsRequest,
        GetWeeklyGameDetailsRequestTypedDict,
    )
    from .getweeklyteamrosterop import (
        GetWeeklyTeamRosterRequest,
        GetWeeklyTeamRosterRequestTypedDict,
    )
    from .getwinprobabilityminop import (
        GetWinProbabilityMinRequest,
        GetWinProbabilityMinRequestTypedDict,
    )
    from .homefilmcardsresponse import (
        HomeFilmCardsResponse,
        HomeFilmCardsResponseTypedDict,
    )
    from .injuryentry import (
        InjuryEntry,
        InjuryEntryGameStatus,
        InjuryEntryTypedDict,
        PracticeStatus,
        PracticeStatusTypedDict,
    )
    from .injuryreportresponse import (
        InjuryReportResponse,
        InjuryReportResponseTypedDict,
    )
    from .insight import Insight, InsightPosition, InsightTypedDict, SecondTeamType
    from .kickingstats import KickingStats, KickingStatsTypedDict
    from .livegame import (
        AwayTeam,
        AwayTeamTypedDict,
        HomeTeam,
        HomeTeamTypedDict,
        LiveGame,
        LiveGameStatus,
        LiveGameTypedDict,
    )
    from .livescoresresponse import LiveScoresResponse, LiveScoresResponseTypedDict
    from .matchuprankingsresponse import (
        MatchupRankingsResponse,
        MatchupRankingsResponseTypedDict,
    )
    from .meridiemenum import MeridiemEnum
    from .moneyline import MoneyLine, MoneyLineTypedDict
    from .multiplerankingscategory import (
        MultipleRankingsCategory,
        MultipleRankingsCategoryPagination,
        MultipleRankingsCategoryPaginationTypedDict,
        MultipleRankingsCategoryTypedDict,
    )
    from .nearestdefenderstatsresponse import (
        NearestDefenderStatsResponse,
        NearestDefenderStatsResponseTypedDict,
    )
    from .oddsselection import OddsSelection, OddsSelectionTypedDict
    from .offensiveplayerpositionenum import OffensivePlayerPositionEnum
    from .offensiveskillpositionenum import OffensiveSkillPositionEnum
    from .overallrecord import (
        OverallRecord,
        OverallRecordPoints,
        OverallRecordPointsTypedDict,
        OverallRecordType,
        OverallRecordTypedDict,
        Streak,
        StreakTypedDict,
    )
    from .pagination import Pagination, PaginationTypedDict
    from .passerstats import PasserStats, PasserStatsTypedDict, Zone, ZoneTypedDict
    from .passingstats import PassingStats, PassingStatsTypedDict
    from .passingstatscategoryenum import PassingStatsCategoryEnum
    from .passingstatsresponse import (
        PassingStatsResponse,
        PassingStatsResponseTypedDict,
    )
    from .passrushstatsresponse import (
        PassRushStatsResponse,
        PassRushStatsResponseTypedDict,
    )
    from .penalty import Penalty, PenaltyTypedDict
    from .play import Play, PlayType, PlayTypedDict
    from .playbyplayresponse import PlayByPlayResponse, PlayByPlayResponseTypedDict
    from .playdetail import PlayDetail, PlayDetailTypedDict, PlayDirection, PlayState
    from .player import Player, PlayerTypedDict
    from .playerdetail import PlayerDetail, PlayerDetailTypedDict
    from .playergamestats import PlayerGameStats, PlayerGameStatsTypedDict
    from .playerpassingstats import PlayerPassingStats, PlayerPassingStatsTypedDict
    from .playerprojection import (
        PlayerProjection,
        PlayerProjectionTypedDict,
        Relationships,
        RelationshipsTypedDict,
        RelationshipsTypePlayerWeekProjectedPoints,
        RelationshipsTypePlayerWeekProjectedStats,
        TypePlayer,
        WeekPoint,
        WeekPointTypedDict,
        WeekStat,
        WeekStatTypedDict,
    )
    from .playerreceivingstats import (
        PlayerReceivingStats,
        PlayerReceivingStatsTypedDict,
    )
    from .playerrushingstats import PlayerRushingStats, PlayerRushingStatsTypedDict
    from .playersearchresponse import (
        PlayerSearchResponse,
        PlayerSearchResponseTypedDict,
    )
    from .playersearchresult import PlayerSearchResult, PlayerSearchResultTypedDict
    from .playerstatsresponse import (
        PlayerStatsResponse,
        PlayerStatsResponsePagination,
        PlayerStatsResponsePaginationTypedDict,
        PlayerStatsResponsePlayer,
        PlayerStatsResponsePlayerTypedDict,
        PlayerStatsResponseStats,
        PlayerStatsResponseStatsTypedDict,
        PlayerStatsResponseTypedDict,
    )
    from .playerweekprojectedpoints import (
        PlayerWeekProjectedPoints,
        PlayerWeekProjectedPointsAttributes,
        PlayerWeekProjectedPointsAttributesTypedDict,
        PlayerWeekProjectedPointsType,
        PlayerWeekProjectedPointsTypedDict,
    )
    from .playerweekprojectedstats import (
        PlayerWeekProjectedStats,
        PlayerWeekProjectedStatsAttributes,
        PlayerWeekProjectedStatsAttributesTypedDict,
        PlayerWeekProjectedStatsType,
        PlayerWeekProjectedStatsTypedDict,
    )
    from .playparticipant import (
        PlayParticipant,
        PlayParticipantStats,
        PlayParticipantStatsTypedDict,
        PlayParticipantTypedDict,
        Role,
    )
    from .playplayer import PlayPlayer, PlayPlayerTypedDict
    from .playstat import PlayStat, PlayStatTypedDict
    from .playsummaryresponse import PlaySummaryResponse, PlaySummaryResponseTypedDict
    from .playtypeenum import PlayTypeEnum
    from .playwinprobability import PlayWinProbability, PlayWinProbabilityTypedDict
    from .pointspread import PointSpread, PointSpreadTypedDict
    from .pointsrecord import (
        PointsRecord,
        PointsRecordPoints,
        PointsRecordPointsTypedDict,
        PointsRecordTypedDict,
    )
    from .practicestatusenum import PracticeStatusEnum
    from .progame import (
        ProGame,
        ProGameCategory,
        ProGameExtension,
        ProGameExtensionTypedDict,
        ProGameStatus,
        ProGameTypedDict,
    )
    from .projectedstatsresponse import (
        Included,
        IncludedTypedDict,
        Meta,
        MetaTypedDict,
        Page,
        PageTypedDict,
        ProjectedStatsResponse,
        ProjectedStatsResponsePagination,
        ProjectedStatsResponsePaginationTypedDict,
        ProjectedStatsResponseTypedDict,
    )
    from .proteam import (
        ProTeam,
        ProTeamConferenceAbbr,
        ProTeamTeamType,
        ProTeamTypedDict,
    )
    from .proweek import ProWeek, ProWeekTypedDict, ProWeekWeekType
    from .receivingstats import ReceivingStats, ReceivingStatsTypedDict
    from .receivingstatscategoryenum import ReceivingStatsCategoryEnum
    from .receivingstatsresponse import (
        ReceivingStatsResponse,
        ReceivingStatsResponseTypedDict,
    )
    from .record import Record, RecordTypedDict
    from .refreshtokenrequest import (
        RefreshTokenRequest,
        RefreshTokenRequestNetworkType,
        RefreshTokenRequestTypedDict,
    )
    from .responsemetadata import ResponseMetadata, ResponseMetadataTypedDict
    from .rosterresponse import (
        Roster,
        RosterResponse,
        RosterResponseTypedDict,
        RosterTypedDict,
    )
    from .rushingstats import RushingStats, RushingStatsTypedDict
    from .rushingstatsresponse import (
        RushingStatsResponse,
        RushingStatsResponseTypedDict,
    )
    from .scheduledgame import ScheduledGame, ScheduledGameTypedDict
    from .scheduleteam import ScheduleTeam, ScheduleTeamTypedDict
    from .scoringplay import ScoreType, ScoringPlay, ScoringPlayTypedDict
    from .searchplayersop import SearchPlayersRequest, SearchPlayersRequestTypedDict
    from .seasonstats import SeasonStats, SeasonStatsTypedDict
    from .seasontypeenum import SeasonTypeEnum
    from .seasonweeksresponse import SeasonWeeksResponse, SeasonWeeksResponseTypedDict
    from .security import Security, SecurityTypedDict
    from .site import Site, SiteRoofType, SiteTypedDict
    from .socialmedia import SocialMedia, SocialMediaTypedDict
    from .sortorderenum import SortOrderEnum
    from .standings import (
        Standings,
        StandingsTeam,
        StandingsTeamTypedDict,
        StandingsTypedDict,
    )
    from .standingsrecord import (
        StandingsRecord,
        StandingsRecordPoints,
        StandingsRecordPointsTypedDict,
        StandingsRecordTypedDict,
    )
    from .standingsresponse import (
        StandingsResponse,
        StandingsResponseTypedDict,
        StandingsResponseWeek,
        StandingsResponseWeekTypedDict,
    )
    from .statisticranking import (
        Statistic,
        StatisticRanking,
        StatisticRankingTypedDict,
        StatisticTypedDict,
    )
    from .team import Team, TeamConferenceAbbr, TeamTeamType, TeamTypedDict
    from .teamboxscore import TeamBoxscore, TeamBoxscoreTypedDict
    from .teamdefensepassstats import (
        TeamDefensePassStats,
        TeamDefensePassStatsTypedDict,
    )
    from .teamdefensepassstatsresponse import (
        TeamDefensePassStatsResponse,
        TeamDefensePassStatsResponseTypedDict,
    )
    from .teamdefenserushstats import (
        TeamDefenseRushStats,
        TeamDefenseRushStatsTypedDict,
    )
    from .teamdefenserushstatsresponse import (
        TeamDefenseRushStatsResponse,
        TeamDefenseRushStatsResponseTypedDict,
    )
    from .teamdefensestats import TeamDefenseStats, TeamDefenseStatsTypedDict
    from .teamdefensestatsresponse import (
        TeamDefenseStatsResponse,
        TeamDefenseStatsResponseTypedDict,
    )
    from .teamgamestats import TeamGameStats, TeamGameStatsTypedDict
    from .teaminfo import TeamInfo, TeamInfoTypedDict
    from .teaminjuryreport import TeamInjuryReport, TeamInjuryReportTypedDict
    from .teammatchuprankings import TeamMatchupRankings, TeamMatchupRankingsTypedDict
    from .teamoffenseoverviewstats import TeamOffenseStats, TeamOffenseStatsTypedDict
    from .teamoffenseoverviewstatsresponse import (
        TeamOffenseStatsResponse,
        TeamOffenseStatsResponseTypedDict,
    )
    from .teamoffensepassstats import (
        TeamOffensePassStats,
        TeamOffensePassStatsTypedDict,
    )
    from .teamoffensepassstatsresponse import (
        TeamOffensePassStatsResponse,
        TeamOffensePassStatsResponseTypedDict,
    )
    from .teamrankingentry import TeamRankingEntry, TeamRankingEntryTypedDict
    from .teamrankings import TeamRankings, TeamRankingsTypedDict
    from .teamrankingsresponse import (
        TeamRankingsResponse,
        TeamRankingsResponseTypedDict,
    )
    from .teamrosterresponse import TeamRosterResponse, TeamRosterResponseTypedDict
    from .teamscore import TeamScore, TeamScoreTypedDict
    from .teamtypeenum import TeamTypeEnum
    from .teamvenue import TeamVenue, TeamVenueTypedDict
    from .ticketvendor import TicketVendor, TicketVendorTypedDict
    from .tokenrequest import (
        TokenRequest,
        TokenRequestNetworkType,
        TokenRequestTypedDict,
    )
    from .tokenresponse import TokenResponse, TokenResponseTypedDict
    from .totals import Totals, TotalsTypedDict
    from .transaction import Transaction, TransactionType, TransactionTypedDict
    from .transactionsresponse import (
        TransactionsResponse,
        TransactionsResponseTypedDict,
    )
    from .venue import Venue, VenueTypedDict
    from .venueinfo import VenueInfo, VenueInfoRoofType, VenueInfoTypedDict
    from .venuesresponse import VenuesResponse, VenuesResponseTypedDict
    from .videoauthorizations import (
        NFLPLUSPLUSNFLPLUSCOACHESFILM,
        NflPlusPlus,
        NFLPLUSPLUSNFLPLUSCOACHESFILMTypedDict,
        NflPlusPlusRequirements,
        NflPlusPlusRequirementsTypedDict,
        NflPlusPlusTypedDict,
        NflPlusPremium,
        NFLPLUSPremiumNFLPLUSCOACHESFILM,
        NFLPLUSPremiumNFLPLUSCOACHESFILMTypedDict,
        NflPlusPremiumRequirements,
        NflPlusPremiumRequirementsTypedDict,
        NflPlusPremiumTypedDict,
        ProPremium,
        ProPremiumNFLPLUSCOACHESFILM,
        ProPremiumNFLPLUSCOACHESFILMTypedDict,
        ProPremiumRequirements,
        ProPremiumRequirementsTypedDict,
        ProPremiumTypedDict,
        VideoAuthorizations,
        VideoAuthorizationsTypedDict,
    )
    from .videogameplayids import VideoGamePlayIds, VideoGamePlayIdsTypedDict
    from .videotag import VideoTag, VideoTagTypedDict
    from .videothumbnail import VideoThumbnail, VideoThumbnailTypedDict
    from .week import Week, WeekTypedDict, WeekWeekType
    from .weeklygamedetail import (
        DriveChart,
        DriveChartTypedDict,
        Replay,
        ReplayTypedDict,
        Summary,
        SummaryTypedDict,
        TaggedVideos,
        TaggedVideosTypedDict,
        WeeklyGameDetail,
        WeeklyGameDetailCategory,
        WeeklyGameDetailExtension,
        WeeklyGameDetailExtensionTypedDict,
        WeeklyGameDetailStatus,
        WeeklyGameDetailTypedDict,
    )
    from .weeklyoddsresponse import WeeklyOddsResponse, WeeklyOddsResponseTypedDict
    from .weeklypassingstatsresponse import (
        WeeklyPassingStatsResponse,
        WeeklyPassingStatsResponseTypedDict,
    )
    from .weeklyplayer import WeeklyPlayer, WeeklyPlayerTypedDict
    from .weeklyplayerpassingstats import (
        WeeklyPlayerPassingStats,
        WeeklyPlayerPassingStatsTypedDict,
    )
    from .weeklyplayerrushingstats import (
        WeeklyPlayerRushingStats,
        WeeklyPlayerRushingStatsTypedDict,
    )
    from .weeklyrosterresponse import (
        WeeklyRosterResponse,
        WeeklyRosterResponseTypedDict,
    )
    from .weeklyrushingstatsresponse import (
        WeeklyRushingStatsResponse,
        WeeklyRushingStatsResponseTypedDict,
    )
    from .weekslugenum import WeekSlugEnum
    from .weeksresponse import WeeksResponse, WeeksResponseTypedDict
    from .winprobabilityresponse import (
        WinProbabilityResponse,
        WinProbabilityResponseTypedDict,
    )

__all__ = [
    "AirYardType",
    "Award",
    "AwardType",
    "AwardTypedDict",
    "Away",
    "AwayTeam",
    "AwayTeamTypedDict",
    "AwayTypedDict",
    "Background",
    "BackgroundTypedDict",
    "DesignationEnum",
    "CollegeClassEnum",
    "BenchPress",
    "BroadJump",
    "FortyYardDash",
    "TenYardSplit",
    "ThreeConeDrill",
    "TwentyYardShuffle",
    "VerticalJump",
    "BenchPressTypedDict",
    "BroadJumpTypedDict",
    "FortyYardDashTypedDict",
    "TenYardSplitTypedDict",
    "ThreeConeDrillTypedDict",
    "TwentyYardShuffleTypedDict",
    "VerticalJumpTypedDict",
    "CombineRankingsResponse",
    "CombineRankingsResponseTypedDict",
    "EventFilterEnum",
    "CombineProfile",
    "CombineProfileTypedDict",
    "CombinePerson",
    "CombinePersonTypedDict",
    "CombineProfilesResponse",
    "CombineProfilesResponseTypedDict",
    "GetCombineProfilesRequest",
    "GetCombineProfilesRequestTypedDict",
    "GetCombineRankingsRequest",
    "GetCombineRankingsRequestTypedDict",
    "BinaryFlagEnum",
    "BoxScoreResponse2",
    "BoxScoreResponse2TypedDict",
    "BoxscoreResponse",
    "BoxscoreResponseTypedDict",
    "BoxscoreSchedule",
    "BoxscoreScheduleTypedDict",
    "BoxscoreScore",
    "BoxscoreScoreTypedDict",
    "BoxscoreSite",
    "BoxscoreSiteRoofType",
    "BoxscoreSiteTypedDict",
    "BoxscoreTeam",
    "BoxscoreTeamTypedDict",
    "BroadcastInfo",
    "BroadcastInfoTypedDict",
    "CameraSource",
    "CareerStats",
    "CareerStatsTypedDict",
    "Clinched",
    "ClinchedTypedDict",
    "CoachesFilmResponse",
    "CoachesFilmResponseTypedDict",
    "CoachesFilmVideo",
    "CoachesFilmVideoType",
    "CoachesFilmVideoTypedDict",
    "Conference",
    "ConferenceEnum",
    "ConferenceTypedDict",
    "Content",
    "ContentTypedDict",
    "ContractInfo",
    "ContractInfoTypedDict",
    "Cta",
    "CtaTypedDict",
    "CurrentGame",
    "CurrentGameCategory",
    "CurrentGameExtension",
    "CurrentGameExtensionTypedDict",
    "CurrentGameTypedDict",
    "CurrentGamesResponse",
    "CurrentGamesResponseTypedDict",
    "DefCoverageType",
    "DefendersInTheBoxType",
    "DefensiveOverviewStatsResponse",
    "DefensiveOverviewStatsResponseTypedDict",
    "DefensivePassRushStats",
    "DefensivePassRushStatsNgsPosition",
    "DefensivePassRushStatsPosition",
    "DefensivePassRushStatsTypedDict",
    "DefensivePlayerOverviewStats",
    "DefensivePlayerOverviewStatsNgsPosition",
    "DefensivePlayerOverviewStatsPosition",
    "DefensivePlayerOverviewStatsTypedDict",
    "DefensiveNearestDefenderStats",
    "DefenseNGSSplitEnum",
    "DefensePositionEnum",
    "DefensePositionGroupEnum",
    "DefenseNGSPositionEnum",
    "DefenseNGSPositionGroupEnum",
    "DefensiveNearestDefenderStatsTypedDict",
    "DefensiveStats",
    "NearestDefenderStatsResponse",
    "NearestDefenderStatsResponseTypedDict",
    "DefensiveStatsTypedDict",
    "Division",
    "DivisionTypedDict",
    "DraftPick",
    "DraftPickTypedDict",
    "DraftResponse",
    "DraftResponseTypedDict",
    "Drive",
    "DriveChart",
    "DriveChartTypedDict",
    "DriveTypedDict",
    "DropbackTimeType",
    "DownEnum",
    "ExperienceGamesResponse",
    "ExperienceGamesResponseTypedDict",
    "ExperienceTeamsResponse",
    "ExperienceTeamsResponseTypedDict",
    "ExternalID",
    "ExternalIDTypedDict",
    "FantasyPlayerStats",
    "FantasyPlayerStatsPosition",
    "FantasyPlayerStatsTypedDict",
    "FantasyStatsResponse",
    "FantasyStatsResponseTypedDict",
    "FilmCard",
    "FilmCardTypedDict",
    "FilmroomPlay",
    "FilmroomPlayTypedDict",
    "FilmroomPlaysResponse",
    "FilmroomPlaysResponseTypedDict",
    "Fixture",
    "FixtureTypedDict",
    "FootballGamesResponse",
    "FootballGamesResponseTypedDict",
    "FuturesMarket",
    "FuturesMarketTypedDict",
    "FuturesOddsResponse",
    "FuturesOddsResponseData",
    "FuturesOddsResponseDataTypedDict",
    "FuturesOddsResponseTypedDict",
    "Game",
    "GameCategory",
    "GameDetail",
    "GameDetailTypedDict",
    "GameExtension",
    "GameExtensionTypedDict",
    "GameID",
    "GameIDTypedDict",
    "GameInsight",
    "GameInsightTypedDict",
    "GameLocationEnum",
    "GameOdds",
    "GameOddsTypedDict",
    "GamePreviewResponse",
    "GamePreviewResponseTypedDict",
    "GameResultEnum",
    "GameSchedule",
    "GameScheduleTypedDict",
    "GameScore",
    "GameScoreTypedDict",
    "GameSite",
    "GameSiteRoofType",
    "GameSiteTypedDict",
    "GameStatsResponse",
    "GameStatsResponseData",
    "GameStatsResponseDataTypedDict",
    "GameStatsResponseTypedDict",
    "GameStatus",
    "GameStatusEnum",
    "GameTeam",
    "GameTeamTypedDict",
    "GameTypedDict",
    "GamecenterResponse",
    "GamecenterResponseTypedDict",
    "GamecenterSchedule",
    "GamecenterScheduleTypedDict",
    "GamesResponse",
    "GamesResponseTypedDict",
    "GetCoachesFilmVideosRequest",
    "GetCoachesFilmVideosRequestTypedDict",
    "GetDefensiveOverviewStatsBySeasonRequest",
    "GetDefensiveOverviewStatsBySeasonRequestTypedDict",
    "GetDefensiveOverviewStatsBySeasonSortKey",
    "GetDefensiveOverviewStatsByWeekRequest",
    "GetDefensiveOverviewStatsByWeekRequestTypedDict",
    "GetDefensiveOverviewStatsByWeekSortKey",
    "GetDefensivePassRushStatsByWeekRequest",
    "GetDefensivePassRushStatsByWeekRequestTypedDict",
    "GetDefensivePassRushStatsByWeekSortKey",
    "GetDefensivePassRushStatsBySeasonRequest",
    "GetDefensivePassRushStatsBySeasonRequestTypedDict",
    "GetDefensivePassRushStatsBySeasonSortKey",
    "GetDefensiveNearestDefenderStatsBySeasonRequest",
    "GetDefensiveNearestDefenderStatsBySeasonRequestTypedDict",
    "GetDefensiveNearestDefenderStatsBySeasonSortKey",
    "GetDefensiveNearestDefenderStatsByWeekRequest",
    "GetDefensiveNearestDefenderStatsByWeekRequestTypedDict",
    "GetDefensiveNearestDefenderStatsByWeekSortKey",
    "GetDefensiveStatsBySeasonRequestTypedDict",
    "GetDefensiveStatsBySeasonSortKey",
    "GetDraftInfoRequest",
    "GetDraftInfoRequestTypedDict",
    "GetDraftPicksReportRequest",
    "GetDraftPicksReportRequestTypedDict",
    "GetExperienceGamesRequest",
    "GetExperienceGamesRequestTypedDict",
    "GetExperienceTeamsRequest",
    "GetExperienceTeamsRequestTypedDict",
    "GetFantasyStatsBySeasonPositionGroup",
    "GetFantasyStatsBySeasonRequest",
    "GetFantasyStatsBySeasonRequestTypedDict",
    "GetFantasyStatsBySeasonSortKey",
    "GetFilmroomPlaysRequest",
    "GetFilmroomPlaysRequestTypedDict",
    "GetFootballBoxScoreRequest",
    "GetFootballBoxScoreRequestTypedDict",
    "GetFootballGamesRequest",
    "GetFootballGamesRequestTypedDict",
    "GetGameInsightsRequest",
    "GetGameInsightsRequestTypedDict",
    "GetGameMatchupRankingsRequest",
    "GetGameMatchupRankingsRequestTypedDict",
    "GetGamePreviewRequest",
    "GetGamePreviewRequestTypedDict",
    "GetGameTeamRankingsRequest",
    "GetGameTeamRankingsRequestTypedDict",
    "GetGamecenterRequest",
    "GetGamecenterRequestTypedDict",
    "GetInjuryReportsRequest",
    "GetInjuryReportsRequestTypedDict",
    "GetLiveGameScoresRequest",
    "GetLiveGameScoresRequestTypedDict",
    "GetLiveGameStatsRequest",
    "GetLiveGameStatsRequestTypedDict",
    "GetMultipleRankingsAllTeamsRequest",
    "GetMultipleRankingsAllTeamsRequestTypedDict",
    "GetPlayByPlayRequest",
    "GetPlayByPlayRequestTypedDict",
    "GetPlayListRequest",
    "GetPlayListRequestTypedDict",
    "GetPlayerDetailsRequest",
    "GetPlayerDetailsRequestTypedDict",
    "GetPlayerPassingStatsBySeasonRequest",
    "GetPlayerPassingStatsBySeasonRequestTypedDict",
    "GetPlayerPassingStatsByWeekRequest",
    "GetPlayerPassingStatsByWeekRequestTypedDict",
    "GetPlayerReceivingStatsBySeasonRequest",
    "GetPlayerReceivingStatsBySeasonRequestTypedDict",
    "GetPlayerReceivingStatsByWeekRequest",
    "GetPlayerReceivingStatsByWeekRequestTypedDict",
    "GetPlayerRequest",
    "GetPlayerRequestTypedDict",
    "GetPlayerRushingStatsBySeasonRequest",
    "GetPlayerRushingStatsBySeasonRequestTypedDict",
    "GetPlayerRushingStatsBySeasonSortKey",
    "GetPlayerRushingStatsByWeekRequest",
    "GetPlayerRushingStatsByWeekRequestTypedDict",
    "GetPlayerRushingStatsByWeekSortKey",
    "GetPlayersTeamRosterRequest",
    "GetPlayersTeamRosterRequestTypedDict",
    "GetPlaysWinProbabilityRequest",
    "GetPlaysWinProbabilityRequestTypedDict",
    "GetPlaysWinProbabilityResponse",
    "GetPlaysWinProbabilityResponseTypedDict",
    "GetProjectedStatsRequest",
    "GetProjectedStatsRequestTypedDict",
    "GetScheduleSeasonWeeksRequest",
    "GetScheduleSeasonWeeksRequestTypedDict",
    "GetScheduledGameRequest",
    "GetScheduledGameRequestTypedDict",
    "GetScheduledGamesRequest",
    "GetScheduledGamesRequestTypedDict",
    "GetSeasonContentInsightsRequest",
    "GetSeasonContentInsightsRequestTypedDict",
    "GetSeasonPlayerStatsPosition",
    "GetSeasonPlayerStatsRequest",
    "GetSeasonPlayerStatsRequestTypedDict",
    "GetSeasonWeeksRequest",
    "GetSeasonWeeksRequestTypedDict",
    "GetStandingsRequest",
    "GetStandingsRequestTypedDict",
    "GetStatsBoxscoreRequest",
    "GetStatsBoxscoreRequestTypedDict",
    "GetSummaryPlayRequest",
    "GetSummaryPlayRequestTypedDict",
    "GetTeamDefensePassStatsBySeasonRequest",
    "GetTeamDefensePassStatsBySeasonRequestTypedDict",
    "GetTeamDefensePassStatsBySeasonSortKey",
    "GetTeamDefenseRushStatsBySeasonRequest",
    "GetTeamDefenseRushStatsBySeasonRequestTypedDict",
    "GetTeamDefenseRushStatsBySeasonSortKey",
    "GetTeamDefenseStatsBySeasonRequest",
    "GetTeamDefenseStatsBySeasonRequestTypedDict",
    "GetTeamDefenseStatsBySeasonSortKey",
    "GetTeamDefenseStatsBySeasonSplit",
    "GetTeamDefensePassStatsByWeekRequest",
    "GetTeamDefensePassStatsByWeekRequestTypedDict",
    "GetTeamDefensePassStatsByWeekSortKey",
    "GetTeamDefenseRushStatsByWeekRequest",
    "GetTeamDefenseRushStatsByWeekRequestTypedDict",
    "GetTeamDefenseRushStatsByWeekSortKey",
    "GetTeamDefenseStatsByWeekRequest",
    "GetTeamDefenseStatsByWeekRequestTypedDict",
    "GetTeamDefenseStatsByWeekSortKey",
    "GetTeamDefenseStatsByWeekSplit",
    "GetTeamInjuriesRequest",
    "GetTeamInjuriesRequestTypedDict",
    "GetTeamOffenseStatsBySeasonRequest",
    "GetTeamOffenseStatsBySeasonRequestTypedDict",
    "GetTeamOffenseStatsBySeasonSortKey",
    "GetTeamOffenseStatsBySeasonSplit",
    "GetTeamOffenseStatsByWeekRequest",
    "GetTeamOffenseStatsByWeekRequestTypedDict",
    "GetTeamOffenseStatsByWeekSortKey",
    "GetTeamOffenseStatsByWeekSplit",
    "GetTeamOffensePassStatsBySeasonRequest",
    "GetTeamOffensePassStatsBySeasonRequestTypedDict",
    "GetTeamOffensePassStatsBySeasonSortKey",
    "GetTeamOffensePassStatsByWeekRequest",
    "GetTeamOffensePassStatsByWeekRequestTypedDict",
    "GetTeamOffensePassStatsByWeekSortKey",
    "GetTeamOffenseRushStatsByWeekRequestTypedDict",
    "GetTeamOffenseRushStatsByWeekRequest",
    "GetTeamOffenseRushStatsBySeasonRequestTypedDict",
    "GetTeamOffenseRushStatsByWeekSortKey",
    "GetTeamOffenseRushStatsBySeasonRequest",
    "GetTeamOffenseRushStatsBySeasonSortKey",
    "GetTeamNeedsRequest",
    "GetTeamNeedsRequestTypedDict",
    "GetWeekOfDateRequest",
    "GetWeekOfDateRequestTypedDict",
    "TeamOffenseRushStats",
    "TeamOffenseRushStatsTypedDict",
    "TeamOffenseRushStatsResponse",
    "TeamOffenseRushStatsResponseTypedDict",
    "GetTeamRosterRequest",
    "GetTeamRosterRequestTypedDict",
    "GetTeamScheduleRequest",
    "GetTeamScheduleRequestTypedDict",
    "GetTeamStandingsRequest",
    "GetTeamStandingsRequestTypedDict",
    "GetTransactionsRequest",
    "GetTransactionsRequestTypedDict",
    "GetTransactionsTransactionType",
    "GetVenuesRequest",
    "GetVenuesRequestTypedDict",
    "GetWeeklyBettingOddsRequest",
    "GetWeeklyBettingOddsRequestTypedDict",
    "GetWeeklyGameDetailsRequest",
    "GetWeeklyGameDetailsRequestTypedDict",
    "GetWeeklyTeamRosterRequest",
    "GetWeeklyTeamRosterRequestTypedDict",
    "GetWinProbabilityMinRequest",
    "GetWinProbabilityMinRequestTypedDict",
    "Home",
    "HomeFilmCardsResponse",
    "HomeFilmCardsResponseTypedDict",
    "HomeTeam",
    "HomeTeamTypedDict",
    "HomeTypedDict",
    "Image",
    "ImageTypedDict",
    "Included",
    "IncludedTypedDict",
    "InjuryEntry",
    "InjuryEntryGameStatus",
    "InjuryEntryTypedDict",
    "InjuryReportResponse",
    "InjuryReportResponseTypedDict",
    "Insight",
    "InsightPosition",
    "InsightTypedDict",
    "InternationalWatchOption",
    "InternationalWatchOptionTypedDict",
    "KickingStats",
    "KickingStatsTypedDict",
    "Leaders",
    "LeadersTypedDict",
    "LeagueAverageReceiverSeparation",
    "LeagueAverageReceiverSeparationTypedDict",
    "LeagueAverageSeparationToQb",
    "LeagueAverageSeparationToQbTypedDict",
    "LinkParams",
    "LinkParamsTypedDict",
    "LiveGame",
    "LiveGameStatus",
    "LiveGameTypedDict",
    "LiveScoresResponse",
    "LiveScoresResponseTypedDict",
    "MatchupRankingsResponse",
    "MatchupRankingsResponseTypedDict",
    "MeridiemEnum",
    "Meta",
    "MetaTypedDict",
    "MoneyLine",
    "MoneyLineTypedDict",
    "MultipleRankingsCategory",
    "MultipleRankingsCategoryPagination",
    "MultipleRankingsCategoryPaginationTypedDict",
    "MultipleRankingsCategoryTypedDict",
    "NFLPLUSPLUSNFLPLUSCOACHESFILM",
    "NFLPLUSPLUSNFLPLUSCOACHESFILMTypedDict",
    "NFLPLUSPremiumNFLPLUSCOACHESFILM",
    "NFLPLUSPremiumNFLPLUSCOACHESFILMTypedDict",
    "NflPlusPlus",
    "NflPlusPlusRequirements",
    "NflPlusPlusRequirementsTypedDict",
    "NflPlusPlusTypedDict",
    "NflPlusPremium",
    "NflPlusPremiumRequirements",
    "NflPlusPremiumRequirementsTypedDict",
    "NflPlusPremiumTypedDict",
    "OddsSelection",
    "OddsSelectionTypedDict",
    "OffensivePlayerPositionEnum",
    "OffensiveSkillPositionEnum",
    "OverallRecord",
    "OverallRecordPoints",
    "OverallRecordPointsTypedDict",
    "OverallRecordType",
    "OverallRecordTypedDict",
    "Page",
    "PageTypedDict",
    "Pagination",
    "PaginationTypedDict",
    "PassDistanceLeaders",
    "PassDistanceLeadersTypedDict",
    "PassRushStatsResponse",
    "PassRushStatsResponseTypedDict",
    "PassRushers",
    "PassRushersTypedDict",
    "PasserStats",
    "PasserStatsTypedDict",
    "Passers",
    "PassersTypedDict",
    "PassingStats",
    "PassingStatsCategoryEnum",
    "PassingStatsResponse",
    "PassingStatsResponseTypedDict",
    "PassingStatsTypedDict",
    "Penalty",
    "PenaltyTypedDict",
    "Personnel",
    "Phase",
    "Play",
    "PlayByPlayResponse",
    "PlayByPlayResponseTypedDict",
    "PlayDetail",
    "PlayDetailTypedDict",
    "PlayDirection",
    "PlayParticipant",
    "PlayParticipantStats",
    "PlayParticipantStatsTypedDict",
    "PlayParticipantTypedDict",
    "PlayPlayer",
    "PlayPlayerTypedDict",
    "PlayStat",
    "PlayStatTypedDict",
    "PlayState",
    "PlaySummaryResponse",
    "PlaySummaryResponseTypedDict",
    "PlayType",
    "PlayTypeEnum",
    "PlayTypedDict",
    "PlayWinProbability",
    "PlayWinProbabilityTypedDict",
    "Player",
    "PlayerDetail",
    "PlayerDetailTypedDict",
    "PlayerGameStats",
    "PlayerGameStatsTypedDict",
    "PlayerPassingStats",
    "PlayerPassingStatsTypedDict",
    "PlayerProjection",
    "PlayerProjectionTypedDict",
    "PlayerReceivingStats",
    "PlayerReceivingStatsTypedDict",
    "PlayerRushingStats",
    "PlayerRushingStatsTypedDict",
    "PlayerSearchResponse",
    "PlayerSearchResponseTypedDict",
    "PlayerSearchResult",
    "PlayerSearchResultTypedDict",
    "PlayerStats",
    "PlayerStatsResponse",
    "PlayerStatsResponsePagination",
    "PlayerStatsResponsePaginationTypedDict",
    "PlayerStatsResponsePlayer",
    "PlayerStatsResponsePlayerTypedDict",
    "PlayerStatsResponseStats",
    "PlayerStatsResponseStatsTypedDict",
    "PlayerStatsResponseTypedDict",
    "PlayerStatsTypedDict",
    "PlayerTypedDict",
    "PlayerWeekProjectedPoints",
    "PlayerWeekProjectedPointsAttributes",
    "PlayerWeekProjectedPointsAttributesTypedDict",
    "PlayerWeekProjectedPointsType",
    "PlayerWeekProjectedPointsTypedDict",
    "PlayerWeekProjectedStats",
    "PlayerWeekProjectedStatsAttributes",
    "PlayerWeekProjectedStatsAttributesTypedDict",
    "PlayerWeekProjectedStatsType",
    "PlayerWeekProjectedStatsTypedDict",
    "PointSpread",
    "PointSpreadTypedDict",
    "PointsRecord",
    "PointsRecordPoints",
    "PointsRecordPointsTypedDict",
    "PointsRecordTypedDict",
    "PositionGroup",
    "PracticeStatus",
    "PracticeStatusEnum",
    "PracticeStatusTypedDict",
    "Preview",
    "PreviewTypedDict",
    "QuarterEnum",
    "ProGame",
    "ProGameCategory",
    "ProGameExtension",
    "ProGameExtensionTypedDict",
    "ProGameStatus",
    "ProGameTypedDict",
    "ProPremium",
    "ProPremiumNFLPLUSCOACHESFILM",
    "ProPremiumNFLPLUSCOACHESFILMTypedDict",
    "ProPremiumRequirements",
    "ProPremiumRequirementsTypedDict",
    "ProPremiumTypedDict",
    "ProTeam",
    "ProTeamConferenceAbbr",
    "ProTeamTeamType",
    "ProTeamTypedDict",
    "ProWeek",
    "ProWeekTypedDict",
    "ProWeekWeekType",
    "ProjectedStatsResponse",
    "ProjectedStatsResponsePagination",
    "ProjectedStatsResponsePaginationTypedDict",
    "ProjectedStatsResponseTypedDict",
    "PromoAsset",
    "PromoAssetTypedDict",
    "QbAlignment",
    "ReceiverAlignment",
    "Receivers",
    "ReceiversTypedDict",
    "ReceivingStats",
    "ReceivingStatsCategoryEnum",
    "ReceivingStatsResponse",
    "ReceivingStatsResponseTypedDict",
    "ReceivingStatsTypedDict",
    "Record",
    "RecordTypedDict",
    "RefreshTokenRequest",
    "RefreshTokenRequestNetworkType",
    "RefreshTokenRequestTypedDict",
    "Relationships",
    "RelationshipsTypePlayerWeekProjectedPoints",
    "RelationshipsTypePlayerWeekProjectedStats",
    "RelationshipsTypedDict",
    "Replay",
    "ReplayTypedDict",
    "ResponseMetadata",
    "ResponseMetadataTypedDict",
    "Result",
    "Role",
    "Roster",
    "RosterResponse",
    "RosterResponseTypedDict",
    "RosterTypedDict",
    "Round",
    "RoundTypedDict",
    "RushDirection",
    "Rushers",
    "RushersTypedDict",
    "RushingStats",
    "RushingStatsResponse",
    "RushingStatsResponseTypedDict",
    "RushingStatsTypedDict",
    "ScheduleTeam",
    "ScheduleTeamTypedDict",
    "ScheduledGame",
    "ScheduledGameTypedDict",
    "Score",
    "ScoreType",
    "ScoreTypedDict",
    "ScoringPlay",
    "ScoringPlayTypedDict",
    "SearchPlayersRequest",
    "SearchPlayersRequestTypedDict",
    "SeasonStats",
    "SeasonStatsTypedDict",
    "SeasonTypeEnum",
    "SeasonWeeksResponse",
    "SeasonWeeksResponseTypedDict",
    "SecondTeamType",
    "Security",
    "SecurityTypedDict",
    "SeparationType",
    "Site",
    "SiteRoofType",
    "SiteTypedDict",
    "SocialMedia",
    "SocialMediaTypedDict",
    "SortOrderEnum",
    "SpeedLeaders",
    "SpeedLeadersTypedDict",
    "Standings",
    "StandingsRecord",
    "StandingsRecordPoints",
    "StandingsRecordPointsTypedDict",
    "StandingsRecordTypedDict",
    "StandingsResponse",
    "StandingsResponseTypedDict",
    "StandingsResponseWeek",
    "StandingsResponseWeekTypedDict",
    "StandingsTeam",
    "StandingsTeamTypedDict",
    "StandingsTypedDict",
    "StatCategory",
    "Statistic",
    "StatisticRanking",
    "StatisticRankingTypedDict",
    "StatisticTypedDict",
    "Streak",
    "StreakTypedDict",
    "StreamingNetwork",
    "StreamingNetworkTypedDict",
    "SubType",
    "Summary",
    "SummaryTypedDict",
    "Tag",
    "TaggedVideos",
    "TaggedVideosTypedDict",
    "TargetLocation",
    "Team",
    "TeamBoxscore",
    "TeamBoxscoreTypedDict",
    "TeamConferenceAbbr",
    "TeamDefensePassStats",
    "TeamDefensePassStatsResponse",
    "TeamDefensePassStatsResponseTypedDict",
    "TeamDefensePassStatsTypedDict",
    "TeamDefenseRushStats",
    "TeamDefenseRushStatsResponse",
    "TeamDefenseRushStatsResponseTypedDict",
    "TeamDefenseRushStatsTypedDict",
    "TeamDefenseStats",
    "TeamDefenseStatsResponse",
    "TeamDefenseStatsResponseTypedDict",
    "TeamDefenseStatsTypedDict",
    "TeamGameStats",
    "TeamGameStatsTypedDict",
    "TeamInfo",
    "TeamInfoTypedDict",
    "TeamInjuryReport",
    "TeamInjuryReportTypedDict",
    "TeamMatchupRankings",
    "TeamMatchupRankingsTypedDict",
    "TeamNeedsResponse",
    "TeamNeedsResponseTypedDict",
    "TeamOffenseStats",
    "TeamOffenseStatsResponse",
    "TeamOffenseStatsResponseTypedDict",
    "TeamOffenseStatsTypedDict",
    "TeamOffensePassStats",
    "TeamOffensePassStatsResponse",
    "TeamOffensePassStatsResponseTypedDict",
    "TeamOffensePassStatsTypedDict",
    "TeamRankingEntry",
    "TeamRankingEntryTypedDict",
    "TeamRankings",
    "TeamRankingsResponse",
    "TeamRankingsResponseTypedDict",
    "TeamRankingsTypedDict",
    "TeamRosterResponse",
    "TeamRosterResponseTypedDict",
    "TeamScore",
    "TeamScoreTypedDict",
    "TeamStats",
    "TeamStatsTypedDict",
    "TeamTeamType",
    "TeamTypeEnum",
    "TeamTypedDict",
    "TeamVenue",
    "TeamVenueTypedDict",
    "Territory",
    "TicketVendor",
    "TicketVendorTypedDict",
    "TimeToSackLeaders",
    "TimeToSackLeadersTypedDict",
    "TokenRequest",
    "TokenRequestNetworkType",
    "TokenRequestTypedDict",
    "TokenResponse",
    "TokenResponseTypedDict",
    "Totals",
    "TotalsTypedDict",
    "Transaction",
    "TransactionType",
    "TransactionTypedDict",
    "TransactionsResponse",
    "TransactionsResponseTypedDict",
    "TypePlayer",
    "Venue",
    "VenueInfo",
    "VenueInfoRoofType",
    "VenueInfoTypedDict",
    "VenueTypedDict",
    "VenuesResponse",
    "VenuesResponseTypedDict",
    "Video",
    "VideoAuthorizations",
    "VideoAuthorizationsTypedDict",
    "VideoGamePlayIds",
    "VideoGamePlayIdsTypedDict",
    "VideoTag",
    "VideoTagTypedDict",
    "VideoThumbnail",
    "VideoThumbnailTypedDict",
    "VideoTypedDict",
    "Week",
    "WeekPoint",
    "WeekPointTypedDict",
    "WeekSlugEnum",
    "WeekStat",
    "WeekStatTypedDict",
    "WeekTypedDict",
    "WeekWeekType",
    "WeeklyGameDetail",
    "WeeklyGameDetailCategory",
    "WeeklyGameDetailExtension",
    "WeeklyGameDetailExtensionTypedDict",
    "WeeklyGameDetailStatus",
    "WeeklyGameDetailTypedDict",
    "WeeklyOddsResponse",
    "WeeklyOddsResponseTypedDict",
    "WeeklyPassingStatsResponse",
    "WeeklyPassingStatsResponseTypedDict",
    "WeeklyPlayer",
    "WeeklyPlayerPassingStats",
    "WeeklyPlayerPassingStatsTypedDict",
    "WeeklyPlayerRushingStats",
    "WeeklyPlayerRushingStatsTypedDict",
    "WeeklyPlayerTypedDict",
    "WeeklyRosterResponse",
    "WeeklyRosterResponseTypedDict",
    "WeeklyRushingStatsResponse",
    "WeeklyRushingStatsResponseTypedDict",
    "WeeksResponse",
    "WeeksResponseTypedDict",
    "WinProbabilityResponse",
    "WinProbabilityResponseTypedDict",
    "YardsToGoEnum",
    "YardsToGoType",
    "Zone",
    "ZoneTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "DesignationEnum": ".enums.combineenums",
    "CollegeClassEnum": ".enums.combineenums",
    "BenchPress": ".combineevents",
    "BroadJump": ".combineevents",
    "FortyYardDash": ".combineevents",
    "TenYardSplit": ".combineevents",
    "ThreeConeDrill": ".combineevents",
    "TwentyYardShuffle": ".combineevents",
    "VerticalJump": ".combineevents",
    "BenchPressTypedDict": ".combineevents",
    "BroadJumpTypedDict": ".combineevents",
    "FortyYardDashTypedDict": ".combineevents",
    "TenYardSplitTypedDict": ".combineevents",
    "ThreeConeDrillTypedDict": ".combineevents",
    "TwentyYardShuffleTypedDict": ".combineevents",
    "VerticalJumpTypedDict": ".combineevents",
    "CombineProfile": ".combineprofile",
    "CombineProfileTypedDict": ".combineprofile",
    "CombinePerson": ".combineprofile",
    "CombinePersonTypedDict": ".combineprofile",
    "CombineProfilesResponse": ".combineprofilesresponse",
    "CombineProfilesResponseTypedDict": ".combineprofilesresponse",
    "GetCombineProfilesRequest": ".getcombineprofilesop",
    "GetCombineProfilesRequestTypedDict": ".getcombineprofilesop",
    "GetCombineRankingsRequest": ".requests.getcombinerankingsop",
    "GetCombineRankingsRequestTypedDict": ".requests.getcombinerankingsop",
    "GetWeekOfDateRequest": ".requests.get_week_of_date_op",
    "GetWeekOfDateRequestTypedDict": ".requests.get_week_of_date_op",
    "EventFilterEnum": ".enums.combineenums",
    "CombineRankingsResponse": ".responses.combinerankingsresponse",
    "CombineRankingsResponseTypedDict": ".responses.combinerankingsresponse",
    "Award": ".award",
    "AwardType": ".award",
    "AwardTypedDict": ".award",
    "BinaryFlagEnum": ".binaryflagenum",
    "BoxscoreResponse": ".boxscoreresponse",
    "BoxscoreResponseTypedDict": ".boxscoreresponse",
    "Away": ".boxscoreresponse_2",
    "AwayTypedDict": ".boxscoreresponse_2",
    "BoxScoreResponse2": ".boxscoreresponse_2",
    "BoxScoreResponse2TypedDict": ".boxscoreresponse_2",
    "Home": ".boxscoreresponse_2",
    "HomeTypedDict": ".boxscoreresponse_2",
    "PlayerStats": ".boxscoreresponse_2",
    "PlayerStatsTypedDict": ".boxscoreresponse_2",
    "TeamStats": ".boxscoreresponse_2",
    "TeamStatsTypedDict": ".boxscoreresponse_2",
    "BoxscoreSchedule": ".boxscoreschedule",
    "BoxscoreScheduleTypedDict": ".boxscoreschedule",
    "BoxscoreScore": ".boxscorescore",
    "BoxscoreScoreTypedDict": ".boxscorescore",
    "BoxscoreSite": ".boxscoresite",
    "BoxscoreSiteRoofType": ".boxscoresite",
    "BoxscoreSiteTypedDict": ".boxscoresite",
    "BoxscoreTeam": ".boxscoreteam",
    "BoxscoreTeamTypedDict": ".boxscoreteam",
    "BroadcastInfo": ".broadcastinfo",
    "BroadcastInfoTypedDict": ".broadcastinfo",
    "InternationalWatchOption": ".broadcastinfo",
    "InternationalWatchOptionTypedDict": ".broadcastinfo",
    "StreamingNetwork": ".broadcastinfo",
    "StreamingNetworkTypedDict": ".broadcastinfo",
    "Territory": ".broadcastinfo",
    "CareerStats": ".careerstats",
    "CareerStatsTypedDict": ".careerstats",
    "Clinched": ".clinched",
    "ClinchedTypedDict": ".clinched",
    "CoachesFilmResponse": ".coachesfilmresponse",
    "CoachesFilmResponseTypedDict": ".coachesfilmresponse",
    "Background": ".coachesfilmvideo",
    "BackgroundTypedDict": ".coachesfilmvideo",
    "CameraSource": ".coachesfilmvideo",
    "CoachesFilmVideo": ".coachesfilmvideo",
    "CoachesFilmVideoType": ".coachesfilmvideo",
    "CoachesFilmVideoTypedDict": ".coachesfilmvideo",
    "Cta": ".coachesfilmvideo",
    "CtaTypedDict": ".coachesfilmvideo",
    "Image": ".coachesfilmvideo",
    "ImageTypedDict": ".coachesfilmvideo",
    "PromoAsset": ".coachesfilmvideo",
    "PromoAssetTypedDict": ".coachesfilmvideo",
    "SubType": ".coachesfilmvideo",
    "Video": ".coachesfilmvideo",
    "VideoTypedDict": ".coachesfilmvideo",
    "Conference": ".conference",
    "ConferenceTypedDict": ".conference",
    "ConferenceEnum": ".conferenceenum",
    "ContractInfo": ".contractinfo",
    "ContractInfoTypedDict": ".contractinfo",
    "CurrentGame": ".currentgame",
    "CurrentGameCategory": ".currentgame",
    "CurrentGameExtension": ".currentgame",
    "CurrentGameExtensionTypedDict": ".currentgame",
    "CurrentGameTypedDict": ".currentgame",
    "CurrentGamesResponse": ".currentgamesresponse",
    "CurrentGamesResponseTypedDict": ".currentgamesresponse",
    "DefensiveOverviewStatsResponse": ".defensiveoverviewstatsresponse",
    "DefensiveOverviewStatsResponseTypedDict": ".defensiveoverviewstatsresponse",
    "DefensivePassRushStats": ".defensivepassrushstats",
    "DefensivePassRushStatsNgsPosition": ".defensivepassrushstats",
    "DefensivePassRushStatsPosition": ".defensivepassrushstats",
    "DefensivePassRushStatsTypedDict": ".defensivepassrushstats",
    "DefensivePlayerOverviewStats": ".defensiveplayeroverviewstats",
    "DefensivePlayerOverviewStatsNgsPosition": ".defensiveplayeroverviewstats",
    "DefensivePlayerOverviewStatsPosition": ".defensiveplayeroverviewstats",
    "DefensivePlayerOverviewStatsTypedDict": ".defensiveplayeroverviewstats",
    "DefensivePlayerStats": ".defensiveplayerstats",
    "DefensivePlayerStatsNgsPosition": ".defensiveplayerstats",
    "DefensivePlayerStatsPosition": ".defensiveplayerstats",
    "DefensivePlayerStatsTypedDict": ".defensiveplayerstats",
    "DefensivePositionGroupEnum": ".defensivepositiongroupenum",
    "DefensiveNearestDefenderStats": ".defensivenearestdefenderstats",
    "DefenseNGSSplitEnum": ".enums.defensive_splits_enum",
    "DefensePositionEnum": ".enums.positionenums",
    "DefensePositionGroupEnum": ".enums.positionenums",
    "DefenseNGSPositionEnum": ".enums.positionenums",
    "DefenseNGSPositionGroupEnum": ".enums.positionenums",
    "DefensiveStats": ".defensivestats",
    "DefensiveStatsTypedDict": ".defensivestats",
    "DefensiveStatsResponse": ".defensivestatsresponse",
    "DefensiveStatsResponseTypedDict": ".defensivestatsresponse",
    "Division": ".division",
    "DivisionTypedDict": ".division",
    "DownEnum": ".enums.downenum",
    "DraftPick": ".draftpick",
    "DraftPickTypedDict": ".draftpick",
    "DraftResponse": ".draftresponse",
    "DraftResponseTypedDict": ".draftresponse",
    "Round": ".draftresponse",
    "RoundTypedDict": ".draftresponse",
    "Drive": ".drive",
    "DriveTypedDict": ".drive",
    "Result": ".drive",
    "ExperienceGamesResponse": ".experiencegamesresponse",
    "ExperienceGamesResponseTypedDict": ".experiencegamesresponse",
    "ExperienceTeamsResponse": ".experienceteamsresponse",
    "ExperienceTeamsResponseTypedDict": ".experienceteamsresponse",
    "ExternalID": ".externalid",
    "ExternalIDTypedDict": ".externalid",
    "FantasyPlayerStats": ".fantasyplayerstats",
    "FantasyPlayerStatsPosition": ".fantasyplayerstats",
    "FantasyPlayerStatsTypedDict": ".fantasyplayerstats",
    "PositionGroup": ".fantasyplayerstats",
    "FantasyStatsResponse": ".fantasystatsresponse",
    "FantasyStatsResponseTypedDict": ".fantasystatsresponse",
    "FilmCard": ".filmcard",
    "FilmCardTypedDict": ".filmcard",
    "LinkParams": ".filmcard",
    "LinkParamsTypedDict": ".filmcard",
    "FilmroomPlay": ".filmroomplay",
    "FilmroomPlayTypedDict": ".filmroomplay",
    "FilmroomPlaysResponse": ".filmroomplaysresponse",
    "FilmroomPlaysResponseTypedDict": ".filmroomplaysresponse",
    "FootballGamesResponse": ".footballgamesresponse",
    "FootballGamesResponseTypedDict": ".footballgamesresponse",
    "Fixture": ".futuresmarket",
    "FixtureTypedDict": ".futuresmarket",
    "FuturesMarket": ".futuresmarket",
    "FuturesMarketTypedDict": ".futuresmarket",
    "FuturesOddsResponse": ".futuresoddsresponse",
    "FuturesOddsResponseData": ".futuresoddsresponse",
    "FuturesOddsResponseDataTypedDict": ".futuresoddsresponse",
    "FuturesOddsResponseTypedDict": ".futuresoddsresponse",
    "Game": ".game",
    "GameCategory": ".game",
    "GameExtension": ".game",
    "GameExtensionTypedDict": ".game",
    "GameStatus": ".game",
    "GameTypedDict": ".game",
    "GamecenterResponse": ".gamecenterresponse",
    "GamecenterResponseTypedDict": ".gamecenterresponse",
    "Leaders": ".gamecenterresponse",
    "LeadersTypedDict": ".gamecenterresponse",
    "LeagueAverageReceiverSeparation": ".gamecenterresponse",
    "LeagueAverageReceiverSeparationTypedDict": ".gamecenterresponse",
    "LeagueAverageSeparationToQb": ".gamecenterresponse",
    "LeagueAverageSeparationToQbTypedDict": ".gamecenterresponse",
    "PassDistanceLeaders": ".gamecenterresponse",
    "PassDistanceLeadersTypedDict": ".gamecenterresponse",
    "PassRushers": ".gamecenterresponse",
    "PassRushersTypedDict": ".gamecenterresponse",
    "Passers": ".gamecenterresponse",
    "PassersTypedDict": ".gamecenterresponse",
    "Receivers": ".gamecenterresponse",
    "ReceiversTypedDict": ".gamecenterresponse",
    "Rushers": ".gamecenterresponse",
    "RushersTypedDict": ".gamecenterresponse",
    "SpeedLeaders": ".gamecenterresponse",
    "SpeedLeadersTypedDict": ".gamecenterresponse",
    "TimeToSackLeaders": ".gamecenterresponse",
    "TimeToSackLeadersTypedDict": ".gamecenterresponse",
    "GamecenterSchedule": ".gamecenterschedule",
    "GamecenterScheduleTypedDict": ".gamecenterschedule",
    "GameDetail": ".gamedetail",
    "GameDetailTypedDict": ".gamedetail",
    "Content": ".gameinsight",
    "ContentTypedDict": ".gameinsight",
    "GameInsight": ".gameinsight",
    "GameInsightTypedDict": ".gameinsight",
    "GameLocationEnum": ".enums.gamelocationenum",
    "GameOdds": ".gameodds",
    "GameOddsTypedDict": ".gameodds",
    "GamePreviewResponse": ".gamepreviewresponse",
    "GamePreviewResponseTypedDict": ".gamepreviewresponse",
    "Preview": ".gamepreviewresponse",
    "PreviewTypedDict": ".gamepreviewresponse",
    "GameResultEnum": ".gameresultenum",
    "GameSchedule": ".gameschedule",
    "GameScheduleTypedDict": ".gameschedule",
    "GameScore": ".gamescore",
    "GameScoreTypedDict": ".gamescore",
    "Phase": ".gamescore",
    "GameSite": ".gamesite",
    "GameSiteRoofType": ".gamesite",
    "GameSiteTypedDict": ".gamesite",
    "GamesResponse": ".gamesresponse",
    "GamesResponseTypedDict": ".gamesresponse",
    "GameStatsResponse": ".gamestatsresponse",
    "GameStatsResponseData": ".gamestatsresponse",
    "GameStatsResponseDataTypedDict": ".gamestatsresponse",
    "GameStatsResponseTypedDict": ".gamestatsresponse",
    "GameStatusEnum": ".gamestatusenum",
    "GameTeam": ".gameteam",
    "GameTeamTypedDict": ".gameteam",
    "Score": ".gameteam",
    "ScoreTypedDict": ".gameteam",
    "GetCoachesFilmVideosRequest": ".getcoachesfilmvideosop",
    "GetCoachesFilmVideosRequestTypedDict": ".getcoachesfilmvideosop",
    "GetDefensiveOverviewStatsBySeasonRequest": ".getdefensiveoverviewstatsbyseasonop",
    "GetDefensiveOverviewStatsBySeasonRequestTypedDict": ".getdefensiveoverviewstatsbyseasonop",
    "GetDefensiveOverviewStatsBySeasonSortKey": ".getdefensiveoverviewstatsbyseasonop",
    "GetDefensiveOverviewStatsByWeekRequest": ".getdefensiveoverviewstatsbyweekop",
    "GetDefensiveOverviewStatsByWeekRequestTypedDict": ".getdefensiveoverviewstatsbyweekop",
    "GetDefensiveOverviewStatsByWeekSortKey": ".getdefensiveoverviewstatsbyweekop",
    "GetDefensivePassRushStatsByWeekRequest": ".getdefensivepassrushstatsbyweekop",
    "GetDefensivePassRushStatsByWeekRequestTypedDict": ".getdefensivepassrushstatsbyweekop",
    "GetDefensivePassRushStatsByWeekSortKey": ".getdefensivepassrushstatsbyweekop",
    "GetDefensivePassRushStatsBySeasonRequest": ".getdefensivepassrushstatsbyseasonop",
    "GetDefensivePassRushStatsBySeasonRequestTypedDict": ".getdefensivepassrushstatsbyseasonop",
    "GetDefensivePassRushStatsBySeasonSortKey": ".getdefensivepassrushstatsbyseasonop",
    "GetDefensiveNearestDefenderStatsBySeasonRequest": ".getdefensivenearestdefenderstatsbyseasonop",
    "GetDefensiveNearestDefenderStatsBySeasonRequestTypedDict": ".getdefensivenearestdefenderstatsbyseasonop",
    "GetDefensiveNearestDefenderStatsBySeasonSortKey": ".getdefensivenearestdefenderstatsbyseasonop",
    "GetDefensiveNearestDefenderStatsByWeekRequest": ".getdefensivenearestdefenderstatsbyweekop",
    "GetDefensiveNearestDefenderStatsByWeekRequestTypedDict": ".getdefensivenearestdefenderstatsbyweekop",
    "GetDefensiveNearestDefenderStatsByWeekSortKey": ".getdefensivenearestdefenderstatsbyweekop",
    "GetDefensiveStatsBySeasonRequest": ".getdefensivestatsbyseasonop",
    "GetDefensiveStatsBySeasonRequestTypedDict": ".getdefensivestatsbyseasonop",
    "GetDefensiveStatsBySeasonSortKey": ".getdefensivestatsbyseasonop",
    "GetDraftInfoRequest": ".getdraftinfoop",
    "GetDraftInfoRequestTypedDict": ".getdraftinfoop",
    "GetDraftPicksReportRequest": ".getdraftpicksreportop",
    "GetDraftPicksReportRequestTypedDict": ".getdraftpicksreportop",
    "GetExperienceGamesRequest": ".getexperiencegamesop",
    "GetExperienceGamesRequestTypedDict": ".getexperiencegamesop",
    "GetExperienceTeamsRequest": ".getexperienceteamsop",
    "GetExperienceTeamsRequestTypedDict": ".getexperienceteamsop",
    "GetFantasyStatsBySeasonPositionGroup": ".getfantasystatsbyseasonop",
    "GetFantasyStatsBySeasonRequest": ".getfantasystatsbyseasonop",
    "GetFantasyStatsBySeasonRequestTypedDict": ".getfantasystatsbyseasonop",
    "GetFantasyStatsBySeasonSortKey": ".getfantasystatsbyseasonop",
    "AirYardType": ".getfilmroomplaysop",
    "DefCoverageType": ".getfilmroomplaysop",
    "DefendersInTheBoxType": ".getfilmroomplaysop",
    "DropbackTimeType": ".getfilmroomplaysop",
    "GetFilmroomPlaysRequest": ".getfilmroomplaysop",
    "GetFilmroomPlaysRequestTypedDict": ".getfilmroomplaysop",
    "Personnel": ".getfilmroomplaysop",
    "QbAlignment": ".getfilmroomplaysop",
    "ReceiverAlignment": ".getfilmroomplaysop",
    "RushDirection": ".getfilmroomplaysop",
    "SeparationType": ".getfilmroomplaysop",
    "TargetLocation": ".getfilmroomplaysop",
    "YardsToGoType": ".getfilmroomplaysop",
    "GetFootballBoxScoreRequest": ".getfootballboxscoreop",
    "GetFootballBoxScoreRequestTypedDict": ".getfootballboxscoreop",
    "GetFootballGamesRequest": ".getfootballgamesop",
    "GetFootballGamesRequestTypedDict": ".getfootballgamesop",
    "GetGamecenterRequest": ".getgamecenterop",
    "GetGamecenterRequestTypedDict": ".getgamecenterop",
    "GetGameInsightsRequest": ".getgameinsightsop",
    "GetGameInsightsRequestTypedDict": ".getgameinsightsop",
    "GetGameMatchupRankingsRequest": ".getgamematchuprankingsop",
    "GetGameMatchupRankingsRequestTypedDict": ".getgamematchuprankingsop",
    "GetGamePreviewRequest": ".getgamepreviewop",
    "GetGamePreviewRequestTypedDict": ".getgamepreviewop",
    "GetGameTeamRankingsRequest": ".getgameteamrankingsop",
    "GetGameTeamRankingsRequestTypedDict": ".getgameteamrankingsop",
    "GetInjuryReportsRequest": ".getinjuryreportsop",
    "GetInjuryReportsRequestTypedDict": ".getinjuryreportsop",
    "GetLiveGameScoresRequest": ".getlivegamescoresop",
    "GetLiveGameScoresRequestTypedDict": ".getlivegamescoresop",
    "GetLiveGameStatsRequest": ".getlivegamestatsop",
    "GetLiveGameStatsRequestTypedDict": ".getlivegamestatsop",
    "GetMultipleRankingsAllTeamsRequest": ".getmultiplerankingsallteamsop",
    "GetMultipleRankingsAllTeamsRequestTypedDict": ".getmultiplerankingsallteamsop",
    "GetPlayByPlayRequest": ".getplaybyplayop",
    "GetPlayListRequest": ".getplaylist",
    "GetPlayListRequestTypedDict": ".getplaylist",
    "GetPlayByPlayRequestTypedDict": ".getplaybyplayop",
    "GetPlayerDetailsRequest": ".getplayerdetailsop",
    "GetPlayerDetailsRequestTypedDict": ".getplayerdetailsop",
    "GetPlayerRequest": ".getplayerop",
    "GetPlayerRequestTypedDict": ".getplayerop",
    "GetPlayerPassingStatsBySeasonRequest": ".getplayerpassingstatsbyseasonop",
    "GetPlayerPassingStatsBySeasonRequestTypedDict": ".getplayerpassingstatsbyseasonop",
    "GetPlayerPassingStatsByWeekRequest": ".getplayerpassingstatsbyweekop",
    "GetPlayerPassingStatsByWeekRequestTypedDict": ".getplayerpassingstatsbyweekop",
    "GetPlayerReceivingStatsBySeasonRequest": ".getplayerreceivingstatsbyseasonop",
    "GetPlayerReceivingStatsBySeasonRequestTypedDict": ".getplayerreceivingstatsbyseasonop",
    "GetPlayerReceivingStatsByWeekRequest": ".getplayerreceivingstatsbyweekop",
    "GetPlayerReceivingStatsByWeekRequestTypedDict": ".getplayerreceivingstatsbyweekop",
    "GetPlayerRushingStatsBySeasonRequest": ".getplayerrushingstatsbyseasonop",
    "GetPlayerRushingStatsBySeasonRequestTypedDict": ".getplayerrushingstatsbyseasonop",
    "GetPlayerRushingStatsBySeasonSortKey": ".getplayerrushingstatsbyseasonop",
    "GetPlayerRushingStatsByWeekRequest": ".getplayerrushingstatsbyweekop",
    "GetPlayerRushingStatsByWeekRequestTypedDict": ".getplayerrushingstatsbyweekop",
    "GetPlayerRushingStatsByWeekSortKey": ".getplayerrushingstatsbyweekop",
    "GetPlayersTeamRosterRequest": ".getplayersteamrosterop",
    "GetPlayersTeamRosterRequestTypedDict": ".getplayersteamrosterop",
    "GameID": ".getplayswinprobabilityop",
    "GameIDTypedDict": ".getplayswinprobabilityop",
    "GetPlaysWinProbabilityRequest": ".getplayswinprobabilityop",
    "GetPlaysWinProbabilityRequestTypedDict": ".getplayswinprobabilityop",
    "GetPlaysWinProbabilityResponse": ".getplayswinprobabilityop",
    "GetPlaysWinProbabilityResponseTypedDict": ".getplayswinprobabilityop",
    "GetProjectedStatsRequest": ".getprojectedstatsop",
    "GetProjectedStatsRequestTypedDict": ".getprojectedstatsop",
    "GetScheduledGameRequest": ".getscheduledgameop",
    "GetScheduledGameRequestTypedDict": ".getscheduledgameop",
    "GetScheduledGamesRequest": ".getscheduledgamesop",
    "GetScheduledGamesRequestTypedDict": ".getscheduledgamesop",
    "GetScheduleSeasonWeeksRequest": ".getscheduleseasonweeksop",
    "GetScheduleSeasonWeeksRequestTypedDict": ".getscheduleseasonweeksop",
    "GetSeasonContentInsightsRequest": ".getseasoncontentinsightsop",
    "GetSeasonContentInsightsRequestTypedDict": ".getseasoncontentinsightsop",
    "Tag": ".getseasoncontentinsightsop",
    "GetSeasonPlayerStatsPosition": ".getseasonplayerstatsop",
    "GetSeasonPlayerStatsRequest": ".getseasonplayerstatsop",
    "GetSeasonPlayerStatsRequestTypedDict": ".getseasonplayerstatsop",
    "StatCategory": ".getseasonplayerstatsop",
    "GetSeasonWeeksRequest": ".getseasonweeksop",
    "GetSeasonWeeksRequestTypedDict": ".getseasonweeksop",
    "GetStandingsRequest": ".getstandingsop",
    "GetStandingsRequestTypedDict": ".getstandingsop",
    "GetStatsBoxscoreRequest": ".getstatsboxscoreop",
    "GetStatsBoxscoreRequestTypedDict": ".getstatsboxscoreop",
    "GetSummaryPlayRequest": ".getsummaryplayop",
    "GetSummaryPlayRequestTypedDict": ".getsummaryplayop",
    "GetTeamDefensePassStatsBySeasonRequest": ".getteamdefensepassstatsbyseasonop",
    "GetTeamDefensePassStatsBySeasonRequestTypedDict": ".getteamdefensepassstatsbyseasonop",
    "GetTeamDefensePassStatsBySeasonSortKey": ".getteamdefensepassstatsbyseasonop",
    "GetTeamDefenseRushStatsBySeasonRequest": ".getteamdefenserushstatsbyseasonop",
    "GetTeamDefenseRushStatsBySeasonRequestTypedDict": ".getteamdefenserushstatsbyseasonop",
    "GetTeamDefenseRushStatsBySeasonSortKey": ".getteamdefenserushstatsbyseasonop",
    "GetTeamDefenseStatsBySeasonRequest": ".getteamdefensestatsbyseasonop",
    "GetTeamDefenseStatsBySeasonRequestTypedDict": ".getteamdefensestatsbyseasonop",
    "GetTeamDefenseStatsBySeasonSortKey": ".getteamdefensestatsbyseasonop",
    "GetTeamDefenseStatsBySeasonSplit": ".getteamdefensestatsbyseasonop",
    "GetTeamDefensePassStatsByWeekRequest": ".getteamdefensepassstatsbyweekop",
    "GetTeamDefensePassStatsByWeekRequestTypedDict": ".getteamdefensepassstatsbyweekop",
    "GetTeamDefensePassStatsByWeekSortKey": ".getteamdefensepassstatsbyweekop",
    "GetTeamDefenseRushStatsByWeekRequest": ".getteamdefenserushstatsbyweekop",
    "GetTeamDefenseRushStatsByWeekRequestTypedDict": ".getteamdefenserushstatsbyweekop",
    "GetTeamDefenseRushStatsByWeekSortKey": ".getteamdefenserushstatsbyweekop",
    "GetTeamDefenseStatsByWeekRequest": ".getteamdefensestatsbyweekop",
    "GetTeamDefenseStatsByWeekRequestTypedDict": ".getteamdefensestatsbyweekop",
    "GetTeamDefenseStatsByWeekSortKey": ".getteamdefensestatsbyweekop",
    "GetTeamDefenseStatsByWeekSplit": ".getteamdefensestatsbyweekop",
    "GetTeamInjuriesRequest": ".getteaminjuriesop",
    "GetTeamInjuriesRequestTypedDict": ".getteaminjuriesop",
    "GetTeamOffenseStatsBySeasonRequest": ".getteamoffenseoverviewstatsbyseasonop",
    "GetTeamOffenseStatsBySeasonRequestTypedDict": ".getteamoffenseoverviewstatsbyseasonop",
    "GetTeamOffenseStatsBySeasonSortKey": ".getteamoffenseoverviewstatsbyseasonop",
    "GetTeamOffenseStatsBySeasonSplit": ".getteamoffenseoverviewstatsbyseasonop",
    "GetTeamOffenseStatsByWeekRequest": ".getteamoffenseoverviewstatsbyweekop",
    "GetTeamOffenseStatsByWeekRequestTypedDict": ".getteamoffenseoverviewstatsbyweekop",
    "GetTeamOffenseStatsByWeekSortKey": ".getteamoffenseoverviewstatsbyweekop",
    "GetTeamOffenseStatsByWeekSplit": ".getteamoffenseoverviewstatsbyweekop",
    "GetTeamOffensePassStatsBySeasonRequest": ".getteamoffensepassstatsbyseasonop",
    "GetTeamOffensePassStatsBySeasonRequestTypedDict": ".getteamoffensepassstatsbyseasonop",
    "GetTeamOffensePassStatsBySeasonSortKey": ".getteamoffensepassstatsbyseasonop",
    "GetTeamOffensePassStatsByWeekRequest": ".getteamoffensepassstatsbyweekop",
    "GetTeamOffensePassStatsByWeekRequestTypedDict": ".getteamoffensepassstatsbyweekop",
    "GetTeamOffensePassStatsByWeekSortKey": ".getteamoffensepassstatsbyweekop",
    "GetTeamOffenseRushStatsBySeasonRequest": ".getteamoffenserushstatsbyseasonop",
    "GetTeamOffenseRushStatsBySeasonRequestTypedDict": ".getteamoffenserushstatsbyseasonop",
    "GetTeamOffenseRushStatsBySeasonSortKey": ".getteamoffenserushstatsbyseasonop",
    "GetTeamOffenseRushStatsByWeekRequest": ".getteamoffenserushstatsbyweekop",
    "GetTeamOffenseRushStatsByWeekRequestTypedDict": ".getteamoffenserushstatsbyweekop",
    "GetTeamOffenseRushStatsByWeekSortKey": ".getteamoffenserushstatsbyweekop",
    "GetTeamRosterRequest": ".getteamrosterop",
    "GetTeamRosterRequestTypedDict": ".getteamrosterop",
    "GetTeamScheduleRequest": ".getteamscheduleop",
    "GetTeamScheduleRequestTypedDict": ".getteamscheduleop",
    "GetTeamStandingsRequest": ".getteamstandingsop",
    "GetTeamStandingsRequestTypedDict": ".getteamstandingsop",
    "GetTeamNeedsRequest": ".getteamneedsop",
    "GetTeamNeedsRequestTypedDict": ".getteamneedsop",
    "GetTransactionsRequest": ".gettransactionsop",
    "GetTransactionsRequestTypedDict": ".gettransactionsop",
    "GetTransactionsTransactionType": ".gettransactionsop",
    "GetVenuesRequest": ".getvenuesop",
    "GetVenuesRequestTypedDict": ".getvenuesop",
    "GetWeeklyBettingOddsRequest": ".getweeklybettingoddsop",
    "GetWeeklyBettingOddsRequestTypedDict": ".getweeklybettingoddsop",
    "GetWeeklyGameDetailsRequest": ".getweeklygamedetailsop",
    "GetWeeklyGameDetailsRequestTypedDict": ".getweeklygamedetailsop",
    "GetWeeklyTeamRosterRequest": ".getweeklyteamrosterop",
    "GetWeeklyTeamRosterRequestTypedDict": ".getweeklyteamrosterop",
    "GetWinProbabilityMinRequest": ".getwinprobabilityminop",
    "GetWinProbabilityMinRequestTypedDict": ".getwinprobabilityminop",
    "HomeFilmCardsResponse": ".homefilmcardsresponse",
    "HomeFilmCardsResponseTypedDict": ".homefilmcardsresponse",
    "InjuryEntry": ".injuryentry",
    "InjuryEntryGameStatus": ".injuryentry",
    "InjuryEntryTypedDict": ".injuryentry",
    "PracticeStatus": ".injuryentry",
    "PracticeStatusTypedDict": ".injuryentry",
    "InjuryReportResponse": ".injuryreportresponse",
    "InjuryReportResponseTypedDict": ".injuryreportresponse",
    "Insight": ".insight",
    "InsightPosition": ".insight",
    "InsightTypedDict": ".insight",
    "SecondTeamType": ".insight",
    "KickingStats": ".kickingstats",
    "KickingStatsTypedDict": ".kickingstats",
    "AwayTeam": ".livegame",
    "AwayTeamTypedDict": ".livegame",
    "HomeTeam": ".livegame",
    "HomeTeamTypedDict": ".livegame",
    "LiveGame": ".livegame",
    "LiveGameStatus": ".livegame",
    "LiveGameTypedDict": ".livegame",
    "LiveScoresResponse": ".livescoresresponse",
    "LiveScoresResponseTypedDict": ".livescoresresponse",
    "MatchupRankingsResponse": ".matchuprankingsresponse",
    "MatchupRankingsResponseTypedDict": ".matchuprankingsresponse",
    "MeridiemEnum": ".meridiemenum",
    "MoneyLine": ".moneyline",
    "MoneyLineTypedDict": ".moneyline",
    "MultipleRankingsCategory": ".multiplerankingscategory",
    "MultipleRankingsCategoryPagination": ".multiplerankingscategory",
    "MultipleRankingsCategoryPaginationTypedDict": ".multiplerankingscategory",
    "MultipleRankingsCategoryTypedDict": ".multiplerankingscategory",
    "OddsSelection": ".oddsselection",
    "OddsSelectionTypedDict": ".oddsselection",
    "OffensivePlayerPositionEnum": ".offensiveplayerpositionenum",
    "OffensiveSkillPositionEnum": ".offensiveskillpositionenum",
    "OverallRecord": ".overallrecord",
    "OverallRecordPoints": ".overallrecord",
    "OverallRecordPointsTypedDict": ".overallrecord",
    "OverallRecordType": ".overallrecord",
    "OverallRecordTypedDict": ".overallrecord",
    "Streak": ".overallrecord",
    "StreakTypedDict": ".overallrecord",
    "Pagination": ".pagination",
    "PaginationTypedDict": ".pagination",
    "PasserStats": ".passerstats",
    "PasserStatsTypedDict": ".passerstats",
    "Zone": ".passerstats",
    "ZoneTypedDict": ".passerstats",
    "PassingStats": ".passingstats",
    "PassingStatsTypedDict": ".passingstats",
    "PassingStatsCategoryEnum": ".passingstatscategoryenum",
    "PassingStatsResponse": ".passingstatsresponse",
    "PassingStatsResponseTypedDict": ".passingstatsresponse",
    "PassRushStatsResponse": ".passrushstatsresponse",
    "PassRushStatsResponseTypedDict": ".passrushstatsresponse",
    "NearestDefenderStatsResponse": ".nearestdefenderstatsresponse",
    "NearestDefenderStatsResponseTypedDict": ".nearestdefenderstatsresponse",
    "Penalty": ".penalty",
    "PenaltyTypedDict": ".penalty",
    "Play": ".play",
    "PlayType": ".play",
    "PlayTypedDict": ".play",
    "PlayByPlayResponse": ".playbyplayresponse",
    "PlayByPlayResponseTypedDict": ".playbyplayresponse",
    "PlayDetail": ".playdetail",
    "PlayDetailTypedDict": ".playdetail",
    "PlayDirection": ".playdetail",
    "PlayState": ".playdetail",
    "Player": ".player",
    "PlayerTypedDict": ".player",
    "PlayerDetail": ".playerdetail",
    "PlayerDetailTypedDict": ".playerdetail",
    "PlayerGameStats": ".playergamestats",
    "PlayerGameStatsTypedDict": ".playergamestats",
    "PlayerPassingStats": ".playerpassingstats",
    "PlayerPassingStatsTypedDict": ".playerpassingstats",
    "PlayerProjection": ".playerprojection",
    "PlayerProjectionTypedDict": ".playerprojection",
    "Relationships": ".playerprojection",
    "RelationshipsTypePlayerWeekProjectedPoints": ".playerprojection",
    "RelationshipsTypePlayerWeekProjectedStats": ".playerprojection",
    "RelationshipsTypedDict": ".playerprojection",
    "TypePlayer": ".playerprojection",
    "WeekPoint": ".playerprojection",
    "WeekPointTypedDict": ".playerprojection",
    "WeekStat": ".playerprojection",
    "WeekStatTypedDict": ".playerprojection",
    "PlayerReceivingStats": ".playerreceivingstats",
    "PlayerReceivingStatsTypedDict": ".playerreceivingstats",
    "PlayerRushingStats": ".playerrushingstats",
    "PlayerRushingStatsTypedDict": ".playerrushingstats",
    "PlayerSearchResponse": ".playersearchresponse",
    "PlayerSearchResponseTypedDict": ".playersearchresponse",
    "PlayerSearchResult": ".playersearchresult",
    "PlayerSearchResultTypedDict": ".playersearchresult",
    "PlayerStatsResponse": ".playerstatsresponse",
    "PlayerStatsResponsePagination": ".playerstatsresponse",
    "PlayerStatsResponsePaginationTypedDict": ".playerstatsresponse",
    "PlayerStatsResponsePlayer": ".playerstatsresponse",
    "PlayerStatsResponsePlayerTypedDict": ".playerstatsresponse",
    "PlayerStatsResponseStats": ".playerstatsresponse",
    "PlayerStatsResponseStatsTypedDict": ".playerstatsresponse",
    "PlayerStatsResponseTypedDict": ".playerstatsresponse",
    "PlayerWeekProjectedPoints": ".playerweekprojectedpoints",
    "PlayerWeekProjectedPointsAttributes": ".playerweekprojectedpoints",
    "PlayerWeekProjectedPointsAttributesTypedDict": ".playerweekprojectedpoints",
    "PlayerWeekProjectedPointsType": ".playerweekprojectedpoints",
    "PlayerWeekProjectedPointsTypedDict": ".playerweekprojectedpoints",
    "PlayerWeekProjectedStats": ".playerweekprojectedstats",
    "PlayerWeekProjectedStatsAttributes": ".playerweekprojectedstats",
    "PlayerWeekProjectedStatsAttributesTypedDict": ".playerweekprojectedstats",
    "PlayerWeekProjectedStatsType": ".playerweekprojectedstats",
    "PlayerWeekProjectedStatsTypedDict": ".playerweekprojectedstats",
    "PlayParticipant": ".playparticipant",
    "PlayParticipantStats": ".playparticipant",
    "PlayParticipantStatsTypedDict": ".playparticipant",
    "PlayParticipantTypedDict": ".playparticipant",
    "Role": ".playparticipant",
    "PlayPlayer": ".playplayer",
    "PlayPlayerTypedDict": ".playplayer",
    "PlayStat": ".playstat",
    "PlayStatTypedDict": ".playstat",
    "PlaySummaryResponse": ".playsummaryresponse",
    "PlaySummaryResponseTypedDict": ".playsummaryresponse",
    "PlayTypeEnum": ".playtypeenum",
    "PlayWinProbability": ".playwinprobability",
    "PlayWinProbabilityTypedDict": ".playwinprobability",
    "PointSpread": ".pointspread",
    "PointSpreadTypedDict": ".pointspread",
    "PointsRecord": ".pointsrecord",
    "PointsRecordPoints": ".pointsrecord",
    "PointsRecordPointsTypedDict": ".pointsrecord",
    "PointsRecordTypedDict": ".pointsrecord",
    "PracticeStatusEnum": ".practicestatusenum",
    "QuarterEnum": ".enums.quarterenum",
    "ProGame": ".progame",
    "ProGameCategory": ".progame",
    "ProGameExtension": ".progame",
    "ProGameExtensionTypedDict": ".progame",
    "ProGameStatus": ".progame",
    "ProGameTypedDict": ".progame",
    "Included": ".projectedstatsresponse",
    "IncludedTypedDict": ".projectedstatsresponse",
    "Meta": ".projectedstatsresponse",
    "MetaTypedDict": ".projectedstatsresponse",
    "Page": ".projectedstatsresponse",
    "PageTypedDict": ".projectedstatsresponse",
    "ProjectedStatsResponse": ".projectedstatsresponse",
    "ProjectedStatsResponsePagination": ".projectedstatsresponse",
    "ProjectedStatsResponsePaginationTypedDict": ".projectedstatsresponse",
    "ProjectedStatsResponseTypedDict": ".projectedstatsresponse",
    "ProTeam": ".proteam",
    "ProTeamConferenceAbbr": ".proteam",
    "ProTeamTeamType": ".proteam",
    "ProTeamTypedDict": ".proteam",
    "ProWeek": ".proweek",
    "ProWeekTypedDict": ".proweek",
    "ProWeekWeekType": ".proweek",
    "ReceivingStats": ".receivingstats",
    "ReceivingStatsTypedDict": ".receivingstats",
    "ReceivingStatsCategoryEnum": ".receivingstatscategoryenum",
    "ReceivingStatsResponse": ".receivingstatsresponse",
    "ReceivingStatsResponseTypedDict": ".receivingstatsresponse",
    "Record": ".record",
    "RecordTypedDict": ".record",
    "RefreshTokenRequest": ".refreshtokenrequest",
    "RefreshTokenRequestNetworkType": ".refreshtokenrequest",
    "RefreshTokenRequestTypedDict": ".refreshtokenrequest",
    "ResponseMetadata": ".responsemetadata",
    "ResponseMetadataTypedDict": ".responsemetadata",
    "Roster": ".rosterresponse",
    "RosterResponse": ".rosterresponse",
    "RosterResponseTypedDict": ".rosterresponse",
    "RosterTypedDict": ".rosterresponse",
    "RushingStats": ".rushingstats",
    "RushingStatsTypedDict": ".rushingstats",
    "RushingStatsResponse": ".rushingstatsresponse",
    "RushingStatsResponseTypedDict": ".rushingstatsresponse",
    "ScheduledGame": ".scheduledgame",
    "ScheduledGameTypedDict": ".scheduledgame",
    "ScheduleTeam": ".scheduleteam",
    "ScheduleTeamTypedDict": ".scheduleteam",
    "ScoreType": ".scoringplay",
    "ScoringPlay": ".scoringplay",
    "ScoringPlayTypedDict": ".scoringplay",
    "SearchPlayersRequest": ".searchplayersop",
    "SearchPlayersRequestTypedDict": ".searchplayersop",
    "SeasonStats": ".seasonstats",
    "SeasonStatsTypedDict": ".seasonstats",
    "SeasonTypeEnum": ".seasontypeenum",
    "SeasonWeeksResponse": ".seasonweeksresponse",
    "SeasonWeeksResponseTypedDict": ".seasonweeksresponse",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Site": ".site",
    "SiteRoofType": ".site",
    "SiteTypedDict": ".site",
    "SocialMedia": ".socialmedia",
    "SocialMediaTypedDict": ".socialmedia",
    "SortOrderEnum": ".sortorderenum",
    "Standings": ".standings",
    "StandingsTeam": ".standings",
    "StandingsTeamTypedDict": ".standings",
    "StandingsTypedDict": ".standings",
    "StandingsRecord": ".standingsrecord",
    "StandingsRecordPoints": ".standingsrecord",
    "StandingsRecordPointsTypedDict": ".standingsrecord",
    "StandingsRecordTypedDict": ".standingsrecord",
    "StandingsResponse": ".standingsresponse",
    "StandingsResponseTypedDict": ".standingsresponse",
    "StandingsResponseWeek": ".standingsresponse",
    "StandingsResponseWeekTypedDict": ".standingsresponse",
    "Statistic": ".statisticranking",
    "StatisticRanking": ".statisticranking",
    "StatisticRankingTypedDict": ".statisticranking",
    "StatisticTypedDict": ".statisticranking",
    "Team": ".team",
    "TeamConferenceAbbr": ".team",
    "TeamTeamType": ".team",
    "TeamTypedDict": ".team",
    "TeamBoxscore": ".teamboxscore",
    "TeamBoxscoreTypedDict": ".teamboxscore",
    "TeamDefensePassStats": ".teamdefensepassstats",
    "TeamDefensePassStatsTypedDict": ".teamdefensepassstats",
    "TeamDefensePassStatsResponse": ".teamdefensepassstatsresponse",
    "TeamDefensePassStatsResponseTypedDict": ".teamdefensepassstatsresponse",
    "TeamDefenseRushStats": ".teamdefenserushstats",
    "TeamDefenseRushStatsTypedDict": ".teamdefenserushstats",
    "TeamDefenseRushStatsResponse": ".teamdefenserushstatsresponse",
    "TeamDefenseRushStatsResponseTypedDict": ".teamdefenserushstatsresponse",
    "TeamDefenseStats": ".teamdefensestats",
    "TeamDefenseStatsTypedDict": ".teamdefensestats",
    "TeamDefenseStatsResponse": ".teamdefensestatsresponse",
    "TeamDefenseStatsResponseTypedDict": ".teamdefensestatsresponse",
    "TeamGameStats": ".teamgamestats",
    "TeamGameStatsTypedDict": ".teamgamestats",
    "TeamInfo": ".teaminfo",
    "TeamInfoTypedDict": ".teaminfo",
    "TeamInjuryReport": ".teaminjuryreport",
    "TeamInjuryReportTypedDict": ".teaminjuryreport",
    "TeamMatchupRankings": ".teammatchuprankings",
    "TeamMatchupRankingsTypedDict": ".teammatchuprankings",
    "TeamNeedsResponse": ".teamneedsresponse",
    "TeamNeedsResponseTypedDict": ".teamneedsresponse",
    "TeamOffenseStats": ".teamoffenseoverviewstats",
    "TeamOffenseStatsTypedDict": ".teamoffenseoverviewstats",
    "TeamOffenseStatsResponse": ".teamoffenseoverviewstatsresponse",
    "TeamOffenseStatsResponseTypedDict": ".teamoffenseoverviewstatsresponse",
    "TeamOffensePassStats": ".teamoffensepassstats",
    "TeamOffensePassStatsTypedDict": ".teamoffensepassstats",
    "TeamOffensePassStatsResponse": ".teamoffensepassstatsresponse",
    "TeamOffensePassStatsResponseTypedDict": ".teamoffensepassstatsresponse",
    "TeamOffenseRushStats": ".teamoffenserushstats",
    "TeamOffenseRushStatsTypedDict": ".teamoffenserushstats",
    "TeamOffenseRushStatsResponse": ".teamoffenserushstatsresponse",
    "TeamOffenseRushStatsResponseTypedDict": ".teamoffenserushstatsresponse",
    "TeamRankingEntry": ".teamrankingentry",
    "TeamRankingEntryTypedDict": ".teamrankingentry",
    "TeamRankings": ".teamrankings",
    "TeamRankingsTypedDict": ".teamrankings",
    "TeamRankingsResponse": ".teamrankingsresponse",
    "TeamRankingsResponseTypedDict": ".teamrankingsresponse",
    "TeamRosterResponse": ".teamrosterresponse",
    "TeamRosterResponseTypedDict": ".teamrosterresponse",
    "TeamScore": ".teamscore",
    "TeamScoreTypedDict": ".teamscore",
    "TeamTypeEnum": ".teamtypeenum",
    "TeamVenue": ".teamvenue",
    "TeamVenueTypedDict": ".teamvenue",
    "TicketVendor": ".ticketvendor",
    "TicketVendorTypedDict": ".ticketvendor",
    "TokenRequest": ".tokenrequest",
    "TokenRequestNetworkType": ".tokenrequest",
    "TokenRequestTypedDict": ".tokenrequest",
    "TokenResponse": ".tokenresponse",
    "TokenResponseTypedDict": ".tokenresponse",
    "Totals": ".totals",
    "TotalsTypedDict": ".totals",
    "Transaction": ".transaction",
    "TransactionType": ".transaction",
    "TransactionTypedDict": ".transaction",
    "TransactionsResponse": ".transactionsresponse",
    "TransactionsResponseTypedDict": ".transactionsresponse",
    "Venue": ".venue",
    "VenueTypedDict": ".venue",
    "VenueInfo": ".venueinfo",
    "VenueInfoRoofType": ".venueinfo",
    "VenueInfoTypedDict": ".venueinfo",
    "VenuesResponse": ".venuesresponse",
    "VenuesResponseTypedDict": ".venuesresponse",
    "NFLPLUSPLUSNFLPLUSCOACHESFILM": ".videoauthorizations",
    "NFLPLUSPLUSNFLPLUSCOACHESFILMTypedDict": ".videoauthorizations",
    "NFLPLUSPremiumNFLPLUSCOACHESFILM": ".videoauthorizations",
    "NFLPLUSPremiumNFLPLUSCOACHESFILMTypedDict": ".videoauthorizations",
    "NflPlusPlus": ".videoauthorizations",
    "NflPlusPlusRequirements": ".videoauthorizations",
    "NflPlusPlusRequirementsTypedDict": ".videoauthorizations",
    "NflPlusPlusTypedDict": ".videoauthorizations",
    "NflPlusPremium": ".videoauthorizations",
    "NflPlusPremiumRequirements": ".videoauthorizations",
    "NflPlusPremiumRequirementsTypedDict": ".videoauthorizations",
    "NflPlusPremiumTypedDict": ".videoauthorizations",
    "ProPremium": ".videoauthorizations",
    "ProPremiumNFLPLUSCOACHESFILM": ".videoauthorizations",
    "ProPremiumNFLPLUSCOACHESFILMTypedDict": ".videoauthorizations",
    "ProPremiumRequirements": ".videoauthorizations",
    "ProPremiumRequirementsTypedDict": ".videoauthorizations",
    "ProPremiumTypedDict": ".videoauthorizations",
    "VideoAuthorizations": ".videoauthorizations",
    "VideoAuthorizationsTypedDict": ".videoauthorizations",
    "VideoGamePlayIds": ".videogameplayids",
    "VideoGamePlayIdsTypedDict": ".videogameplayids",
    "VideoTag": ".videotag",
    "VideoTagTypedDict": ".videotag",
    "VideoThumbnail": ".videothumbnail",
    "VideoThumbnailTypedDict": ".videothumbnail",
    "Week": ".week",
    "WeekTypedDict": ".week",
    "WeekWeekType": ".week",
    "DriveChart": ".weeklygamedetail",
    "DriveChartTypedDict": ".weeklygamedetail",
    "Replay": ".weeklygamedetail",
    "ReplayTypedDict": ".weeklygamedetail",
    "Summary": ".weeklygamedetail",
    "SummaryTypedDict": ".weeklygamedetail",
    "TaggedVideos": ".weeklygamedetail",
    "TaggedVideosTypedDict": ".weeklygamedetail",
    "WeeklyGameDetail": ".weeklygamedetail",
    "WeeklyGameDetailCategory": ".weeklygamedetail",
    "WeeklyGameDetailExtension": ".weeklygamedetail",
    "WeeklyGameDetailExtensionTypedDict": ".weeklygamedetail",
    "WeeklyGameDetailStatus": ".weeklygamedetail",
    "WeeklyGameDetailTypedDict": ".weeklygamedetail",
    "WeeklyOddsResponse": ".weeklyoddsresponse",
    "WeeklyOddsResponseTypedDict": ".weeklyoddsresponse",
    "WeeklyPassingStatsResponse": ".weeklypassingstatsresponse",
    "WeeklyPassingStatsResponseTypedDict": ".weeklypassingstatsresponse",
    "WeeklyPlayer": ".weeklyplayer",
    "WeeklyPlayerTypedDict": ".weeklyplayer",
    "WeeklyPlayerPassingStats": ".weeklyplayerpassingstats",
    "WeeklyPlayerPassingStatsTypedDict": ".weeklyplayerpassingstats",
    "WeeklyPlayerRushingStats": ".weeklyplayerrushingstats",
    "WeeklyPlayerRushingStatsTypedDict": ".weeklyplayerrushingstats",
    "WeeklyRosterResponse": ".weeklyrosterresponse",
    "WeeklyRosterResponseTypedDict": ".weeklyrosterresponse",
    "WeeklyRushingStatsResponse": ".weeklyrushingstatsresponse",
    "WeeklyRushingStatsResponseTypedDict": ".weeklyrushingstatsresponse",
    "WeekSlugEnum": ".weekslugenum",
    "WeeksResponse": ".weeksresponse",
    "WeeksResponseTypedDict": ".weeksresponse",
    "WinProbabilityResponse": ".winprobabilityresponse",
    "WinProbabilityResponseTypedDict": ".winprobabilityresponse",
    "YardsToGoEnum": ".enums.yardstogoenum",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
