# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from griddy.nfl.models.box_score_response_player_stats import (
    BoxScoreResponsePlayerStats,
)
from griddy.nfl.models.box_score_response_team_stats import (
    BoxScoreResponseTeamStats,
)
from griddy.nfl.models.game import Game
from griddy.nfl.models.scoring_play import ScoringPlay


class BoxScoreResponse(BaseModel):
    """
    BoxScoreResponse
    """  # noqa: E501

    game: Optional[Game] = None
    player_stats: Optional[BoxScoreResponsePlayerStats] = Field(
        default=None, alias="playerStats"
    )
    scoring_summary: Optional[List[ScoringPlay]] = Field(
        default=None, alias="scoringSummary"
    )
    team_stats: Optional[BoxScoreResponseTeamStats] = Field(
        default=None, alias="teamStats"
    )
    __properties: ClassVar[List[str]] = [
        "game",
        "playerStats",
        "scoringSummary",
        "teamStats",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BoxScoreResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict["game"] = self.game.to_dict()
        # override the default output from pydantic by calling `to_dict()` of player_stats
        if self.player_stats:
            _dict["playerStats"] = self.player_stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in scoring_summary (list)
        _items = []
        if self.scoring_summary:
            for _item_scoring_summary in self.scoring_summary:
                if _item_scoring_summary:
                    _items.append(_item_scoring_summary.to_dict())
            _dict["scoringSummary"] = _items
        # override the default output from pydantic by calling `to_dict()` of team_stats
        if self.team_stats:
            _dict["teamStats"] = self.team_stats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BoxScoreResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "game": (
                    Game.from_dict(obj["game"]) if obj.get("game") is not None else None
                ),
                "playerStats": (
                    BoxScoreResponsePlayerStats.from_dict(obj["playerStats"])
                    if obj.get("playerStats") is not None
                    else None
                ),
                "scoringSummary": (
                    [ScoringPlay.from_dict(_item) for _item in obj["scoringSummary"]]
                    if obj.get("scoringSummary") is not None
                    else None
                ),
                "teamStats": (
                    BoxScoreResponseTeamStats.from_dict(obj["teamStats"])
                    if obj.get("teamStats") is not None
                    else None
                ),
            }
        )
        return _obj
