"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextgenstatspositionenum import NextGenStatsPositionEnum
from griddy.nfl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BoxScorePlayerFieldGoalsStatisticTypedDict(TypedDict):
    nfl_id: NotRequired[int]
    gsis_id: NotRequired[str]
    esb_id: NotRequired[str]
    jersey_number: NotRequired[int]
    player_name: NotRequired[str]
    short_name: NotRequired[str]
    team_id: NotRequired[str]
    headshot: NotRequired[str]
    r"""URL to player headshot image (contains formatInstructions placeholder)"""
    position: NotRequired[NextGenStatsPositionEnum]
    r"""Next Gen Stats player position"""
    attempts: NotRequired[int]
    success_cnt: NotRequired[int]
    blocked_cnt: NotRequired[int]
    yards: NotRequired[int]
    avg_yard: NotRequired[float]
    longest_made_field_goal: NotRequired[int]


class BoxScorePlayerFieldGoalsStatistic(BaseModel):
    nfl_id: Annotated[Optional[int], pydantic.Field(alias="nflId")] = None

    gsis_id: Annotated[Optional[str], pydantic.Field(alias="gsisId")] = None

    esb_id: Annotated[Optional[str], pydantic.Field(alias="esbId")] = None

    jersey_number: Annotated[Optional[int], pydantic.Field(alias="jerseyNumber")] = None

    player_name: Annotated[Optional[str], pydantic.Field(alias="playerName")] = None

    short_name: Annotated[Optional[str], pydantic.Field(alias="shortName")] = None

    team_id: Annotated[Optional[str], pydantic.Field(alias="teamId")] = None

    headshot: Optional[str] = None
    r"""URL to player headshot image (contains formatInstructions placeholder)"""

    position: Optional[NextGenStatsPositionEnum] = None
    r"""Next Gen Stats player position"""

    attempts: Optional[int] = None

    success_cnt: Annotated[Optional[int], pydantic.Field(alias="successCnt")] = None

    blocked_cnt: Annotated[Optional[int], pydantic.Field(alias="blockedCnt")] = None

    yards: Optional[int] = None

    avg_yard: Annotated[Optional[float], pydantic.Field(alias="avgYard")] = None

    longest_made_field_goal: Annotated[
        Optional[int], pydantic.Field(alias="longestMadeFieldGoal")
    ] = None
