"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CameraSourceEnum(str, Enum):
    r"""Location of the camera"""

    ENDZONE = "Endzone"
    SIDELINE = "Sideline"
    BROADCAST = "Broadcast"
