"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CoachesFileVideoSubTypeEnum(str, Enum):
    r"""Coaches film sub types"""

    COACHES_FILM = "Coaches Film"
    COACHES_FILM_PRO = "Coaches Film Pro"
