"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FantasyPositionGroupEnum(str, Enum):
    r"""Position group"""

    QB = "QB"
    RB = "RB"
    WR = "WR"
    TE = "TE"
    SPEC = "SPEC"
