"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .game import Game, GameTypedDict
from .pagination import Pagination, PaginationTypedDict
from griddy.nfl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FootballGamesResponseTypedDict(TypedDict):
    games: NotRequired[List[GameTypedDict]]
    pagination: NotRequired[PaginationTypedDict]


class FootballGamesResponse(BaseModel):
    games: Optional[List[Game]] = None

    pagination: Optional[Pagination] = None
