"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


GameResultEnum = Literal[
    "W",
    "L",
    "T",
]
r"""Game result (Win/Loss/Tie)"""
