"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from griddy_nfl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ContentTypedDict(TypedDict):
    r"""Insight content and analysis"""


class Content(BaseModel):
    r"""Insight content and analysis"""


class GameInsightTypedDict(TypedDict):
    r"""Game-specific analytical insight"""

    content: NotRequired[ContentTypedDict]
    r"""Insight content and analysis"""
    game_id: NotRequired[str]
    r"""Game identifier"""
    id: NotRequired[str]
    r"""Insight identifier"""
    type: NotRequired[str]
    r"""Type of insight"""


class GameInsight(BaseModel):
    r"""Game-specific analytical insight"""

    content: Optional[Content] = None
    r"""Insight content and analysis"""

    game_id: Annotated[Optional[str], pydantic.Field(alias="gameId")] = None
    r"""Game identifier"""

    id: Optional[str] = None
    r"""Insight identifier"""

    type: Optional[str] = None
    r"""Type of insight"""
