# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt
from typing_extensions import Self


class GameSummaryTeamScore(BaseModel):
    """
    GameSummaryTeamScore
    """  # noqa: E501

    q1: Optional[StrictInt] = None
    q2: Optional[StrictInt] = None
    q3: Optional[StrictInt] = None
    q4: Optional[StrictInt] = None
    ot: Optional[StrictInt] = None
    total: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["q1", "q2", "q3", "q4", "ot", "total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GameSummaryTeamScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if q1 (nullable) is None
        # and model_fields_set contains the field
        if self.q1 is None and "q1" in self.model_fields_set:
            _dict["q1"] = None

        # set to None if q2 (nullable) is None
        # and model_fields_set contains the field
        if self.q2 is None and "q2" in self.model_fields_set:
            _dict["q2"] = None

        # set to None if q3 (nullable) is None
        # and model_fields_set contains the field
        if self.q3 is None and "q3" in self.model_fields_set:
            _dict["q3"] = None

        # set to None if q4 (nullable) is None
        # and model_fields_set contains the field
        if self.q4 is None and "q4" in self.model_fields_set:
            _dict["q4"] = None

        # set to None if ot (nullable) is None
        # and model_fields_set contains the field
        if self.ot is None and "ot" in self.model_fields_set:
            _dict["ot"] = None

        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict["total"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GameSummaryTeamScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "q1": obj.get("q1"),
                "q2": obj.get("q2"),
                "q3": obj.get("q3"),
                "q4": obj.get("q4"),
                "ot": obj.get("ot"),
                "total": obj.get("total"),
            }
        )
        return _obj
