"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class GamePhaseEnum(str, Enum):
    r"""Current phase of the game"""

    PREGAME = "PREGAME"
    INGAME = "INGAME"
    HALFTIME = "HALFTIME"
    FINAL = "FINAL"
    SUSPENDED = "SUSPENDED"
