"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
from ..utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPlayersTeamRosterRequestTypedDict(TypedDict):
    team_id: str
    r"""Team identifier (UUID)"""
    season: int
    r"""Season year"""
    include_stats: NotRequired[bool]
    r"""Include current season statistics"""


class GetPlayersTeamRosterRequest(BaseModel):
    team_id: Annotated[
        str,
        pydantic.Field(alias="teamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Team identifier (UUID)"""

    season: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Season year"""

    include_stats: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeStats"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Include current season statistics"""
