"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .seasontypeenum import SeasonTypeEnum
from .sortorderenum import SortOrderEnum
from enum import Enum
from griddy.nfl.types import BaseModel
from griddy.nfl.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_TEAM_OFFENSE_PASS_STATS_BY_SEASON_OP_SERVERS = [
    # Production NFL Pro API
    "https://pro.nfl.com",
]


class GetTeamOffensePassStatsBySeasonQueryParamSortKey(str, Enum):
    r"""Field to sort by"""

    TOTAL = "total"
    PASS = "pass"
    PASS_PCT = "passPct"
    PASS_TD = "passTd"
    PASS_YDS = "passYds"
    PASS_YPP = "passYpp"
    EPA_PASS = "epaPass"
    EPA_PASS_PP = "epaPassPP"
    TTT = "ttt"
    QBP = "qbp"
    QBP_PCT = "qbpPct"
    ATT = "att"
    SACKED_YDS = "sackedYds"
    SACK = "sack"
    SACK_PCT = "sackPct"
    TTP = "ttp"
    BLITZ_PCT = "blitzPct"
    PA_PCT = "paPct"
    YAC = "yac"
    YACOE = "yacoe"
    SEP = "sep"
    PASS_YPG = "passYpg"
    SACKED_YPG = "sackedYpg"


class GetTeamOffensePassStatsBySeasonRequestTypedDict(TypedDict):
    season: int
    r"""Season year"""
    season_type: SeasonTypeEnum
    r"""Type of season"""
    limit: NotRequired[int]
    r"""Maximum number of teams to return"""
    offset: NotRequired[int]
    r"""Number of records to skip for pagination"""
    page: NotRequired[int]
    r"""Page number for pagination"""
    sort_key: NotRequired[GetTeamOffensePassStatsBySeasonQueryParamSortKey]
    r"""Field to sort by"""
    sort_value: NotRequired[SortOrderEnum]
    r"""Sort direction"""
    team_defense: NotRequired[str]
    r"""Filter by specific team ID"""


class GetTeamOffensePassStatsBySeasonRequest(BaseModel):
    season: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Season year"""

    season_type: Annotated[
        SeasonTypeEnum,
        pydantic.Field(alias="seasonType"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Type of season"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 35
    r"""Maximum number of teams to return"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of records to skip for pagination"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number for pagination"""

    sort_key: Annotated[
        Optional[GetTeamOffensePassStatsBySeasonQueryParamSortKey],
        pydantic.Field(alias="sortKey"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = GetTeamOffensePassStatsBySeasonQueryParamSortKey.PASS_YPG
    r"""Field to sort by"""

    sort_value: Annotated[
        Optional[SortOrderEnum],
        pydantic.Field(alias="sortValue"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort direction"""

    team_defense: Annotated[
        Optional[str],
        pydantic.Field(alias="teamDefense"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by specific team ID"""
