"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .seasontypeenum import SeasonTypeEnum
from .sortorderenum import SortOrderEnum
from enum import Enum
from griddy.nfl.types import BaseModel
from griddy.nfl.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_TEAM_OFFENSE_OVERVIEW_STATS_BY_SEASON_OP_SERVERS = [
    # Production NFL Pro API
    "https://pro.nfl.com",
]


class GetTeamOffenseOverviewStatsBySeasonQueryParamSortKey(str, Enum):
    r"""Field to sort by"""

    TOTAL = "total"
    PASS = "pass"
    RUN = "run"
    YDS = "yds"
    PASS_PCT = "passPct"
    YPP = "ypp"
    TD = "td"
    PASS_TD = "passTd"
    RUSH_TD = "rushTd"
    EPA = "epa"
    EPA_PP = "epaPP"
    PASS_YDS = "passYds"
    PASS_YPP = "passYpp"
    EPA_PASS = "epaPass"
    EPA_PASS_PP = "epaPassPP"
    RUSH_YDS = "rushYds"
    RUSH_YPP = "rushYpp"
    EPA_RUSH = "epaRush"
    EPA_RUSH_PP = "epaRushPP"
    TO = "to"
    PPG = "ppg"
    YPG = "ypg"
    PASS_YPG = "passYpg"
    RUSH_YPG = "rushYpg"
    RED_ZONE_PCT = "redZonePct"
    THIRD_DOWN_PCT = "thirdDownPct"


class QueryParamSplit(str, Enum):
    TEAM_SHOTGUN = "TEAM_SHOTGUN"
    TEAM_UNDER_CENTER = "TEAM_UNDER_CENTER"
    TEAM_PISTOL = "TEAM_PISTOL"
    TEAM_WHEN_LEADING = "TEAM_WHEN_LEADING"
    TEAM_WHEN_TRAILING = "TEAM_WHEN_TRAILING"
    TEAM_WHEN_TIED = "TEAM_WHEN_TIED"
    TEAM_RED_ZONE = "TEAM_RED_ZONE"
    TEAM_GOAL_TO_GO = "TEAM_GOAL_TO_GO"


class GetTeamOffenseOverviewStatsBySeasonRequestTypedDict(TypedDict):
    season: int
    r"""Season year"""
    season_type: SeasonTypeEnum
    r"""Type of season"""
    limit: NotRequired[int]
    r"""Maximum number of teams to return"""
    offset: NotRequired[int]
    r"""Number of records to skip for pagination"""
    page: NotRequired[int]
    r"""Page number for pagination"""
    sort_key: NotRequired[GetTeamOffenseOverviewStatsBySeasonQueryParamSortKey]
    r"""Field to sort by"""
    sort_value: NotRequired[SortOrderEnum]
    r"""Sort direction"""
    team_defense: NotRequired[str]
    r"""Filter by specific team identifier"""
    split: NotRequired[List[QueryParamSplit]]
    r"""Offensive situation splits to filter by (supports multiple values)"""


class GetTeamOffenseOverviewStatsBySeasonRequest(BaseModel):
    season: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Season year"""

    season_type: Annotated[
        SeasonTypeEnum,
        pydantic.Field(alias="seasonType"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Type of season"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 35
    r"""Maximum number of teams to return"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of records to skip for pagination"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number for pagination"""

    sort_key: Annotated[
        Optional[GetTeamOffenseOverviewStatsBySeasonQueryParamSortKey],
        pydantic.Field(alias="sortKey"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = GetTeamOffenseOverviewStatsBySeasonQueryParamSortKey.YPG
    r"""Field to sort by"""

    sort_value: Annotated[
        Optional[SortOrderEnum],
        pydantic.Field(alias="sortValue"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort direction"""

    team_defense: Annotated[
        Optional[str],
        pydantic.Field(alias="teamDefense"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by specific team identifier"""

    split: Annotated[
        Optional[List[QueryParamSplit]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Offensive situation splits to filter by (supports multiple values)"""
