"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
from ..utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class GetWinProbabilityMinRequestTypedDict(TypedDict):
    fapi_game_id: List[str]
    r"""Football API game identifiers (UUID format). Supports multiple game IDs
    to retrieve win probability data for multiple games simultaneously.

    """


class GetWinProbabilityMinRequest(BaseModel):
    fapi_game_id: Annotated[
        List[str],
        pydantic.Field(alias="fapiGameId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Football API game identifiers (UUID format). Supports multiple game IDs
    to retrieve win probability data for multiple games simultaneously.

    """
