"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class NextGenStatsPositionEnum(str, Enum):
    r"""Next Gen Stats player position"""

    C = "C"
    CB = "CB"
    DB = "DB"
    DE = "DE"
    DT = "DT"
    ED = "ED"
    FB = "FB"
    FS = "FS"
    G = "G"
    ILB = "ILB"
    K = "K"
    LB = "LB"
    LS = "LS"
    MLB = "MLB"
    NT = "NT"
    OL = "OL"
    OLB = "OLB"
    P = "P"
    QB = "QB"
    RB = "RB"
    S = "S"
    SCB = "SCB"
    SS = "SS"
    T = "T"
    TE = "TE"
    WR = "WR"
