# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NFLTeamInfo(BaseModel):
    """
    Basic team information included in roster responses
    """ # noqa: E501
    abbr: Optional[StrictStr] = None
    city_state: Optional[StrictStr] = Field(default=None, alias="cityState")
    conference: Optional[NFLNFLConference] = None
    conference_abbr: Optional[NFLNFLConferenceEnum] = Field(default=None, alias="conferenceAbbr")
    division: Optional[NFLNFLDivision] = None
    full_name: Optional[StrictStr] = Field(default=None, alias="fullName")
    logo: Optional[StrictStr] = None
    nick: Optional[StrictStr] = None
    season: Optional[StrictInt] = None
    smart_id: Optional[StrictStr] = Field(default=None, alias="smartId")
    stadium_name: Optional[StrictStr] = Field(default=None, alias="stadiumName")
    team_id: Optional[StrictStr] = Field(default=None, alias="teamId")
    team_site_ticket_url: Optional[StrictStr] = Field(default=None, alias="teamSiteTicketUrl")
    team_site_url: Optional[StrictStr] = Field(default=None, alias="teamSiteUrl")
    team_type: Optional[NFLNFLTeamTypeEnum] = Field(default=None, alias="teamType")
    ticket_phone_number: Optional[StrictStr] = Field(default=None, alias="ticketPhoneNumber")
    year_found: Optional[StrictInt] = Field(default=None, alias="yearFound")
    __properties: ClassVar[List[str]] = ["abbr", "cityState", "conference", "conferenceAbbr", "division", "fullName", "logo", "nick", "season", "smartId", "stadiumName", "teamId", "teamSiteTicketUrl", "teamSiteUrl", "teamType", "ticketPhoneNumber", "yearFound"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFLTeamInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conference
        if self.conference:
            _dict['conference'] = self.conference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of division
        if self.division:
            _dict['division'] = self.division.to_dict()
        # set to None if team_site_ticket_url (nullable) is None
        # and model_fields_set contains the field
        if self.team_site_ticket_url is None and "team_site_ticket_url" in self.model_fields_set:
            _dict['teamSiteTicketUrl'] = None

        # set to None if team_site_url (nullable) is None
        # and model_fields_set contains the field
        if self.team_site_url is None and "team_site_url" in self.model_fields_set:
            _dict['teamSiteUrl'] = None

        # set to None if ticket_phone_number (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_phone_number is None and "ticket_phone_number" in self.model_fields_set:
            _dict['ticketPhoneNumber'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFLTeamInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "abbr": obj.get("abbr"),
            "cityState": obj.get("cityState"),
            "conference": NFLNFLConference.from_dict(obj["conference"]) if obj.get("conference") is not None else None,
            "conferenceAbbr": obj.get("conferenceAbbr"),
            "division": NFLNFLDivision.from_dict(obj["division"]) if obj.get("division") is not None else None,
            "fullName": obj.get("fullName"),
            "logo": obj.get("logo"),
            "nick": obj.get("nick"),
            "season": obj.get("season"),
            "smartId": obj.get("smartId"),
            "stadiumName": obj.get("stadiumName"),
            "teamId": obj.get("teamId"),
            "teamSiteTicketUrl": obj.get("teamSiteTicketUrl"),
            "teamSiteUrl": obj.get("teamSiteUrl"),
            "teamType": obj.get("teamType"),
            "ticketPhoneNumber": obj.get("ticketPhoneNumber"),
            "yearFound": obj.get("yearFound")
        })
        return _obj


