# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NFLParticipantPlayerInfo(BaseModel):
    """
    NFLParticipantPlayerInfo
    """ # noqa: E501
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    gsis_id: Optional[StrictStr] = Field(default=None, description="GSIS player ID", alias="gsisId")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    nfl_id: Optional[StrictInt] = Field(default=None, description="NFL player ID", alias="nflId")
    player_name: Optional[StrictStr] = Field(default=None, description="Full player name", alias="playerName")
    position: Optional[StrictStr] = Field(default=None, description="Player position")
    position_group: Optional[StrictStr] = Field(default=None, description="Position group", alias="positionGroup")
    team_id: Optional[StrictStr] = Field(default=None, description="Team ID", alias="teamId")
    uniform_number: Optional[StrictStr] = Field(default=None, description="Jersey number", alias="uniformNumber")
    __properties: ClassVar[List[str]] = ["firstName", "gsisId", "lastName", "nflId", "playerName", "position", "positionGroup", "teamId", "uniformNumber"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFLParticipantPlayerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFLParticipantPlayerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "gsisId": obj.get("gsisId"),
            "lastName": obj.get("lastName"),
            "nflId": obj.get("nflId"),
            "playerName": obj.get("playerName"),
            "position": obj.get("position"),
            "positionGroup": obj.get("positionGroup"),
            "teamId": obj.get("teamId"),
            "uniformNumber": obj.get("uniformNumber")
        })
        return _obj


