# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NFLRosterResponseRoster(BaseModel):
    """
    NFLRosterResponseRoster
    """ # noqa: E501
    defense: Optional[List[NFLNFLPlayer]] = None
    injured_reserve: Optional[List[NFLNFLPlayer]] = Field(default=None, alias="injuredReserve")
    offense: Optional[List[NFLNFLPlayer]] = None
    practice_squad: Optional[List[NFLNFLPlayer]] = Field(default=None, alias="practiceSquad")
    special_teams: Optional[List[NFLNFLPlayer]] = Field(default=None, alias="specialTeams")
    __properties: ClassVar[List[str]] = ["defense", "injuredReserve", "offense", "practiceSquad", "specialTeams"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFLRosterResponseRoster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in defense (list)
        _items = []
        if self.defense:
            for _item_defense in self.defense:
                if _item_defense:
                    _items.append(_item_defense.to_dict())
            _dict['defense'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in injured_reserve (list)
        _items = []
        if self.injured_reserve:
            for _item_injured_reserve in self.injured_reserve:
                if _item_injured_reserve:
                    _items.append(_item_injured_reserve.to_dict())
            _dict['injuredReserve'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in offense (list)
        _items = []
        if self.offense:
            for _item_offense in self.offense:
                if _item_offense:
                    _items.append(_item_offense.to_dict())
            _dict['offense'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in practice_squad (list)
        _items = []
        if self.practice_squad:
            for _item_practice_squad in self.practice_squad:
                if _item_practice_squad:
                    _items.append(_item_practice_squad.to_dict())
            _dict['practiceSquad'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in special_teams (list)
        _items = []
        if self.special_teams:
            for _item_special_teams in self.special_teams:
                if _item_special_teams:
                    _items.append(_item_special_teams.to_dict())
            _dict['specialTeams'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFLRosterResponseRoster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defense": [NFLNFLPlayer.from_dict(_item) for _item in obj["defense"]] if obj.get("defense") is not None else None,
            "injuredReserve": [NFLNFLPlayer.from_dict(_item) for _item in obj["injuredReserve"]] if obj.get("injuredReserve") is not None else None,
            "offense": [NFLNFLPlayer.from_dict(_item) for _item in obj["offense"]] if obj.get("offense") is not None else None,
            "practiceSquad": [NFLNFLPlayer.from_dict(_item) for _item in obj["practiceSquad"]] if obj.get("practiceSquad") is not None else None,
            "specialTeams": [NFLNFLPlayer.from_dict(_item) for _item in obj["specialTeams"]] if obj.get("specialTeams") is not None else None
        })
        return _obj


