# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NFLDraftPick(BaseModel):
    """
    NFLDraftPick
    """ # noqa: E501
    college: Optional[StrictStr] = None
    is_compensatory: Optional[StrictBool] = Field(default=None, alias="isCompensatory")
    original_team: Optional[NFLNFLTeam] = Field(default=None, alias="originalTeam")
    overall_pick: Optional[StrictInt] = Field(default=None, alias="overallPick")
    pick: Optional[StrictInt] = None
    player: Optional[NFLNFLPlayer] = None
    position: Optional[StrictStr] = None
    round: Optional[StrictInt] = None
    team: Optional[NFLNFLTeam] = None
    __properties: ClassVar[List[str]] = ["college", "isCompensatory", "originalTeam", "overallPick", "pick", "player", "position", "round", "team"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFLDraftPick from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of original_team
        if self.original_team:
            _dict['originalTeam'] = self.original_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFLDraftPick from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "college": obj.get("college"),
            "isCompensatory": obj.get("isCompensatory"),
            "originalTeam": NFLNFLTeam.from_dict(obj["originalTeam"]) if obj.get("originalTeam") is not None else None,
            "overallPick": obj.get("overallPick"),
            "pick": obj.get("pick"),
            "player": NFLNFLPlayer.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "position": obj.get("position"),
            "round": obj.get("round"),
            "team": NFLNFLTeam.from_dict(obj["team"]) if obj.get("team") is not None else None
        })
        return _obj


