"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class OffensiveSkillPositionEnum(str, Enum):
    r"""Offensive skill position (excluding QB)"""

    FB = "FB"
    RB = "RB"
    TE = "TE"
    WR = "WR"
