"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .defensivepassrushstats import (
    DefensivePassRushStats,
    DefensivePassRushStatsTypedDict,
)
from .seasontypeenum import SeasonTypeEnum
from .sortorderenum import SortOrderEnum
from griddy.nfl.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PassRushStatsResponseTypedDict(TypedDict):
    r"""Common pagination and query metadata for stats responses"""

    limit: NotRequired[int]
    r"""Maximum number of results returned"""
    offset: NotRequired[int]
    r"""Number of records skipped"""
    season: NotRequired[int]
    r"""Season year"""
    season_type: NotRequired[SeasonTypeEnum]
    r"""Type of NFL season"""
    sort_key: NotRequired[str]
    r"""Field used for sorting"""
    sort_value: NotRequired[SortOrderEnum]
    r"""Sort direction for ordered results"""
    total: NotRequired[int]
    r"""Total number of items matching the criteria"""
    defenders: NotRequired[List[DefensivePassRushStatsTypedDict]]
    qualified_defender: NotRequired[bool]
    r"""Whether results are filtered to qualified defenders only"""


class PassRushStatsResponse(BaseModel):
    r"""Common pagination and query metadata for stats responses"""

    limit: Optional[int] = None
    r"""Maximum number of results returned"""

    offset: Optional[int] = None
    r"""Number of records skipped"""

    season: Optional[int] = None
    r"""Season year"""

    season_type: Annotated[
        Optional[SeasonTypeEnum], pydantic.Field(alias="seasonType")
    ] = None
    r"""Type of NFL season"""

    sort_key: Annotated[Optional[str], pydantic.Field(alias="sortKey")] = None
    r"""Field used for sorting"""

    sort_value: Annotated[
        Optional[SortOrderEnum], pydantic.Field(alias="sortValue")
    ] = None
    r"""Sort direction for ordered results"""

    total: Optional[int] = None
    r"""Total number of items matching the criteria"""

    defenders: Optional[List[DefensivePassRushStats]] = None

    qualified_defender: Annotated[
        Optional[bool], pydantic.Field(alias="qualifiedDefender")
    ] = None
    r"""Whether results are filtered to qualified defenders only"""
