# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from src.griddy.nfl.models.player_projection_relationships_week_points_inner import (
    PlayerProjectionRelationshipsWeekPointsInner,
)
from src.griddy.nfl.models.player_projection_relationships_week_stats_inner import (
    PlayerProjectionRelationshipsWeekStatsInner,
)


class PlayerProjectionRelationships(BaseModel):
    """
    PlayerProjectionRelationships
    """  # noqa: E501

    week_points: Optional[List[PlayerProjectionRelationshipsWeekPointsInner]] = Field(
        default=None, alias="weekPoints"
    )
    week_stats: Optional[List[PlayerProjectionRelationshipsWeekStatsInner]] = Field(
        default=None, alias="weekStats"
    )
    __properties: ClassVar[List[str]] = ["weekPoints", "weekStats"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerProjectionRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in week_points (list)
        _items = []
        if self.week_points:
            for _item_week_points in self.week_points:
                if _item_week_points:
                    _items.append(_item_week_points.to_dict())
            _dict["weekPoints"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in week_stats (list)
        _items = []
        if self.week_stats:
            for _item_week_stats in self.week_stats:
                if _item_week_stats:
                    _items.append(_item_week_stats.to_dict())
            _dict["weekStats"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerProjectionRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "weekPoints": (
                    [
                        PlayerProjectionRelationshipsWeekPointsInner.from_dict(_item)
                        for _item in obj["weekPoints"]
                    ]
                    if obj.get("weekPoints") is not None
                    else None
                ),
                "weekStats": (
                    [
                        PlayerProjectionRelationshipsWeekStatsInner.from_dict(_item)
                        for _item in obj["weekStats"]
                    ]
                    if obj.get("weekStats") is not None
                    else None
                ),
            }
        )
        return _obj
