"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PlayParticipantRoleEnum(str, Enum):
    PASSER = "PASSER"
    RUSHER = "RUSHER"
    RECEIVER = "RECEIVER"
    TACKLER = "TACKLER"
    KICKER = "KICKER"
    RETURNER = "RETURNER"
    BLOCKER = "BLOCKER"
