"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from griddy.nfl.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AttributesTypedDict(TypedDict):
    player_id: NotRequired[str]
    r"""Player SMART ID"""
    points: NotRequired[Nullable[float]]
    r"""Projected fantasy points"""
    season: NotRequired[int]
    r"""Season year"""
    settings_code: NotRequired[str]
    r"""Fantasy settings code"""
    week: NotRequired[int]
    r"""Week number"""


class Attributes(BaseModel):
    player_id: Annotated[Optional[str], pydantic.Field(alias="playerId")] = None
    r"""Player SMART ID"""

    points: OptionalNullable[float] = UNSET
    r"""Projected fantasy points"""

    season: Optional[int] = None
    r"""Season year"""

    settings_code: Annotated[Optional[str], pydantic.Field(alias="settingsCode")] = None
    r"""Fantasy settings code"""

    week: Optional[int] = None
    r"""Week number"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["playerId", "points", "season", "settingsCode", "week"]
        nullable_fields = ["points"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PlayerWeekProjectedPointsType(str, Enum):
    PLAYER_WEEK_PROJECTED_POINTS = "player-week-projected-points"


class PlayerWeekProjectedPointsTypedDict(TypedDict):
    attributes: NotRequired[AttributesTypedDict]
    id: NotRequired[str]
    r"""Unique identifier for this projection"""
    type: NotRequired[PlayerWeekProjectedPointsType]


class PlayerWeekProjectedPoints(BaseModel):
    attributes: Optional[Attributes] = None

    id: Optional[str] = None
    r"""Unique identifier for this projection"""

    type: Optional[PlayerWeekProjectedPointsType] = None
