"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PlayDirectionEnum(str, Enum):
    r"""Direction of play"""

    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"
