# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing_extensions import Self

from src.griddy.nfl.models.play_direction_enum import PlayDirectionEnum
from src.griddy.nfl.models.play_stat import PlayStat
from src.griddy.nfl.models.play_state_enum import PlayStateEnum
from src.griddy.nfl.models.play_type_enum import PlayTypeEnum


class PlayDetail(BaseModel):
    """
    PlayDetail
    """  # noqa: E501

    absolute_yardline_number: Optional[StrictInt] = Field(
        default=None,
        description="Absolute position on 100-yard field",
        alias="absoluteYardlineNumber",
    )
    down: Optional[StrictInt] = Field(
        default=None, description="Current down (0 for kickoff)"
    )
    end_game_clock: Optional[StrictStr] = Field(
        default=None, description="Game clock at play end", alias="endGameClock"
    )
    expected_points: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Expected points value", alias="expectedPoints"
    )
    expected_points_added: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Expected points added on this play",
        alias="expectedPointsAdded",
    )
    game_clock: Optional[StrictStr] = Field(
        default=None, description="Time on game clock", alias="gameClock"
    )
    game_id: Optional[StrictInt] = Field(default=None, alias="gameId")
    home_score: Optional[StrictInt] = Field(default=None, alias="homeScore")
    home_timeouts_left: Optional[StrictInt] = Field(
        default=None,
        description="Home team timeouts remaining",
        alias="homeTimeoutsLeft",
    )
    is_big_play: Optional[StrictBool] = Field(default=None, alias="isBigPlay")
    is_change_of_possession: Optional[StrictBool] = Field(
        default=None, alias="isChangeOfPossession"
    )
    is_end_quarter: Optional[StrictBool] = Field(default=None, alias="isEndQuarter")
    is_goal_to_go: Optional[StrictBool] = Field(default=None, alias="isGoalToGo")
    is_no_play: Optional[StrictBool] = Field(default=None, alias="isNoPlay")
    is_penalty: Optional[StrictBool] = Field(default=None, alias="isPenalty")
    is_played_out_play: Optional[StrictBool] = Field(
        default=None, alias="isPlayedOutPlay"
    )
    is_playtime_play: Optional[StrictBool] = Field(default=None, alias="isPlaytimePlay")
    is_redzone_play: Optional[StrictBool] = Field(default=None, alias="isRedzonePlay")
    is_st_play: Optional[StrictBool] = Field(
        default=None, description="Special teams play", alias="isSTPlay"
    )
    is_scoring: Optional[StrictBool] = Field(default=None, alias="isScoring")
    play_description: Optional[StrictStr] = Field(
        default=None,
        description="Play description without jersey numbers",
        alias="playDescription",
    )
    play_description_with_jersey_numbers: Optional[StrictStr] = Field(
        default=None,
        description="Play description including jersey numbers",
        alias="playDescriptionWithJerseyNumbers",
    )
    play_direction: Optional[PlayDirectionEnum] = Field(
        default=None, alias="playDirection"
    )
    play_id: Optional[StrictInt] = Field(default=None, alias="playId")
    play_state: Optional[PlayStateEnum] = Field(default=None, alias="playState")
    play_stats: Optional[List[PlayStat]] = Field(
        default=None,
        description="Individual player statistics for this play",
        alias="playStats",
    )
    play_type: Optional[PlayTypeEnum] = Field(default=None, alias="playType")
    play_type_code: Optional[StrictInt] = Field(
        default=None, description="Numeric code for play type", alias="playTypeCode"
    )
    possession_team_id: Optional[StrictStr] = Field(
        default=None, description="Team ID with possession", alias="possessionTeamId"
    )
    post_play_home_team_win_probability: Optional[Union[StrictFloat, StrictInt]] = (
        Field(
            default=None,
            description="Home team win probability after play",
            alias="postPlayHomeTeamWinProbability",
        )
    )
    post_play_visitor_team_win_probability: Optional[Union[StrictFloat, StrictInt]] = (
        Field(
            default=None,
            description="Visitor team win probability after play",
            alias="postPlayVisitorTeamWinProbability",
        )
    )
    pre_snap_home_score: Optional[StrictInt] = Field(
        default=None, alias="preSnapHomeScore"
    )
    pre_snap_home_team_win_probability: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Home team win probability before play",
        alias="preSnapHomeTeamWinProbability",
    )
    pre_snap_visitor_score: Optional[StrictInt] = Field(
        default=None, alias="preSnapVisitorScore"
    )
    pre_snap_visitor_team_win_probability: Optional[Union[StrictFloat, StrictInt]] = (
        Field(
            default=None,
            description="Visitor team win probability before play",
            alias="preSnapVisitorTeamWinProbability",
        )
    )
    quarter: Optional[StrictInt] = Field(default=None, description="Current quarter")
    sequence: Optional[StrictInt] = Field(
        default=None, description="Play sequence number"
    )
    start_game_clock: Optional[StrictStr] = Field(
        default=None, description="Game clock at play start", alias="startGameClock"
    )
    time_of_day_utc: Optional[datetime] = Field(
        default=None, description="UTC timestamp of play", alias="timeOfDayUTC"
    )
    visitor_score: Optional[StrictInt] = Field(default=None, alias="visitorScore")
    visitor_timeouts_left: Optional[StrictInt] = Field(
        default=None,
        description="Visitor team timeouts remaining",
        alias="visitorTimeoutsLeft",
    )
    yardline: Optional[StrictStr] = Field(default=None, description="Field position")
    yardline_number: Optional[StrictInt] = Field(
        default=None, description="Yard line number", alias="yardlineNumber"
    )
    yardline_side: Optional[StrictStr] = Field(
        default=None, description="Side of field", alias="yardlineSide"
    )
    yards_to_go: Optional[StrictInt] = Field(
        default=None, description="Yards needed for first down", alias="yardsToGo"
    )
    __properties: ClassVar[List[str]] = [
        "absoluteYardlineNumber",
        "down",
        "endGameClock",
        "expectedPoints",
        "expectedPointsAdded",
        "gameClock",
        "gameId",
        "homeScore",
        "homeTimeoutsLeft",
        "isBigPlay",
        "isChangeOfPossession",
        "isEndQuarter",
        "isGoalToGo",
        "isNoPlay",
        "isPenalty",
        "isPlayedOutPlay",
        "isPlaytimePlay",
        "isRedzonePlay",
        "isSTPlay",
        "isScoring",
        "playDescription",
        "playDescriptionWithJerseyNumbers",
        "playDirection",
        "playId",
        "playState",
        "playStats",
        "playType",
        "playTypeCode",
        "possessionTeamId",
        "postPlayHomeTeamWinProbability",
        "postPlayVisitorTeamWinProbability",
        "preSnapHomeScore",
        "preSnapHomeTeamWinProbability",
        "preSnapVisitorScore",
        "preSnapVisitorTeamWinProbability",
        "quarter",
        "sequence",
        "startGameClock",
        "timeOfDayUTC",
        "visitorScore",
        "visitorTimeoutsLeft",
        "yardline",
        "yardlineNumber",
        "yardlineSide",
        "yardsToGo",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in play_stats (list)
        _items = []
        if self.play_stats:
            for _item_play_stats in self.play_stats:
                if _item_play_stats:
                    _items.append(_item_play_stats.to_dict())
            _dict["playStats"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "absoluteYardlineNumber": obj.get("absoluteYardlineNumber"),
                "down": obj.get("down"),
                "endGameClock": obj.get("endGameClock"),
                "expectedPoints": obj.get("expectedPoints"),
                "expectedPointsAdded": obj.get("expectedPointsAdded"),
                "gameClock": obj.get("gameClock"),
                "gameId": obj.get("gameId"),
                "homeScore": obj.get("homeScore"),
                "homeTimeoutsLeft": obj.get("homeTimeoutsLeft"),
                "isBigPlay": obj.get("isBigPlay"),
                "isChangeOfPossession": obj.get("isChangeOfPossession"),
                "isEndQuarter": obj.get("isEndQuarter"),
                "isGoalToGo": obj.get("isGoalToGo"),
                "isNoPlay": obj.get("isNoPlay"),
                "isPenalty": obj.get("isPenalty"),
                "isPlayedOutPlay": obj.get("isPlayedOutPlay"),
                "isPlaytimePlay": obj.get("isPlaytimePlay"),
                "isRedzonePlay": obj.get("isRedzonePlay"),
                "isSTPlay": obj.get("isSTPlay"),
                "isScoring": obj.get("isScoring"),
                "playDescription": obj.get("playDescription"),
                "playDescriptionWithJerseyNumbers": obj.get(
                    "playDescriptionWithJerseyNumbers"
                ),
                "playDirection": obj.get("playDirection"),
                "playId": obj.get("playId"),
                "playState": obj.get("playState"),
                "playStats": (
                    [PlayStat.from_dict(_item) for _item in obj["playStats"]]
                    if obj.get("playStats") is not None
                    else None
                ),
                "playType": obj.get("playType"),
                "playTypeCode": obj.get("playTypeCode"),
                "possessionTeamId": obj.get("possessionTeamId"),
                "postPlayHomeTeamWinProbability": obj.get(
                    "postPlayHomeTeamWinProbability"
                ),
                "postPlayVisitorTeamWinProbability": obj.get(
                    "postPlayVisitorTeamWinProbability"
                ),
                "preSnapHomeScore": obj.get("preSnapHomeScore"),
                "preSnapHomeTeamWinProbability": obj.get(
                    "preSnapHomeTeamWinProbability"
                ),
                "preSnapVisitorScore": obj.get("preSnapVisitorScore"),
                "preSnapVisitorTeamWinProbability": obj.get(
                    "preSnapVisitorTeamWinProbability"
                ),
                "quarter": obj.get("quarter"),
                "sequence": obj.get("sequence"),
                "startGameClock": obj.get("startGameClock"),
                "timeOfDayUTC": obj.get("timeOfDayUTC"),
                "visitorScore": obj.get("visitorScore"),
                "visitorTimeoutsLeft": obj.get("visitorTimeoutsLeft"),
                "yardline": obj.get("yardline"),
                "yardlineNumber": obj.get("yardlineNumber"),
                "yardlineSide": obj.get("yardlineSide"),
                "yardsToGo": obj.get("yardsToGo"),
            }
        )
        return _obj
