"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


PracticeStatusEnum = Literal[
    "DNP",
    "LIMITED",
    "FULL",
    "NOT_LISTED",
]
r"""Player practice participation status"""
