"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class RoofTypeEnum(str, Enum):
    r"""Stadium roof type"""

    OUTDOOR = "OUTDOOR"
    INDOOR = "INDOOR"
    DOME = "DOME"
    RETRACTABLE = "RETRACTABLE"
