"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from griddy.nfl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RushLocationMapEntryTypedDict(TypedDict):
    yards: NotRequired[int]
    attempts: NotRequired[int]
    touchdowns: NotRequired[int]
    distance: NotRequired[float]
    avg_yards: NotRequired[float]
    avg_distance: NotRequired[float]
    avg_time_to_los: NotRequired[float]


class RushLocationMapEntry(BaseModel):
    yards: Optional[int] = None

    attempts: Optional[int] = None

    touchdowns: Optional[int] = None

    distance: Optional[float] = None

    avg_yards: Annotated[Optional[float], pydantic.Field(alias="avgYards")] = None

    avg_distance: Annotated[Optional[float], pydantic.Field(alias="avgDistance")] = None

    avg_time_to_los: Annotated[
        Optional[float], pydantic.Field(alias="avgTimeToLos")
    ] = None
