"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from griddy_nfl.types import BaseModel
from griddy_nfl.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class SearchPlayersRequestTypedDict(TypedDict):
    term: str
    r"""Search term for player name (first or last name)"""


class SearchPlayersRequest(BaseModel):
    term: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Search term for player name (first or last name)"""
