"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SeasonTypeEnum(str, Enum):
    r"""Type of NFL season"""

    PRE = "PRE"
    REG = "REG"
    POST = "POST"
