# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from griddy.nfl.models.roof_type_enum import RoofTypeEnum


class Site(BaseModel):
    """
    Stadium or venue information for a game
    """  # noqa: E501

    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    roof_type: Optional[RoofTypeEnum] = Field(default=None, alias="roofType")
    site_city: Optional[StrictStr] = Field(default=None, alias="siteCity")
    site_full_name: Optional[StrictStr] = Field(
        default=None, description="Stadium name", alias="siteFullName"
    )
    site_id: Optional[StrictInt] = Field(default=None, alias="siteId")
    site_state: Optional[StrictStr] = Field(default=None, alias="siteState")
    smart_id: Optional[StrictStr] = Field(default=None, alias="smartId")
    __properties: ClassVar[List[str]] = [
        "postalCode",
        "roofType",
        "siteCity",
        "siteFullName",
        "siteId",
        "siteState",
        "smartId",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Site from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict["postalCode"] = None

        # set to None if site_state (nullable) is None
        # and model_fields_set contains the field
        if self.site_state is None and "site_state" in self.model_fields_set:
            _dict["siteState"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Site from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "postalCode": obj.get("postalCode"),
                "roofType": obj.get("roofType"),
                "siteCity": obj.get("siteCity"),
                "siteFullName": obj.get("siteFullName"),
                "siteId": obj.get("siteId"),
                "siteState": obj.get("siteState"),
                "smartId": obj.get("smartId"),
            }
        )
        return _obj
