"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextgenstatspositionenum import NextGenStatsPositionEnum
from griddy.nfl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SpeedLeaderEntryTypedDict(TypedDict):
    gsis_play_id: NotRequired[int]
    esb_id: NotRequired[str]
    jersey_number: NotRequired[int]
    player_name: NotRequired[str]
    position: NotRequired[NextGenStatsPositionEnum]
    r"""Next Gen Stats player position"""
    short_name: NotRequired[str]
    team_id: NotRequired[str]
    headshot: NotRequired[str]
    r"""URL to player headshot image (contains formatInstructions placeholder)"""
    max_speed: NotRequired[float]


class SpeedLeaderEntry(BaseModel):
    gsis_play_id: Annotated[Optional[int], pydantic.Field(alias="gsisPlayId")] = None

    esb_id: Annotated[Optional[str], pydantic.Field(alias="esbId")] = None

    jersey_number: Annotated[Optional[int], pydantic.Field(alias="jerseyNumber")] = None

    player_name: Annotated[Optional[str], pydantic.Field(alias="playerName")] = None

    position: Optional[NextGenStatsPositionEnum] = None
    r"""Next Gen Stats player position"""

    short_name: Annotated[Optional[str], pydantic.Field(alias="shortName")] = None

    team_id: Annotated[Optional[str], pydantic.Field(alias="teamId")] = None

    headshot: Optional[str] = None
    r"""URL to player headshot image (contains formatInstructions placeholder)"""

    max_speed: Annotated[Optional[float], pydantic.Field(alias="maxSpeed")] = None
