# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from griddy.nfl.models.clinched import Clinched
from griddy.nfl.models.overall_record import OverallRecord
from griddy.nfl.models.points_record import PointsRecord
from griddy.nfl.models.record import Record
from griddy.nfl.models.standings_record import StandingsRecord
from griddy.nfl.models.standings_team import StandingsTeam


class Standings(BaseModel):
    """
    Standings
    """  # noqa: E501

    clinched: Optional[Clinched] = None
    close_games: Optional[Record] = Field(default=None, alias="closeGames")
    conference: Optional[StandingsRecord] = None
    division: Optional[StandingsRecord] = None
    home: Optional[PointsRecord] = None
    last5: Optional[PointsRecord] = None
    overall: Optional[OverallRecord] = None
    road: Optional[PointsRecord] = None
    team: Optional[StandingsTeam] = None
    __properties: ClassVar[List[str]] = [
        "clinched",
        "closeGames",
        "conference",
        "division",
        "home",
        "last5",
        "overall",
        "road",
        "team",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Standings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of clinched
        if self.clinched:
            _dict["clinched"] = self.clinched.to_dict()
        # override the default output from pydantic by calling `to_dict()` of close_games
        if self.close_games:
            _dict["closeGames"] = self.close_games.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conference
        if self.conference:
            _dict["conference"] = self.conference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of division
        if self.division:
            _dict["division"] = self.division.to_dict()
        # override the default output from pydantic by calling `to_dict()` of home
        if self.home:
            _dict["home"] = self.home.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last5
        if self.last5:
            _dict["last5"] = self.last5.to_dict()
        # override the default output from pydantic by calling `to_dict()` of overall
        if self.overall:
            _dict["overall"] = self.overall.to_dict()
        # override the default output from pydantic by calling `to_dict()` of road
        if self.road:
            _dict["road"] = self.road.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict["team"] = self.team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Standings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "clinched": (
                    Clinched.from_dict(obj["clinched"])
                    if obj.get("clinched") is not None
                    else None
                ),
                "closeGames": (
                    Record.from_dict(obj["closeGames"])
                    if obj.get("closeGames") is not None
                    else None
                ),
                "conference": (
                    StandingsRecord.from_dict(obj["conference"])
                    if obj.get("conference") is not None
                    else None
                ),
                "division": (
                    StandingsRecord.from_dict(obj["division"])
                    if obj.get("division") is not None
                    else None
                ),
                "home": (
                    PointsRecord.from_dict(obj["home"])
                    if obj.get("home") is not None
                    else None
                ),
                "last5": (
                    PointsRecord.from_dict(obj["last5"])
                    if obj.get("last5") is not None
                    else None
                ),
                "overall": (
                    OverallRecord.from_dict(obj["overall"])
                    if obj.get("overall") is not None
                    else None
                ),
                "road": (
                    PointsRecord.from_dict(obj["road"])
                    if obj.get("road") is not None
                    else None
                ),
                "team": (
                    StandingsTeam.from_dict(obj["team"])
                    if obj.get("team") is not None
                    else None
                ),
            }
        )
        return _obj
