# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)
"""  # noqa: E501

import json
from enum import Enum

from typing_extensions import Self


class StreakTypeEnum(str, Enum):
    """
    Winning/Losing (or Tie, I guess) streak types
    """

    """
    allowed enum values
    """
    W = "W"
    L = "L"
    T = "T"
    STREAK_TYPE_LOSING = "STREAK_TYPE_LOSING"
    STREAK_TYPE_WINNING = "STREAK_TYPE_WINNING"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GameResultEnum from a JSON string"""
        return cls(json.loads(json_str))
