"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .boxscoreschedule import BoxscoreSchedule, BoxscoreScheduleTypedDict
from .teamboxscore import TeamBoxscore, TeamBoxscoreTypedDict
from griddy.nfl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TeamBoxScore1TypedDict(TypedDict):
    away: NotRequired[TeamBoxscoreTypedDict]
    game_id: NotRequired[str]
    r"""Game identifier"""
    home: NotRequired[TeamBoxscoreTypedDict]
    schedule: NotRequired[BoxscoreScheduleTypedDict]


class TeamBoxScore1(BaseModel):
    away: Optional[TeamBoxscore] = None

    game_id: Annotated[Optional[str], pydantic.Field(alias="gameId")] = None
    r"""Game identifier"""

    home: Optional[TeamBoxscore] = None

    schedule: Optional[BoxscoreSchedule] = None
