# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from griddy.nfl.models.conference_enum import ConferenceEnum
from griddy.nfl.models.social_media import SocialMedia
from griddy.nfl.models.team_type_enum import TeamTypeEnum
from griddy.nfl.models.venue import Venue


class Team(BaseModel):
    """
    Team
    """  # noqa: E501

    abbreviation: Optional[StrictStr] = Field(
        default=None, description="Three-letter team abbreviation"
    )
    conference_abbr: Optional[ConferenceEnum] = Field(
        default=None, alias="conferenceAbbr"
    )
    conference_full_name: Optional[StrictStr] = Field(
        default=None, description="Full conference name", alias="conferenceFullName"
    )
    current_logo: Optional[StrictStr] = Field(
        default=None,
        description="URL to team logo (may contain {formatInstructions} placeholder)",
        alias="currentLogo",
    )
    division_full_name: Optional[StrictStr] = Field(
        default=None, description="Full division name", alias="divisionFullName"
    )
    full_name: Optional[StrictStr] = Field(
        default=None, description="Full team name", alias="fullName"
    )
    id: Optional[StrictStr] = Field(default=None, description="Unique team identifier")
    league: Optional[StrictStr] = Field(default=None, description="League name")
    location: Optional[StrictStr] = Field(
        default=None, description="Team location/city"
    )
    nfl_shop_url: Optional[StrictStr] = Field(
        default=None, description="URL to team's NFL shop", alias="nflShopUrl"
    )
    nick_name: Optional[StrictStr] = Field(
        default=None, description="Team nickname", alias="nickName"
    )
    official_website_url: Optional[StrictStr] = Field(
        default=None, description="Team's official website", alias="officialWebsiteUrl"
    )
    owners: Optional[StrictStr] = Field(
        default=None, description="Team ownership information"
    )
    primary_color: Optional[StrictStr] = Field(
        default=None, description="Primary team color (hex)", alias="primaryColor"
    )
    season: Optional[StrictStr] = Field(default=None, description="Current season")
    secondary_color: Optional[StrictStr] = Field(
        default=None, description="Secondary team color (hex)", alias="secondaryColor"
    )
    socials: Optional[List[SocialMedia]] = None
    team_type: Optional[TeamTypeEnum] = Field(default=None, alias="teamType")
    venues: Optional[List[Venue]] = None
    year_established: Optional[StrictInt] = Field(
        default=None, description="Year team was established", alias="yearEstablished"
    )
    __properties: ClassVar[List[str]] = [
        "abbreviation",
        "conferenceAbbr",
        "conferenceFullName",
        "currentLogo",
        "divisionFullName",
        "fullName",
        "id",
        "league",
        "location",
        "nflShopUrl",
        "nickName",
        "officialWebsiteUrl",
        "owners",
        "primaryColor",
        "season",
        "secondaryColor",
        "socials",
        "teamType",
        "venues",
        "yearEstablished",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Team from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in socials (list)
        _items = []
        if self.socials:
            for _item_socials in self.socials:
                if _item_socials:
                    _items.append(_item_socials.to_dict())
            _dict["socials"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in venues (list)
        _items = []
        if self.venues:
            for _item_venues in self.venues:
                if _item_venues:
                    _items.append(_item_venues.to_dict())
            _dict["venues"] = _items
        # set to None if nfl_shop_url (nullable) is None
        # and model_fields_set contains the field
        if self.nfl_shop_url is None and "nfl_shop_url" in self.model_fields_set:
            _dict["nflShopUrl"] = None

        # set to None if official_website_url (nullable) is None
        # and model_fields_set contains the field
        if (
            self.official_website_url is None
            and "official_website_url" in self.model_fields_set
        ):
            _dict["officialWebsiteUrl"] = None

        # set to None if owners (nullable) is None
        # and model_fields_set contains the field
        if self.owners is None and "owners" in self.model_fields_set:
            _dict["owners"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Team from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "abbreviation": obj.get("abbreviation"),
                "conferenceAbbr": obj.get("conferenceAbbr"),
                "conferenceFullName": obj.get("conferenceFullName"),
                "currentLogo": obj.get("currentLogo"),
                "divisionFullName": obj.get("divisionFullName"),
                "fullName": obj.get("fullName"),
                "id": obj.get("id"),
                "league": obj.get("league"),
                "location": obj.get("location"),
                "nflShopUrl": obj.get("nflShopUrl"),
                "nickName": obj.get("nickName"),
                "officialWebsiteUrl": obj.get("officialWebsiteUrl"),
                "owners": obj.get("owners"),
                "primaryColor": obj.get("primaryColor"),
                "season": obj.get("season"),
                "secondaryColor": obj.get("secondaryColor"),
                "socials": (
                    [SocialMedia.from_dict(_item) for _item in obj["socials"]]
                    if obj.get("socials") is not None
                    else None
                ),
                "teamType": obj.get("teamType"),
                "venues": (
                    [Venue.from_dict(_item) for _item in obj["venues"]]
                    if obj.get("venues") is not None
                    else None
                ),
                "yearEstablished": obj.get("yearEstablished"),
            }
        )
        return _obj
