# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from griddy.nfl.models.player import Player
from griddy.nfl.models.team import Team
from griddy.nfl.models.transaction_type_enum import TransactionTypeEnum


class Transaction(BaseModel):
    """
    Transaction
    """  # noqa: E501

    compensation_details: Optional[StrictStr] = Field(
        default=None,
        description="Trade compensation or contract details",
        alias="compensationDetails",
    )
    var_date: Optional[datetime] = Field(default=None, alias="date")
    details: Optional[StrictStr] = Field(
        default=None, description="Transaction details"
    )
    id: Optional[StrictStr] = None
    player: Optional[Player] = None
    related_team: Optional[Team] = Field(default=None, alias="relatedTeam")
    team: Optional[Team] = None
    type: Optional[TransactionTypeEnum] = None
    __properties: ClassVar[List[str]] = [
        "compensationDetails",
        "date",
        "details",
        "id",
        "player",
        "relatedTeam",
        "team",
        "type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict["player"] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of related_team
        if self.related_team:
            _dict["relatedTeam"] = self.related_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict["team"] = self.team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "compensationDetails": obj.get("compensationDetails"),
                "date": obj.get("date"),
                "details": obj.get("details"),
                "id": obj.get("id"),
                "player": (
                    Player.from_dict(obj["player"])
                    if obj.get("player") is not None
                    else None
                ),
                "relatedTeam": (
                    Team.from_dict(obj["relatedTeam"])
                    if obj.get("relatedTeam") is not None
                    else None
                ),
                "team": (
                    Team.from_dict(obj["team"]) if obj.get("team") is not None else None
                ),
                "type": obj.get("type"),
            }
        )
        return _obj
