"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from griddy.nfl.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RequirementsTypedDict(TypedDict):
    country_code: NotRequired[List[str]]


class Requirements(BaseModel):
    country_code: Annotated[
        Optional[List[str]], pydantic.Field(alias="countryCode")
    ] = None


class NflPlusCoachesFilmTypedDict(TypedDict):
    requirements: NotRequired[RequirementsTypedDict]


class NflPlusCoachesFilm(BaseModel):
    requirements: Optional[Requirements] = None


class NflPlusPlusTypedDict(TypedDict):
    nfl_plus_coaches_film: NotRequired[NflPlusCoachesFilmTypedDict]


class NflPlusPlus(BaseModel):
    nfl_plus_coaches_film: Annotated[
        Optional[NflPlusCoachesFilm], pydantic.Field(alias="NFL PLUS - COACHES FILM")
    ] = None


class VideoAuthorizationsRequirementsTypedDict(TypedDict):
    country_code: NotRequired[List[str]]


class VideoAuthorizationsRequirements(BaseModel):
    country_code: Annotated[
        Optional[List[str]], pydantic.Field(alias="countryCode")
    ] = None


class VideoAuthorizationsNFLPLUSCOACHESFILMTypedDict(TypedDict):
    requirements: NotRequired[VideoAuthorizationsRequirementsTypedDict]


class VideoAuthorizationsNFLPLUSCOACHESFILM(BaseModel):
    requirements: Optional[VideoAuthorizationsRequirements] = None


class NflPlusPremiumTypedDict(TypedDict):
    nfl_plus_coaches_film: NotRequired[VideoAuthorizationsNFLPLUSCOACHESFILMTypedDict]


class NflPlusPremium(BaseModel):
    nfl_plus_coaches_film: Annotated[
        Optional[VideoAuthorizationsNFLPLUSCOACHESFILM],
        pydantic.Field(alias="NFL PLUS - COACHES FILM"),
    ] = None


class VideoAuthorizationsSchemasRequirementsTypedDict(TypedDict):
    country_code: NotRequired[List[str]]


class VideoAuthorizationsSchemasRequirements(BaseModel):
    country_code: Annotated[
        Optional[List[str]], pydantic.Field(alias="countryCode")
    ] = None


class VideoAuthorizationsSchemasNFLPLUSCOACHESFILMTypedDict(TypedDict):
    requirements: NotRequired[VideoAuthorizationsSchemasRequirementsTypedDict]


class VideoAuthorizationsSchemasNFLPLUSCOACHESFILM(BaseModel):
    requirements: Optional[VideoAuthorizationsSchemasRequirements] = None


class ProPremiumTypedDict(TypedDict):
    nfl_plus_coaches_film: NotRequired[
        VideoAuthorizationsSchemasNFLPLUSCOACHESFILMTypedDict
    ]


class ProPremium(BaseModel):
    nfl_plus_coaches_film: Annotated[
        Optional[VideoAuthorizationsSchemasNFLPLUSCOACHESFILM],
        pydantic.Field(alias="NFL PLUS - COACHES FILM"),
    ] = None


class VideoAuthorizationsTypedDict(TypedDict):
    r"""Authorization requirements for video access"""

    nfl_plus_plus: NotRequired[List[NflPlusPlusTypedDict]]
    nfl_plus_premium: NotRequired[List[NflPlusPremiumTypedDict]]
    pro_premium: NotRequired[List[ProPremiumTypedDict]]


class VideoAuthorizations(BaseModel):
    r"""Authorization requirements for video access"""

    nfl_plus_plus: Optional[List[NflPlusPlus]] = None

    nfl_plus_premium: Optional[List[NflPlusPremium]] = None

    pro_premium: Optional[List[ProPremium]] = None
