# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from nfl.models.nflnfl_binary_flag_enum import NFLNFLBinaryFlagEnum
from nfl.models.nflnfl_filmroom_plays_response import NFLNFLFilmroomPlaysResponse
from nfl.models.nflnfl_play_type_enum import NFLNFLPlayTypeEnum
from nfl.models.nflnfl_season_type_enum import NFLNFLSeasonTypeEnum
from nfl.models.nflnfl_week_slug_enum import NFLNFLWeekSlugEnum

from nfl.api_client import ApiClient, RequestSerialized
from nfl.api_response import ApiResponse
from nfl.rest import RESTResponseType


class FilmroomController:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_filmroom_plays(
        self,
        game_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by specific game IDs (supports multiple values)")] = None,
        week_slug: Annotated[Optional[List[NFLNFLWeekSlugEnum]], Field(description="Filter by week identifier (supports multiple values)")] = None,
        season: Annotated[Optional[List[StrictInt]], Field(description="Filter by season year (supports multiple values)")] = None,
        season_type: Annotated[Optional[List[NFLNFLSeasonTypeEnum]], Field(description="Filter by season type")] = None,
        nfl_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by player NFL ID")] = None,
        quarter: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by quarter")] = None,
        down: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by down")] = None,
        yards_to_go_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by yards to go category")] = None,
        touchdown: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for touchdown plays (1 = yes, 0 = no)")] = None,
        rush10_plus_yards: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for rushing plays of 10+ yards")] = None,
        fumble_lost: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles lost")] = None,
        fumble: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles")] = None,
        qb_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by quarterback alignment")] = None,
        redzone: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for red zone plays")] = None,
        goal_to_go: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for goal-to-go situations")] = None,
        pass_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing plays")] = None,
        run_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for running plays")] = None,
        play_type: Annotated[Optional[List[NFLNFLPlayTypeEnum]], Field(description="Filter by specific play types")] = None,
        attempt: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing attempts")] = None,
        completion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for completed passes")] = None,
        interception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for interceptions")] = None,
        reception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for receptions")] = None,
        sack: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for sacks")] = None,
        rec_motion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by receiver motion")] = None,
        target_location: Annotated[Optional[List[StrictStr]], Field(description="Filter by target location on field")] = None,
        air_yard_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by air yards category")] = None,
        dropback_time_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by dropback time")] = None,
        pressure: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by quarterback pressure")] = None,
        blitz: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by defensive blitz")] = None,
        play_action: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by play action usage")] = None,
        rush_direction: Annotated[Optional[List[StrictStr]], Field(description="Filter by rush direction")] = None,
        run_stuff: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for stuffed runs")] = None,
        receiver_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver alignment")] = None,
        separation_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver separation")] = None,
        personnel: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive personnel package")] = None,
        defenders_in_the_box_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defenders in the box")] = None,
        def_coverage_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive coverage type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> NFLNFLFilmroomPlaysResponse:
        """Get Filmroom Plays with Advanced Filtering

        Retrieves detailed play-by-play data with extensive filtering capabilities for film study. Returns comprehensive play information including formations, personnel packages, game situations, and detailed play descriptions. This endpoint supports advanced filtering by game situation, player involvement, formation types, and tactical elements. 

        :param game_id: Filter by specific game IDs (supports multiple values)
        :type game_id: List[str]
        :param week_slug: Filter by week identifier (supports multiple values)
        :type week_slug: List[NFLNFLWeekSlugEnum]
        :param season: Filter by season year (supports multiple values)
        :type season: List[int]
        :param season_type: Filter by season type
        :type season_type: List[NFLNFLSeasonTypeEnum]
        :param nfl_id: Filter by player NFL ID
        :type nfl_id: List[str]
        :param quarter: Filter by quarter
        :type quarter: List[int]
        :param down: Filter by down
        :type down: List[int]
        :param yards_to_go_type: Filter by yards to go category
        :type yards_to_go_type: List[str]
        :param touchdown: Filter for touchdown plays (1 = yes, 0 = no)
        :type touchdown: List[NFLNFLBinaryFlagEnum]
        :param rush10_plus_yards: Filter for rushing plays of 10+ yards
        :type rush10_plus_yards: List[NFLNFLBinaryFlagEnum]
        :param fumble_lost: Filter for plays with fumbles lost
        :type fumble_lost: List[NFLNFLBinaryFlagEnum]
        :param fumble: Filter for plays with fumbles
        :type fumble: List[NFLNFLBinaryFlagEnum]
        :param qb_alignment: Filter by quarterback alignment
        :type qb_alignment: List[str]
        :param redzone: Filter for red zone plays
        :type redzone: List[NFLNFLBinaryFlagEnum]
        :param goal_to_go: Filter for goal-to-go situations
        :type goal_to_go: List[NFLNFLBinaryFlagEnum]
        :param pass_play: Filter for passing plays
        :type pass_play: List[NFLNFLBinaryFlagEnum]
        :param run_play: Filter for running plays
        :type run_play: List[NFLNFLBinaryFlagEnum]
        :param play_type: Filter by specific play types
        :type play_type: List[NFLNFLPlayTypeEnum]
        :param attempt: Filter for passing attempts
        :type attempt: List[NFLNFLBinaryFlagEnum]
        :param completion: Filter for completed passes
        :type completion: List[NFLNFLBinaryFlagEnum]
        :param interception: Filter for interceptions
        :type interception: List[NFLNFLBinaryFlagEnum]
        :param reception: Filter for receptions
        :type reception: List[NFLNFLBinaryFlagEnum]
        :param sack: Filter for sacks
        :type sack: List[NFLNFLBinaryFlagEnum]
        :param rec_motion: Filter by receiver motion
        :type rec_motion: List[NFLNFLBinaryFlagEnum]
        :param target_location: Filter by target location on field
        :type target_location: List[str]
        :param air_yard_type: Filter by air yards category
        :type air_yard_type: List[str]
        :param dropback_time_type: Filter by dropback time
        :type dropback_time_type: List[str]
        :param pressure: Filter by quarterback pressure
        :type pressure: List[NFLNFLBinaryFlagEnum]
        :param blitz: Filter by defensive blitz
        :type blitz: List[NFLNFLBinaryFlagEnum]
        :param play_action: Filter by play action usage
        :type play_action: List[NFLNFLBinaryFlagEnum]
        :param rush_direction: Filter by rush direction
        :type rush_direction: List[str]
        :param run_stuff: Filter for stuffed runs
        :type run_stuff: List[NFLNFLBinaryFlagEnum]
        :param receiver_alignment: Filter by receiver alignment
        :type receiver_alignment: List[str]
        :param separation_type: Filter by receiver separation
        :type separation_type: List[str]
        :param personnel: Filter by defensive personnel package
        :type personnel: List[str]
        :param defenders_in_the_box_type: Filter by defenders in the box
        :type defenders_in_the_box_type: List[str]
        :param def_coverage_type: Filter by defensive coverage type
        :type def_coverage_type: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_filmroom_plays_serialize(
            game_id=game_id,
            week_slug=week_slug,
            season=season,
            season_type=season_type,
            nfl_id=nfl_id,
            quarter=quarter,
            down=down,
            yards_to_go_type=yards_to_go_type,
            touchdown=touchdown,
            rush10_plus_yards=rush10_plus_yards,
            fumble_lost=fumble_lost,
            fumble=fumble,
            qb_alignment=qb_alignment,
            redzone=redzone,
            goal_to_go=goal_to_go,
            pass_play=pass_play,
            run_play=run_play,
            play_type=play_type,
            attempt=attempt,
            completion=completion,
            interception=interception,
            reception=reception,
            sack=sack,
            rec_motion=rec_motion,
            target_location=target_location,
            air_yard_type=air_yard_type,
            dropback_time_type=dropback_time_type,
            pressure=pressure,
            blitz=blitz,
            play_action=play_action,
            rush_direction=rush_direction,
            run_stuff=run_stuff,
            receiver_alignment=receiver_alignment,
            separation_type=separation_type,
            personnel=personnel,
            defenders_in_the_box_type=defenders_in_the_box_type,
            def_coverage_type=def_coverage_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NFLNFLFilmroomPlaysResponse",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_filmroom_plays_with_http_info(
        self,
        game_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by specific game IDs (supports multiple values)")] = None,
        week_slug: Annotated[Optional[List[NFLNFLWeekSlugEnum]], Field(description="Filter by week identifier (supports multiple values)")] = None,
        season: Annotated[Optional[List[StrictInt]], Field(description="Filter by season year (supports multiple values)")] = None,
        season_type: Annotated[Optional[List[NFLNFLSeasonTypeEnum]], Field(description="Filter by season type")] = None,
        nfl_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by player NFL ID")] = None,
        quarter: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by quarter")] = None,
        down: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by down")] = None,
        yards_to_go_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by yards to go category")] = None,
        touchdown: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for touchdown plays (1 = yes, 0 = no)")] = None,
        rush10_plus_yards: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for rushing plays of 10+ yards")] = None,
        fumble_lost: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles lost")] = None,
        fumble: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles")] = None,
        qb_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by quarterback alignment")] = None,
        redzone: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for red zone plays")] = None,
        goal_to_go: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for goal-to-go situations")] = None,
        pass_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing plays")] = None,
        run_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for running plays")] = None,
        play_type: Annotated[Optional[List[NFLNFLPlayTypeEnum]], Field(description="Filter by specific play types")] = None,
        attempt: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing attempts")] = None,
        completion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for completed passes")] = None,
        interception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for interceptions")] = None,
        reception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for receptions")] = None,
        sack: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for sacks")] = None,
        rec_motion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by receiver motion")] = None,
        target_location: Annotated[Optional[List[StrictStr]], Field(description="Filter by target location on field")] = None,
        air_yard_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by air yards category")] = None,
        dropback_time_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by dropback time")] = None,
        pressure: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by quarterback pressure")] = None,
        blitz: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by defensive blitz")] = None,
        play_action: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by play action usage")] = None,
        rush_direction: Annotated[Optional[List[StrictStr]], Field(description="Filter by rush direction")] = None,
        run_stuff: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for stuffed runs")] = None,
        receiver_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver alignment")] = None,
        separation_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver separation")] = None,
        personnel: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive personnel package")] = None,
        defenders_in_the_box_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defenders in the box")] = None,
        def_coverage_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive coverage type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> ApiResponse[NFLNFLFilmroomPlaysResponse]:
        """Get Filmroom Plays with Advanced Filtering

        Retrieves detailed play-by-play data with extensive filtering capabilities for film study. Returns comprehensive play information including formations, personnel packages, game situations, and detailed play descriptions. This endpoint supports advanced filtering by game situation, player involvement, formation types, and tactical elements. 

        :param game_id: Filter by specific game IDs (supports multiple values)
        :type game_id: List[str]
        :param week_slug: Filter by week identifier (supports multiple values)
        :type week_slug: List[NFLNFLWeekSlugEnum]
        :param season: Filter by season year (supports multiple values)
        :type season: List[int]
        :param season_type: Filter by season type
        :type season_type: List[NFLNFLSeasonTypeEnum]
        :param nfl_id: Filter by player NFL ID
        :type nfl_id: List[str]
        :param quarter: Filter by quarter
        :type quarter: List[int]
        :param down: Filter by down
        :type down: List[int]
        :param yards_to_go_type: Filter by yards to go category
        :type yards_to_go_type: List[str]
        :param touchdown: Filter for touchdown plays (1 = yes, 0 = no)
        :type touchdown: List[NFLNFLBinaryFlagEnum]
        :param rush10_plus_yards: Filter for rushing plays of 10+ yards
        :type rush10_plus_yards: List[NFLNFLBinaryFlagEnum]
        :param fumble_lost: Filter for plays with fumbles lost
        :type fumble_lost: List[NFLNFLBinaryFlagEnum]
        :param fumble: Filter for plays with fumbles
        :type fumble: List[NFLNFLBinaryFlagEnum]
        :param qb_alignment: Filter by quarterback alignment
        :type qb_alignment: List[str]
        :param redzone: Filter for red zone plays
        :type redzone: List[NFLNFLBinaryFlagEnum]
        :param goal_to_go: Filter for goal-to-go situations
        :type goal_to_go: List[NFLNFLBinaryFlagEnum]
        :param pass_play: Filter for passing plays
        :type pass_play: List[NFLNFLBinaryFlagEnum]
        :param run_play: Filter for running plays
        :type run_play: List[NFLNFLBinaryFlagEnum]
        :param play_type: Filter by specific play types
        :type play_type: List[NFLNFLPlayTypeEnum]
        :param attempt: Filter for passing attempts
        :type attempt: List[NFLNFLBinaryFlagEnum]
        :param completion: Filter for completed passes
        :type completion: List[NFLNFLBinaryFlagEnum]
        :param interception: Filter for interceptions
        :type interception: List[NFLNFLBinaryFlagEnum]
        :param reception: Filter for receptions
        :type reception: List[NFLNFLBinaryFlagEnum]
        :param sack: Filter for sacks
        :type sack: List[NFLNFLBinaryFlagEnum]
        :param rec_motion: Filter by receiver motion
        :type rec_motion: List[NFLNFLBinaryFlagEnum]
        :param target_location: Filter by target location on field
        :type target_location: List[str]
        :param air_yard_type: Filter by air yards category
        :type air_yard_type: List[str]
        :param dropback_time_type: Filter by dropback time
        :type dropback_time_type: List[str]
        :param pressure: Filter by quarterback pressure
        :type pressure: List[NFLNFLBinaryFlagEnum]
        :param blitz: Filter by defensive blitz
        :type blitz: List[NFLNFLBinaryFlagEnum]
        :param play_action: Filter by play action usage
        :type play_action: List[NFLNFLBinaryFlagEnum]
        :param rush_direction: Filter by rush direction
        :type rush_direction: List[str]
        :param run_stuff: Filter for stuffed runs
        :type run_stuff: List[NFLNFLBinaryFlagEnum]
        :param receiver_alignment: Filter by receiver alignment
        :type receiver_alignment: List[str]
        :param separation_type: Filter by receiver separation
        :type separation_type: List[str]
        :param personnel: Filter by defensive personnel package
        :type personnel: List[str]
        :param defenders_in_the_box_type: Filter by defenders in the box
        :type defenders_in_the_box_type: List[str]
        :param def_coverage_type: Filter by defensive coverage type
        :type def_coverage_type: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_filmroom_plays_serialize(
            game_id=game_id,
            week_slug=week_slug,
            season=season,
            season_type=season_type,
            nfl_id=nfl_id,
            quarter=quarter,
            down=down,
            yards_to_go_type=yards_to_go_type,
            touchdown=touchdown,
            rush10_plus_yards=rush10_plus_yards,
            fumble_lost=fumble_lost,
            fumble=fumble,
            qb_alignment=qb_alignment,
            redzone=redzone,
            goal_to_go=goal_to_go,
            pass_play=pass_play,
            run_play=run_play,
            play_type=play_type,
            attempt=attempt,
            completion=completion,
            interception=interception,
            reception=reception,
            sack=sack,
            rec_motion=rec_motion,
            target_location=target_location,
            air_yard_type=air_yard_type,
            dropback_time_type=dropback_time_type,
            pressure=pressure,
            blitz=blitz,
            play_action=play_action,
            rush_direction=rush_direction,
            run_stuff=run_stuff,
            receiver_alignment=receiver_alignment,
            separation_type=separation_type,
            personnel=personnel,
            defenders_in_the_box_type=defenders_in_the_box_type,
            def_coverage_type=def_coverage_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NFLNFLFilmroomPlaysResponse",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_filmroom_plays_without_preload_content(
        self,
        game_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by specific game IDs (supports multiple values)")] = None,
        week_slug: Annotated[Optional[List[NFLNFLWeekSlugEnum]], Field(description="Filter by week identifier (supports multiple values)")] = None,
        season: Annotated[Optional[List[StrictInt]], Field(description="Filter by season year (supports multiple values)")] = None,
        season_type: Annotated[Optional[List[NFLNFLSeasonTypeEnum]], Field(description="Filter by season type")] = None,
        nfl_id: Annotated[Optional[List[StrictStr]], Field(description="Filter by player NFL ID")] = None,
        quarter: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by quarter")] = None,
        down: Annotated[Optional[List[Annotated[int, Field(le=4, strict=True, ge=1)]]], Field(description="Filter by down")] = None,
        yards_to_go_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by yards to go category")] = None,
        touchdown: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for touchdown plays (1 = yes, 0 = no)")] = None,
        rush10_plus_yards: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for rushing plays of 10+ yards")] = None,
        fumble_lost: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles lost")] = None,
        fumble: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for plays with fumbles")] = None,
        qb_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by quarterback alignment")] = None,
        redzone: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for red zone plays")] = None,
        goal_to_go: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for goal-to-go situations")] = None,
        pass_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing plays")] = None,
        run_play: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for running plays")] = None,
        play_type: Annotated[Optional[List[NFLNFLPlayTypeEnum]], Field(description="Filter by specific play types")] = None,
        attempt: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for passing attempts")] = None,
        completion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for completed passes")] = None,
        interception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for interceptions")] = None,
        reception: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for receptions")] = None,
        sack: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for sacks")] = None,
        rec_motion: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by receiver motion")] = None,
        target_location: Annotated[Optional[List[StrictStr]], Field(description="Filter by target location on field")] = None,
        air_yard_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by air yards category")] = None,
        dropback_time_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by dropback time")] = None,
        pressure: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by quarterback pressure")] = None,
        blitz: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by defensive blitz")] = None,
        play_action: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter by play action usage")] = None,
        rush_direction: Annotated[Optional[List[StrictStr]], Field(description="Filter by rush direction")] = None,
        run_stuff: Annotated[Optional[List[NFLNFLBinaryFlagEnum]], Field(description="Filter for stuffed runs")] = None,
        receiver_alignment: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver alignment")] = None,
        separation_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by receiver separation")] = None,
        personnel: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive personnel package")] = None,
        defenders_in_the_box_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defenders in the box")] = None,
        def_coverage_type: Annotated[Optional[List[StrictStr]], Field(description="Filter by defensive coverage type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> RESTResponseType:
        """Get Filmroom Plays with Advanced Filtering

        Retrieves detailed play-by-play data with extensive filtering capabilities for film study. Returns comprehensive play information including formations, personnel packages, game situations, and detailed play descriptions. This endpoint supports advanced filtering by game situation, player involvement, formation types, and tactical elements. 

        :param game_id: Filter by specific game IDs (supports multiple values)
        :type game_id: List[str]
        :param week_slug: Filter by week identifier (supports multiple values)
        :type week_slug: List[NFLNFLWeekSlugEnum]
        :param season: Filter by season year (supports multiple values)
        :type season: List[int]
        :param season_type: Filter by season type
        :type season_type: List[NFLNFLSeasonTypeEnum]
        :param nfl_id: Filter by player NFL ID
        :type nfl_id: List[str]
        :param quarter: Filter by quarter
        :type quarter: List[int]
        :param down: Filter by down
        :type down: List[int]
        :param yards_to_go_type: Filter by yards to go category
        :type yards_to_go_type: List[str]
        :param touchdown: Filter for touchdown plays (1 = yes, 0 = no)
        :type touchdown: List[NFLNFLBinaryFlagEnum]
        :param rush10_plus_yards: Filter for rushing plays of 10+ yards
        :type rush10_plus_yards: List[NFLNFLBinaryFlagEnum]
        :param fumble_lost: Filter for plays with fumbles lost
        :type fumble_lost: List[NFLNFLBinaryFlagEnum]
        :param fumble: Filter for plays with fumbles
        :type fumble: List[NFLNFLBinaryFlagEnum]
        :param qb_alignment: Filter by quarterback alignment
        :type qb_alignment: List[str]
        :param redzone: Filter for red zone plays
        :type redzone: List[NFLNFLBinaryFlagEnum]
        :param goal_to_go: Filter for goal-to-go situations
        :type goal_to_go: List[NFLNFLBinaryFlagEnum]
        :param pass_play: Filter for passing plays
        :type pass_play: List[NFLNFLBinaryFlagEnum]
        :param run_play: Filter for running plays
        :type run_play: List[NFLNFLBinaryFlagEnum]
        :param play_type: Filter by specific play types
        :type play_type: List[NFLNFLPlayTypeEnum]
        :param attempt: Filter for passing attempts
        :type attempt: List[NFLNFLBinaryFlagEnum]
        :param completion: Filter for completed passes
        :type completion: List[NFLNFLBinaryFlagEnum]
        :param interception: Filter for interceptions
        :type interception: List[NFLNFLBinaryFlagEnum]
        :param reception: Filter for receptions
        :type reception: List[NFLNFLBinaryFlagEnum]
        :param sack: Filter for sacks
        :type sack: List[NFLNFLBinaryFlagEnum]
        :param rec_motion: Filter by receiver motion
        :type rec_motion: List[NFLNFLBinaryFlagEnum]
        :param target_location: Filter by target location on field
        :type target_location: List[str]
        :param air_yard_type: Filter by air yards category
        :type air_yard_type: List[str]
        :param dropback_time_type: Filter by dropback time
        :type dropback_time_type: List[str]
        :param pressure: Filter by quarterback pressure
        :type pressure: List[NFLNFLBinaryFlagEnum]
        :param blitz: Filter by defensive blitz
        :type blitz: List[NFLNFLBinaryFlagEnum]
        :param play_action: Filter by play action usage
        :type play_action: List[NFLNFLBinaryFlagEnum]
        :param rush_direction: Filter by rush direction
        :type rush_direction: List[str]
        :param run_stuff: Filter for stuffed runs
        :type run_stuff: List[NFLNFLBinaryFlagEnum]
        :param receiver_alignment: Filter by receiver alignment
        :type receiver_alignment: List[str]
        :param separation_type: Filter by receiver separation
        :type separation_type: List[str]
        :param personnel: Filter by defensive personnel package
        :type personnel: List[str]
        :param defenders_in_the_box_type: Filter by defenders in the box
        :type defenders_in_the_box_type: List[str]
        :param def_coverage_type: Filter by defensive coverage type
        :type def_coverage_type: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_filmroom_plays_serialize(
            game_id=game_id,
            week_slug=week_slug,
            season=season,
            season_type=season_type,
            nfl_id=nfl_id,
            quarter=quarter,
            down=down,
            yards_to_go_type=yards_to_go_type,
            touchdown=touchdown,
            rush10_plus_yards=rush10_plus_yards,
            fumble_lost=fumble_lost,
            fumble=fumble,
            qb_alignment=qb_alignment,
            redzone=redzone,
            goal_to_go=goal_to_go,
            pass_play=pass_play,
            run_play=run_play,
            play_type=play_type,
            attempt=attempt,
            completion=completion,
            interception=interception,
            reception=reception,
            sack=sack,
            rec_motion=rec_motion,
            target_location=target_location,
            air_yard_type=air_yard_type,
            dropback_time_type=dropback_time_type,
            pressure=pressure,
            blitz=blitz,
            play_action=play_action,
            rush_direction=rush_direction,
            run_stuff=run_stuff,
            receiver_alignment=receiver_alignment,
            separation_type=separation_type,
            personnel=personnel,
            defenders_in_the_box_type=defenders_in_the_box_type,
            def_coverage_type=def_coverage_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NFLNFLFilmroomPlaysResponse",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_filmroom_plays_serialize(
        self,
        game_id,
        week_slug,
        season,
        season_type,
        nfl_id,
        quarter,
        down,
        yards_to_go_type,
        touchdown,
        rush10_plus_yards,
        fumble_lost,
        fumble,
        qb_alignment,
        redzone,
        goal_to_go,
        pass_play,
        run_play,
        play_type,
        attempt,
        completion,
        interception,
        reception,
        sack,
        rec_motion,
        target_location,
        air_yard_type,
        dropback_time_type,
        pressure,
        blitz,
        play_action,
        rush_direction,
        run_stuff,
        receiver_alignment,
        separation_type,
        personnel,
        defenders_in_the_box_type,
        def_coverage_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _hosts = [
            'https://pro.nfl.com'
        ]
        _host = _hosts[_host_index]

        _collection_formats: Dict[str, str] = {
            'gameId': 'multi',
            'weekSlug': 'multi',
            'season': 'multi',
            'seasonType': 'multi',
            'nflId': 'multi',
            'quarter': 'multi',
            'down': 'multi',
            'yardsToGoType': 'multi',
            'touchdown': 'multi',
            'rush10PlusYards': 'multi',
            'fumbleLost': 'multi',
            'fumble': 'multi',
            'qbAlignment': 'multi',
            'redzone': 'multi',
            'goalToGo': 'multi',
            'passPlay': 'multi',
            'runPlay': 'multi',
            'playType': 'multi',
            'attempt': 'multi',
            'completion': 'multi',
            'interception': 'multi',
            'reception': 'multi',
            'sack': 'multi',
            'rec_motion': 'multi',
            'targetLocation': 'multi',
            'airYardType': 'multi',
            'dropbackTimeType': 'multi',
            'pressure': 'multi',
            'blitz': 'multi',
            'playAction': 'multi',
            'rushDirection': 'multi',
            'runStuff': 'multi',
            'receiverAlignment': 'multi',
            'separationType': 'multi',
            'personnel': 'multi',
            'defendersInTheBoxType': 'multi',
            'def_coverageType': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if game_id is not None:
            
            _query_params.append(('gameId', game_id))
            
        if week_slug is not None:
            
            _query_params.append(('weekSlug', week_slug))
            
        if season is not None:
            
            _query_params.append(('season', season))
            
        if season_type is not None:
            
            _query_params.append(('seasonType', season_type))
            
        if nfl_id is not None:
            
            _query_params.append(('nflId', nfl_id))
            
        if quarter is not None:
            
            _query_params.append(('quarter', quarter))
            
        if down is not None:
            
            _query_params.append(('down', down))
            
        if yards_to_go_type is not None:
            
            _query_params.append(('yardsToGoType', yards_to_go_type))
            
        if touchdown is not None:
            
            _query_params.append(('touchdown', touchdown))
            
        if rush10_plus_yards is not None:
            
            _query_params.append(('rush10PlusYards', rush10_plus_yards))
            
        if fumble_lost is not None:
            
            _query_params.append(('fumbleLost', fumble_lost))
            
        if fumble is not None:
            
            _query_params.append(('fumble', fumble))
            
        if qb_alignment is not None:
            
            _query_params.append(('qbAlignment', qb_alignment))
            
        if redzone is not None:
            
            _query_params.append(('redzone', redzone))
            
        if goal_to_go is not None:
            
            _query_params.append(('goalToGo', goal_to_go))
            
        if pass_play is not None:
            
            _query_params.append(('passPlay', pass_play))
            
        if run_play is not None:
            
            _query_params.append(('runPlay', run_play))
            
        if play_type is not None:
            
            _query_params.append(('playType', play_type))
            
        if attempt is not None:
            
            _query_params.append(('attempt', attempt))
            
        if completion is not None:
            
            _query_params.append(('completion', completion))
            
        if interception is not None:
            
            _query_params.append(('interception', interception))
            
        if reception is not None:
            
            _query_params.append(('reception', reception))
            
        if sack is not None:
            
            _query_params.append(('sack', sack))
            
        if rec_motion is not None:
            
            _query_params.append(('rec_motion', rec_motion))
            
        if target_location is not None:
            
            _query_params.append(('targetLocation', target_location))
            
        if air_yard_type is not None:
            
            _query_params.append(('airYardType', air_yard_type))
            
        if dropback_time_type is not None:
            
            _query_params.append(('dropbackTimeType', dropback_time_type))
            
        if pressure is not None:
            
            _query_params.append(('pressure', pressure))
            
        if blitz is not None:
            
            _query_params.append(('blitz', blitz))
            
        if play_action is not None:
            
            _query_params.append(('playAction', play_action))
            
        if rush_direction is not None:
            
            _query_params.append(('rushDirection', rush_direction))
            
        if run_stuff is not None:
            
            _query_params.append(('runStuff', run_stuff))
            
        if receiver_alignment is not None:
            
            _query_params.append(('receiverAlignment', receiver_alignment))
            
        if separation_type is not None:
            
            _query_params.append(('separationType', separation_type))
            
        if personnel is not None:
            
            _query_params.append(('personnel', personnel))
            
        if defenders_in_the_box_type is not None:
            
            _query_params.append(('defendersInTheBoxType', defenders_in_the_box_type))
            
        if def_coverage_type is not None:
            
            _query_params.append(('def_coverageType', def_coverage_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'NFLAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/secured/videos/filmroom/plays',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


