# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from griddy.nfl.api_client import NFLAPIClient, RequestSerialized
from griddy.nfl.api_response import NFLAPIResponse
from griddy.nfl.models.passing_stats_category_enum import PassingStatsCategoryEnum
from griddy.nfl.models.passing_stats_response import PassingStatsResponse
from griddy.nfl.models.season_type_enum import SeasonTypeEnum
from griddy.nfl.models.sort_order_enum import SortOrderEnum
from griddy.nfl.rest import RESTResponseType


class PlayerStatisticsController:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = NFLAPIClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_player_passing_stats_by_season(
        self,
        season: Annotated[StrictInt, Field(description="Season year")],
        season_type: Annotated[SeasonTypeEnum, Field(description="Type of season")],
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of players to return"),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(description="Number of records to skip for pagination"),
        ] = None,
        page: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=1)]],
            Field(description="Page number for pagination"),
        ] = None,
        sort_key: Annotated[
            Optional[PassingStatsCategoryEnum], Field(description="Field to sort by")
        ] = None,
        sort_value: Annotated[
            Optional[SortOrderEnum], Field(description="Sort direction")
        ] = None,
        qualified_passer: Annotated[
            Optional[StrictBool],
            Field(
                description="Filter to only qualified passers (minimum attempts threshold)"
            ),
        ] = None,
        team_offense: Annotated[
            Optional[List[StrictStr]],
            Field(description="Filter by specific team IDs (supports multiple teams)"),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> PassingStatsResponse:
        """Get Player Passing Statistics by Season

        Retrieves comprehensive passing statistics for NFL players during a specified season. Returns detailed metrics including traditional stats, advanced analytics, and Next Gen Stats data. Supports filtering by teams, qualified passers only, and various sorting options. Data includes completion percentage, yards per attempt, passer rating, EPA (Expected Points Added), CPOE (Completion Percentage Over Expected), time to throw metrics, and situational statistics.

        :param season: Season year (required)
        :type season: int
        :param season_type: Type of season (required)
        :type season_type: SeasonTypeEnum
        :param limit: Maximum number of players to return
        :type limit: int
        :param offset: Number of records to skip for pagination
        :type offset: int
        :param page: Page number for pagination
        :type page: int
        :param sort_key: Field to sort by
        :type sort_key: PassingStatsCategoryEnum
        :param sort_value: Sort direction
        :type sort_value: SortOrderEnum
        :param qualified_passer: Filter to only qualified passers (minimum attempts threshold)
        :type qualified_passer: bool
        :param team_offense: Filter by specific team IDs (supports multiple teams)
        :type team_offense: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_player_passing_stats_by_season_serialize(
            season=season,
            season_type=season_type,
            limit=limit,
            offset=offset,
            page=page,
            sort_key=sort_key,
            sort_value=sort_value,
            qualified_passer=qualified_passer,
            team_offense=team_offense,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "PassingStatsResponse",
            "400": None,
            "401": None,
            "403": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_player_passing_stats_by_season_with_http_info(
        self,
        season: Annotated[StrictInt, Field(description="Season year")],
        season_type: Annotated[SeasonTypeEnum, Field(description="Type of season")],
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of players to return"),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(description="Number of records to skip for pagination"),
        ] = None,
        page: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=1)]],
            Field(description="Page number for pagination"),
        ] = None,
        sort_key: Annotated[
            Optional[PassingStatsCategoryEnum], Field(description="Field to sort by")
        ] = None,
        sort_value: Annotated[
            Optional[SortOrderEnum], Field(description="Sort direction")
        ] = None,
        qualified_passer: Annotated[
            Optional[StrictBool],
            Field(
                description="Filter to only qualified passers (minimum attempts threshold)"
            ),
        ] = None,
        team_offense: Annotated[
            Optional[List[StrictStr]],
            Field(description="Filter by specific team IDs (supports multiple teams)"),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> NFLAPIResponse[PassingStatsResponse]:
        """Get Player Passing Statistics by Season

        Retrieves comprehensive passing statistics for NFL players during a specified season. Returns detailed metrics including traditional stats, advanced analytics, and Next Gen Stats data. Supports filtering by teams, qualified passers only, and various sorting options. Data includes completion percentage, yards per attempt, passer rating, EPA (Expected Points Added), CPOE (Completion Percentage Over Expected), time to throw metrics, and situational statistics.

        :param season: Season year (required)
        :type season: int
        :param season_type: Type of season (required)
        :type season_type: SeasonTypeEnum
        :param limit: Maximum number of players to return
        :type limit: int
        :param offset: Number of records to skip for pagination
        :type offset: int
        :param page: Page number for pagination
        :type page: int
        :param sort_key: Field to sort by
        :type sort_key: PassingStatsCategoryEnum
        :param sort_value: Sort direction
        :type sort_value: SortOrderEnum
        :param qualified_passer: Filter to only qualified passers (minimum attempts threshold)
        :type qualified_passer: bool
        :param team_offense: Filter by specific team IDs (supports multiple teams)
        :type team_offense: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_player_passing_stats_by_season_serialize(
            season=season,
            season_type=season_type,
            limit=limit,
            offset=offset,
            page=page,
            sort_key=sort_key,
            sort_value=sort_value,
            qualified_passer=qualified_passer,
            team_offense=team_offense,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "PassingStatsResponse",
            "400": None,
            "401": None,
            "403": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_player_passing_stats_by_season_without_preload_content(
        self,
        season: Annotated[StrictInt, Field(description="Season year")],
        season_type: Annotated[SeasonTypeEnum, Field(description="Type of season")],
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of players to return"),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(description="Number of records to skip for pagination"),
        ] = None,
        page: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=1)]],
            Field(description="Page number for pagination"),
        ] = None,
        sort_key: Annotated[
            Optional[PassingStatsCategoryEnum], Field(description="Field to sort by")
        ] = None,
        sort_value: Annotated[
            Optional[SortOrderEnum], Field(description="Sort direction")
        ] = None,
        qualified_passer: Annotated[
            Optional[StrictBool],
            Field(
                description="Filter to only qualified passers (minimum attempts threshold)"
            ),
        ] = None,
        team_offense: Annotated[
            Optional[List[StrictStr]],
            Field(description="Filter by specific team IDs (supports multiple teams)"),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=1)] = 0,
    ) -> RESTResponseType:
        """Get Player Passing Statistics by Season

        Retrieves comprehensive passing statistics for NFL players during a specified season. Returns detailed metrics including traditional stats, advanced analytics, and Next Gen Stats data. Supports filtering by teams, qualified passers only, and various sorting options. Data includes completion percentage, yards per attempt, passer rating, EPA (Expected Points Added), CPOE (Completion Percentage Over Expected), time to throw metrics, and situational statistics.

        :param season: Season year (required)
        :type season: int
        :param season_type: Type of season (required)
        :type season_type: SeasonTypeEnum
        :param limit: Maximum number of players to return
        :type limit: int
        :param offset: Number of records to skip for pagination
        :type offset: int
        :param page: Page number for pagination
        :type page: int
        :param sort_key: Field to sort by
        :type sort_key: PassingStatsCategoryEnum
        :param sort_value: Sort direction
        :type sort_value: SortOrderEnum
        :param qualified_passer: Filter to only qualified passers (minimum attempts threshold)
        :type qualified_passer: bool
        :param team_offense: Filter by specific team IDs (supports multiple teams)
        :type team_offense: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_player_passing_stats_by_season_serialize(
            season=season,
            season_type=season_type,
            limit=limit,
            offset=offset,
            page=page,
            sort_key=sort_key,
            sort_value=sort_value,
            qualified_passer=qualified_passer,
            team_offense=team_offense,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "PassingStatsResponse",
            "400": None,
            "401": None,
            "403": None,
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _get_player_passing_stats_by_season_serialize(
        self,
        season,
        season_type,
        limit,
        offset,
        page,
        sort_key,
        sort_value,
        qualified_passer,
        team_offense,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _hosts = ["https://pro.nfl.com"]
        _host = _hosts[_host_index]

        _collection_formats: Dict[str, str] = {
            "teamOffense": "multi",
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if season is not None:

            _query_params.append(("season", season))

        if season_type is not None:

            _query_params.append(("seasonType", season_type.value))

        if limit is not None:

            _query_params.append(("limit", limit))

        if offset is not None:

            _query_params.append(("offset", offset))

        if page is not None:

            _query_params.append(("page", page))

        if sort_key is not None:

            _query_params.append(("sortKey", sort_key.value))

        if sort_value is not None:

            _query_params.append(("sortValue", sort_value.value))

        if qualified_passer is not None:

            _query_params.append(("qualifiedPasser", qualified_passer))

        if team_offense is not None:

            _query_params.append(("teamOffense", team_offense))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["NFLAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/secured/stats/players-offense/passing/season",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
