"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextgenstatspositionenum import NextGenStatsPositionEnum
from openapi.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BoxScorePlayerTacklesStatisticTypedDict(TypedDict):
    nfl_id: NotRequired[int]
    gsis_id: NotRequired[str]
    esb_id: NotRequired[str]
    jersey_number: NotRequired[int]
    player_name: NotRequired[str]
    short_name: NotRequired[str]
    team_id: NotRequired[str]
    headshot: NotRequired[str]
    r"""URL to player headshot image (contains formatInstructions placeholder)"""
    position: NotRequired[NextGenStatsPositionEnum]
    r"""Next Gen Stats player position"""
    count: NotRequired[int]
    assists: NotRequired[int]
    sacks: NotRequired[float]
    sack_yards: NotRequired[int]
    qb_hits: NotRequired[int]
    safeties: NotRequired[int]
    tackles_for_loss: NotRequired[int]
    tackles_for_loss_yards: NotRequired[int]
    special_teams_tackles: NotRequired[int]
    special_teams_assists: NotRequired[int]
    special_teams_blocks: NotRequired[int]
    miscellaneous_tackles: NotRequired[int]
    miscellaneous_assists: NotRequired[int]


class BoxScorePlayerTacklesStatistic(BaseModel):
    nfl_id: Annotated[Optional[int], pydantic.Field(alias="nflId")] = None

    gsis_id: Annotated[Optional[str], pydantic.Field(alias="gsisId")] = None

    esb_id: Annotated[Optional[str], pydantic.Field(alias="esbId")] = None

    jersey_number: Annotated[Optional[int], pydantic.Field(alias="jerseyNumber")] = None

    player_name: Annotated[Optional[str], pydantic.Field(alias="playerName")] = None

    short_name: Annotated[Optional[str], pydantic.Field(alias="shortName")] = None

    team_id: Annotated[Optional[str], pydantic.Field(alias="teamId")] = None

    headshot: Optional[str] = None
    r"""URL to player headshot image (contains formatInstructions placeholder)"""

    position: Optional[NextGenStatsPositionEnum] = None
    r"""Next Gen Stats player position"""

    count: Optional[int] = None

    assists: Optional[int] = None

    sacks: Optional[float] = None

    sack_yards: Annotated[Optional[int], pydantic.Field(alias="sackYards")] = None

    qb_hits: Annotated[Optional[int], pydantic.Field(alias="qbHits")] = None

    safeties: Optional[int] = None

    tackles_for_loss: Annotated[
        Optional[int], pydantic.Field(alias="tacklesForLoss")
    ] = None

    tackles_for_loss_yards: Annotated[
        Optional[int], pydantic.Field(alias="tacklesForLossYards")
    ] = None

    special_teams_tackles: Annotated[
        Optional[int], pydantic.Field(alias="specialTeamsTackles")
    ] = None

    special_teams_assists: Annotated[
        Optional[int], pydantic.Field(alias="specialTeamsAssists")
    ] = None

    special_teams_blocks: Annotated[
        Optional[int], pydantic.Field(alias="specialTeamsBlocks")
    ] = None

    miscellaneous_tackles: Annotated[
        Optional[int], pydantic.Field(alias="miscellaneousTackles")
    ] = None

    miscellaneous_assists: Annotated[
        Optional[int], pydantic.Field(alias="miscellaneousAssists")
    ] = None
