"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextgenstatspositionenum import NextGenStatsPositionEnum
from openapi.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BoxScorePlayerKickingStatisticTypedDict(TypedDict):
    nfl_id: NotRequired[int]
    gsis_id: NotRequired[str]
    esb_id: NotRequired[str]
    jersey_number: NotRequired[int]
    player_name: NotRequired[str]
    short_name: NotRequired[str]
    team_id: NotRequired[str]
    headshot: NotRequired[str]
    r"""URL to player headshot image (contains formatInstructions placeholder)"""
    position: NotRequired[NextGenStatsPositionEnum]
    r"""Next Gen Stats player position"""
    count: NotRequired[int]
    yards: NotRequired[int]
    touchback_cnt: NotRequired[int]
    inside20_cnt: NotRequired[int]
    out_of_bounds_cnt: NotRequired[int]
    to_endzone_cnt: NotRequired[int]
    return_yards: NotRequired[int]


class BoxScorePlayerKickingStatistic(BaseModel):
    nfl_id: Annotated[Optional[int], pydantic.Field(alias="nflId")] = None

    gsis_id: Annotated[Optional[str], pydantic.Field(alias="gsisId")] = None

    esb_id: Annotated[Optional[str], pydantic.Field(alias="esbId")] = None

    jersey_number: Annotated[Optional[int], pydantic.Field(alias="jerseyNumber")] = None

    player_name: Annotated[Optional[str], pydantic.Field(alias="playerName")] = None

    short_name: Annotated[Optional[str], pydantic.Field(alias="shortName")] = None

    team_id: Annotated[Optional[str], pydantic.Field(alias="teamId")] = None

    headshot: Optional[str] = None
    r"""URL to player headshot image (contains formatInstructions placeholder)"""

    position: Optional[NextGenStatsPositionEnum] = None
    r"""Next Gen Stats player position"""

    count: Optional[int] = None

    yards: Optional[int] = None

    touchback_cnt: Annotated[Optional[int], pydantic.Field(alias="touchbackCnt")] = None

    inside20_cnt: Annotated[Optional[int], pydantic.Field(alias="inside20Cnt")] = None

    out_of_bounds_cnt: Annotated[
        Optional[int], pydantic.Field(alias="outOfBoundsCnt")
    ] = None

    to_endzone_cnt: Annotated[Optional[int], pydantic.Field(alias="toEndzoneCnt")] = (
        None
    )

    return_yards: Annotated[Optional[int], pydantic.Field(alias="returnYards")] = None
