"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nextgenstatspositionenum import NextGenStatsPositionEnum
from openapi.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BoxScorePlayerPassingStatisticTypedDict(TypedDict):
    nfl_id: NotRequired[int]
    gsis_id: NotRequired[str]
    esb_id: NotRequired[str]
    jersey_number: NotRequired[int]
    player_name: NotRequired[str]
    short_name: NotRequired[str]
    team_id: NotRequired[str]
    headshot: NotRequired[str]
    r"""URL to player headshot image (contains formatInstructions placeholder)"""
    position: NotRequired[NextGenStatsPositionEnum]
    r"""Next Gen Stats player position"""
    attempts: NotRequired[int]
    completions: NotRequired[int]
    completion_pct: NotRequired[float]
    yards: NotRequired[int]
    yards_per_attempt: NotRequired[float]
    lost_sacked_yards: NotRequired[int]
    sacks: NotRequired[int]
    touchdowns: NotRequired[int]
    longest_pass_completion: NotRequired[int]
    longest_td_pass: NotRequired[int]
    interceptions: NotRequired[int]
    qb_rating: NotRequired[float]


class BoxScorePlayerPassingStatistic(BaseModel):
    nfl_id: Annotated[Optional[int], pydantic.Field(alias="nflId")] = None

    gsis_id: Annotated[Optional[str], pydantic.Field(alias="gsisId")] = None

    esb_id: Annotated[Optional[str], pydantic.Field(alias="esbId")] = None

    jersey_number: Annotated[Optional[int], pydantic.Field(alias="jerseyNumber")] = None

    player_name: Annotated[Optional[str], pydantic.Field(alias="playerName")] = None

    short_name: Annotated[Optional[str], pydantic.Field(alias="shortName")] = None

    team_id: Annotated[Optional[str], pydantic.Field(alias="teamId")] = None

    headshot: Optional[str] = None
    r"""URL to player headshot image (contains formatInstructions placeholder)"""

    position: Optional[NextGenStatsPositionEnum] = None
    r"""Next Gen Stats player position"""

    attempts: Optional[int] = None

    completions: Optional[int] = None

    completion_pct: Annotated[
        Optional[float], pydantic.Field(alias="completionPct")
    ] = None

    yards: Optional[int] = None

    yards_per_attempt: Annotated[
        Optional[float], pydantic.Field(alias="yardsPerAttempt")
    ] = None

    lost_sacked_yards: Annotated[
        Optional[int], pydantic.Field(alias="lostSackedYards")
    ] = None

    sacks: Optional[int] = None

    touchdowns: Optional[int] = None

    longest_pass_completion: Annotated[
        Optional[int], pydantic.Field(alias="longestPassCompletion")
    ] = None

    longest_td_pass: Annotated[Optional[int], pydantic.Field(alias="longestTdPass")] = (
        None
    )

    interceptions: Optional[int] = None

    qb_rating: Annotated[Optional[float], pydantic.Field(alias="qbRating")] = None
