"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_EXPERIENCE_TEAMS_OP_SERVERS = [
    # Production Regular NFL API
    "https://api.nfl.com",
]


class GetExperienceTeamsRequestTypedDict(TypedDict):
    season: int
    r"""Season year"""
    allteams: NotRequired[bool]
    r"""Include all teams including special teams"""


class GetExperienceTeamsRequest(BaseModel):
    season: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Season year"""

    allteams: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Include all teams including special teams"""
