"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


GET_GAMECENTER_OP_SERVERS = [
    # Production NFL Pro API
    "https://pro.nfl.com",
]


class GetGamecenterRequestTypedDict(TypedDict):
    game_id: str
    r"""Game identifier"""


class GetGamecenterRequest(BaseModel):
    game_id: Annotated[
        str,
        pydantic.Field(alias="gameId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Game identifier"""
