"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


LineOfScrimmageDistanceEnum = Literal[
    "behindLOS",
    "losTo9",
    "10To19",
    "20Plus",
]
