"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


NextGenStatsPositionEnum = Literal[
    "C",
    "CB",
    "DB",
    "DE",
    "DT",
    "ED",
    "FB",
    "FS",
    "G",
    "ILB",
    "K",
    "LB",
    "LS",
    "MLB",
    "NT",
    "OL",
    "OLB",
    "P",
    "QB",
    "RB",
    "S",
    "SCB",
    "SS",
    "T",
    "TE",
    "WR",
]
r"""Next Gen Stats player position"""
