"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


PlayDirectionEnum = Literal[
    "left",
    "right",
    "middle",
]
r"""Direction of play"""
