"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StatisticTypedDict(TypedDict):
    type: NotRequired[str]
    r"""Statistical category name"""
    value: NotRequired[float]
    r"""Statistical value"""


class Statistic(BaseModel):
    type: Optional[str] = None
    r"""Statistical category name"""

    value: Optional[float] = None
    r"""Statistical value"""


class StatisticRankingTypedDict(TypedDict):
    rank: NotRequired[int]
    r"""Team's rank in this category (1-32)"""
    statistic: NotRequired[StatisticTypedDict]


class StatisticRanking(BaseModel):
    rank: Optional[int] = None
    r"""Team's rank in this category (1-32)"""

    statistic: Optional[Statistic] = None
