"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import httpx
import importlib
import json
import requests
import sys
import time
import urllib
import weakref

from typing import Any, Callable, Dict, Optional, TYPE_CHECKING, Union, cast

from ..core.utils import extract_cookies_as_dict

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
from ..nfl import models, utils
from ._hooks import SDKHooks
from .types import OptionalNullable, UNSET

from griddy import settings

if TYPE_CHECKING:
    from .authentication import Authentication
    from .betting import Betting
    from .content_insights import ContentInsights
    from .content_sdk import ContentSDK
    from .defensive_pass_rush_statistics import DefensivePassRushStatistics
    from .defensive_player_overview import DefensivePlayerOverview
    from .defensive_statistics import DefensiveStatistics
    from .experience import Experience
    from .fantasy_statistics import FantasyStatistics
    from .filmroom import Filmroom
    from .football import Football
    from .player_passing_statistics import PlayerPassingStatistics
    from .player_receiving_statistics import PlayerReceivingStatistics
    from .player_rushing_statistics import PlayerRushingStatistics
    from .player_statistics import PlayerStatistics
    from .players import Players
    from .plays import Plays
    from .schedules import Schedules
    from .schedules_extended import SchedulesExtended
    from .scores import Scores
    from .season_schedule import SeasonSchedule
    from .secured_videos import SecuredVideos
    from .stats_sdk import StatsSDK
    from .team_defense_pass_statistics import TeamDefensePassStatistics
    from .team_defense_rush_statistics import TeamDefenseRushStatistics
    from .team_defense_statistics import TeamDefenseStatistics
    from .team_offense_overview_statistics import (
        TeamOffenseOverviewStatistics,
    )
    from .team_offense_pass_statistics import TeamOffensePassStatistics
    from .teams import Teams
    from .win_probability import WinProbability


class GriddyNFL(BaseSDK):
    r"""NFL REST APIs: Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights."""

    content: "ContentSDK"
    r"""Game previews, film cards, and insights"""
    content_insights: "ContentInsights"
    r"""Editorial insights and analytics content about NFL players and games"""
    players: "Players"
    r"""Player information, statistics, and projections"""
    plays: "Plays"
    r"""Play-by-play data and film room analysis"""
    schedules_extended: "SchedulesExtended"
    r"""Current games, standings, and betting futures"""
    schedules: "Schedules"
    r"""Game schedules, matchup rankings, and injury reports"""
    betting: "Betting"
    r"""Game betting odds and lines"""
    season_schedule: "SeasonSchedule"
    r"""Season weeks and bye information"""
    scores: "Scores"
    r"""Real-time scoring and game status endpoints"""
    win_probability: "WinProbability"
    r"""Game and play-level win probability analytics"""
    defensive_statistics: "DefensiveStatistics"
    r"""Individual defensive player statistics and coverage analytics"""
    defensive_player_overview: "DefensivePlayerOverview"
    r"""Comprehensive individual defensive player statistics and analytics"""
    defensive_pass_rush_statistics: "DefensivePassRushStatistics"
    r"""Individual defensive player pass rush statistics and analytics"""
    fantasy_statistics: "FantasyStatistics"
    r"""Fantasy football player statistics and scoring metrics"""
    player_statistics: "PlayerStatistics"
    r"""Individual player passing statistics and analytics"""
    player_passing_statistics: "PlayerPassingStatistics"
    r"""Individual player passing statistics and analytics by week"""
    player_receiving_statistics: "PlayerReceivingStatistics"
    r"""Individual player receiving statistics and analytics"""
    player_rushing_statistics: "PlayerRushingStatistics"
    r"""Individual player rushing statistics and analytics"""
    team_defense_statistics: "TeamDefenseStatistics"
    r"""Comprehensive team defensive statistics and situational analytics"""
    team_defense_pass_statistics: "TeamDefensePassStatistics"
    r"""Comprehensive team defensive pass statistics and situational analytics"""
    team_defense_rush_statistics: "TeamDefenseRushStatistics"
    r"""Comprehensive team defensive rush statistics and situational analytics"""
    team_offense_overview_statistics: "TeamOffenseOverviewStatistics"
    r"""Comprehensive team offensive overview statistics and situational analytics"""
    team_offense_pass_statistics: "TeamOffensePassStatistics"
    r"""Comprehensive team offensive pass statistics and situational analytics"""
    secured_videos: "SecuredVideos"
    r"""Premium coaches film video content with multiple camera angles"""
    filmroom: "Filmroom"
    r"""Advanced play analysis and film study data"""
    stats: "StatsSDK"
    r"""Comprehensive game and team statistics endpoints"""
    teams: "Teams"
    r"""Team information, rosters, and schedules"""
    experience: "Experience"
    r"""Experience API endpoints for games and teams"""
    football: "Football"
    r"""Football API endpoints for games, standings, stats, and venues"""
    authentication: "Authentication"
    r"""Token generation and refresh operations for NFL API access"""
    _sub_sdk_map = {
        "content": ("griddy_nfl.content_sdk", "ContentSDK"),
        "content_insights": ("griddy_nfl.content_insights", "ContentInsights"),
        "players": ("griddy_nfl.players", "Players"),
        "plays": ("griddy_nfl.plays", "Plays"),
        "schedules_extended": ("griddy_nfl.schedules_extended", "SchedulesExtended"),
        "schedules": ("griddy_nfl.schedules", "Schedules"),
        "betting": ("griddy_nfl.betting", "Betting"),
        "season_schedule": ("griddy_nfl.season_schedule", "SeasonSchedule"),
        "scores": ("griddy_nfl.scores", "Scores"),
        "win_probability": ("griddy_nfl.win_probability", "WinProbability"),
        "defensive_statistics": (
            "griddy_nfl.defensive_statistics",
            "DefensiveStatistics",
        ),
        "defensive_player_overview": (
            "griddy_nfl.defensive_player_overview",
            "DefensivePlayerOverview",
        ),
        "defensive_pass_rush_statistics": (
            "griddy_nfl.defensive_pass_rush_statistics",
            "DefensivePassRushStatistics",
        ),
        "fantasy_statistics": ("griddy_nfl.fantasy_statistics", "FantasyStatistics"),
        "player_statistics": ("griddy_nfl.player_statistics", "PlayerStatistics"),
        "player_passing_statistics": (
            "griddy_nfl.player_passing_statistics",
            "PlayerPassingStatistics",
        ),
        "player_receiving_statistics": (
            "griddy_nfl.player_receiving_statistics",
            "PlayerReceivingStatistics",
        ),
        "player_rushing_statistics": (
            "griddy_nfl.player_rushing_statistics",
            "PlayerRushingStatistics",
        ),
        "team_defense_statistics": (
            "griddy_nfl.team_defense_statistics",
            "TeamDefenseStatistics",
        ),
        "team_defense_pass_statistics": (
            "griddy_nfl.team_defense_pass_statistics",
            "TeamDefensePassStatistics",
        ),
        "team_defense_rush_statistics": (
            "griddy_nfl.team_defense_rush_statistics",
            "TeamDefenseRushStatistics",
        ),
        "team_offense_overview_statistics": (
            "griddy_nfl.team_offense_overview_statistics",
            "TeamOffenseOverviewStatistics",
        ),
        "team_offense_pass_statistics": (
            "griddy_nfl.team_offense_pass_statistics",
            "TeamOffensePassStatistics",
        ),
        "secured_videos": ("griddy_nfl.secured_videos", "SecuredVideos"),
        "filmroom": ("griddy_nfl.filmroom", "Filmroom"),
        "stats": ("griddy_nfl.stats_sdk", "StatsSDK"),
        "teams": ("griddy_nfl.teams", "Teams"),
        "experience": ("griddy_nfl.experience", "Experience"),
        "football": ("griddy_nfl.football", "Football"),
        "authentication": ("griddy_nfl.authentication", "Authentication"),
    }

    def __init__(
        self,
        cookies_file: str,
        nfl_auth: Optional[Union[Optional[str], Callable[[], Optional[str]]]] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param nfl_auth: The file path of a Netscape formatted cookies file used to set up NFL auth.
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        self.cookies_file = cookies_file
        self._account_info = self.load_account_info()
        self._token = {}
        self.get_auth_token()
        security: Any = None
        if callable(nfl_auth):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.Security(nfl_auth=nfl_auth())
        else:
            security = models.Security(nfl_auth=nfl_auth)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def _token_is_fresh(self) -> bool:
        """
        Determine if it's time to refresh our access token

        Returns:
            A bool which is True if the token is fresh; False otherwise
        """
        return (self._token.get("accessToken") is not None) and self._token.get(
            "expiresIn"
        ) > time.time() + 30

    def get_auth_token(self):
        """
        Get and store an authentication token if necessary.
        """
        if self._token_is_fresh():
            return

        token_url = settings.NFL["token_url"]
        if self._token.get("refreshToken"):
            token_url += "/refresh"

        token_request_data = json.dumps(
            {**self._client_data, **self._account_info}, separators=(",", ":")
        ).encode()
        response = requests.post(
            token_url,
            data=token_request_data,
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()

        self._token = response.json()
        self.session.headers.update(
            {"Authorization": f"Bearer {self._token['accessToken']}"}
        )

    def load_account_info(self):
        """
        Load account information to be used in token requests.
        """
        nfl_auth_cookies = extract_cookies_as_dict(
            self.cookies_file, settings.NFL["auth_url"]
        )
        login_token = nfl_auth_cookies.get(f"glt_{settings.NFL['api_key']}")
        account_post_data = {
            "include": "profile,data",
            "lang": "en",
            "APIKey": settings.NFL["api_key"],
            "sdk": "js_latest",
            "login_token": login_token,
            "authMode": "cookie",
            "pageURL": "https://www.nfl.com/",
            "sdkBuild": settings.NFL["sdk_build"],
            "format": "json",
        }
        response = requests.post(
            settings.NFL["account_url"],
            data=urllib.parse.urlencode(account_post_data).encode("ascii"),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        ).json()
        info = {}
        for key in ["signatureTimestamp", "UID", "UIDSignature"]:
            if key in response:
                info[key] = response[key]

        return info

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
