# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_insight_content_explanation import NFLInsightContentExplanation

class TestNFLInsightContentExplanation(unittest.TestCase):
    """NFLInsightContentExplanation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLInsightContentExplanation:
        """Test NFLInsightContentExplanation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLInsightContentExplanation`
        """
        model = NFLInsightContentExplanation()
        if include_optional:
            return NFLInsightContentExplanation(
                evergreen_content = nfl.models.insight_content_explanation_evergreen_content.InsightContentExplanation_evergreenContent(
                    description = 'Timeless content that remains relevant beyond specific games or weeks, often focusing on season-long trends or career analysis', ),
                fantasy_insights = nfl.models.insight_content_explanation_fantasy_insights.InsightContentExplanation_fantasyInsights(
                    description = 'Fantasy football focused content analyzing player performances and projections for fantasy league purposes', ),
                postgame_insights = nfl.models.insight_content_explanation_postgame_insights.InsightContentExplanation_postgameInsights(
                    description = 'Post-game analysis examining what happened, key performances, and statistical breakdowns from completed games', ),
                pregame_insights = nfl.models.insight_content_explanation_pregame_insights.InsightContentExplanation_pregameInsights(
                    description = 'Analysis and predictions published before games, often focusing on key matchups, player trends, and statistical angles to watch', )
            )
        else:
            return NFLInsightContentExplanation(
        )
        """

    def testNFLInsightContentExplanation(self):
        """Test NFLInsightContentExplanation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
