# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from griddy.nfl.models.receiving_stats import ReceivingStats


class TestReceivingStats(unittest.TestCase):
    """ReceivingStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReceivingStats:
        """Test ReceivingStats
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReceivingStats`
        """
        model = ReceivingStats()
        if include_optional:
            return ReceivingStats(
                drops = 56,
                long_reception = 56,
                receptions = 56,
                targets = 56,
                touchdowns = 56,
                yards = 56,
                yards_per_reception = 1.337
            )
        else:
            return ReceivingStats(
        )
        """

    def testReceivingStats(self):
        """Test ReceivingStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
