# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from griddy.nfl.models.defensive_player_overview_stats import (
    DefensivePlayerOverviewStats,
)


class TestDefensivePlayerOverviewStats(unittest.TestCase):
    """DefensivePlayerOverviewStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefensivePlayerOverviewStats:
        """Test DefensivePlayerOverviewStats
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DefensivePlayerOverviewStats`
        """
        model = DefensivePlayerOverviewStats()
        if include_optional:
            return DefensivePlayerOverviewStats(
                display_name = 'Cameron Heyward',
                game_snap = 140,
                gp = 3,
                gs = 3,
                h_stop = 0,
                headshot = 'https://static.www.nfl.com/image/upload/formatInstructions/league/vfql05jp29d2pltrlwqz',
                int = 0,
                jersey_number = 97,
                nfl_id = '37104',
                ngs_position = 'C',
                ngs_position_group = 'DB',
                pass_rating_nd = 0,
                position = 'CB',
                position_group = 'DB',
                pr = 79,
                qbp = 8,
                qbp_r = 0.10127,
                qd = True,
                rd = 61,
                rec_nd = 0,
                rec_td_nd = 0,
                rec_yds_nd = 0,
                sack = 1,
                short_name = 'Ca.Heyward',
                snap = 140,
                snap_pct = 0.71066,
                t_stop = 12,
                tck = 14,
                team_id = '3900',
                team_snap = 197,
                tg = 3,
                tgt_nd = 0,
                total_tg = 3
            )
        else:
            return DefensivePlayerOverviewStats(
                display_name = 'Cameron Heyward',
                gp = 3,
                gs = 3,
                nfl_id = '37104',
                position = 'CB',
                snap = 140,
                team_id = '3900',
        )
        """

    def testDefensivePlayerOverviewStats(self):
        """Test DefensivePlayerOverviewStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
