# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from controllers.teams_controller import TeamsController


class TestTeamsController(unittest.TestCase):
    """TeamsController unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamsController()

    def tearDown(self) -> None:
        pass

    def test_get_all_teams(self) -> None:
        """Test case for get_all_teams

        Get All Teams
        """
        pass

    def test_get_team_roster(self) -> None:
        """Test case for get_team_roster

        Get Team Roster
        """
        pass

    def test_get_team_schedule(self) -> None:
        """Test case for get_team_schedule

        Get Team Schedule
        """
        pass

    def test_get_weekly_team_roster(self) -> None:
        """Test case for get_weekly_team_roster

        Get Weekly Team Roster
        """
        pass


if __name__ == "__main__":
    unittest.main()
