# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_defensive_overview_metrics_explanation_hard_stops import NFLDefensiveOverviewMetricsExplanationHardStops

class TestNFLDefensiveOverviewMetricsExplanationHardStops(unittest.TestCase):
    """NFLDefensiveOverviewMetricsExplanationHardStops unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLDefensiveOverviewMetricsExplanationHardStops:
        """Test NFLDefensiveOverviewMetricsExplanationHardStops
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLDefensiveOverviewMetricsExplanationHardStops`
        """
        model = NFLDefensiveOverviewMetricsExplanationHardStops()
        if include_optional:
            return NFLDefensiveOverviewMetricsExplanationHardStops(
                description = 'Tackles for loss or no gain - indicates ability to disrupt offensive plays behind or at line of scrimmage'
            )
        else:
            return NFLDefensiveOverviewMetricsExplanationHardStops(
        )
        """

    def testNFLDefensiveOverviewMetricsExplanationHardStops(self):
        """Test NFLDefensiveOverviewMetricsExplanationHardStops"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
