# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_coverage_metrics_receiver_separation import NFLCoverageMetricsReceiverSeparation

class TestNFLCoverageMetricsReceiverSeparation(unittest.TestCase):
    """NFLCoverageMetricsReceiverSeparation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLCoverageMetricsReceiverSeparation:
        """Test NFLCoverageMetricsReceiverSeparation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLCoverageMetricsReceiverSeparation`
        """
        model = NFLCoverageMetricsReceiverSeparation()
        if include_optional:
            return NFLCoverageMetricsReceiverSeparation(
                description = 'Average distance between defender and receiver at time of target',
                unit = 'yards'
            )
        else:
            return NFLCoverageMetricsReceiverSeparation(
        )
        """

    def testNFLCoverageMetricsReceiverSeparation(self):
        """Test NFLCoverageMetricsReceiverSeparation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
