# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_gamecenter_response_leaders_pass_distance_leaders import NFLGamecenterResponseLeadersPassDistanceLeaders

class TestNFLGamecenterResponseLeadersPassDistanceLeaders(unittest.TestCase):
    """NFLGamecenterResponseLeadersPassDistanceLeaders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLGamecenterResponseLeadersPassDistanceLeaders:
        """Test NFLGamecenterResponseLeadersPassDistanceLeaders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLGamecenterResponseLeadersPassDistanceLeaders`
        """
        model = NFLGamecenterResponseLeadersPassDistanceLeaders()
        if include_optional:
            return NFLGamecenterResponseLeadersPassDistanceLeaders(
                home = [
                    nfl.models.pass_distance_leader_entry.PassDistanceLeaderEntry(
                        pass_info = nfl.models.pass_info.passInfo(
                            air_distance = 53.34561369034946, ), )
                    ],
                visitor = [
                    nfl.models.pass_distance_leader_entry.PassDistanceLeaderEntry(
                        pass_info = nfl.models.pass_info.passInfo(
                            air_distance = 53.34561369034946, ), )
                    ]
            )
        else:
            return NFLGamecenterResponseLeadersPassDistanceLeaders(
        )
        """

    def testNFLGamecenterResponseLeadersPassDistanceLeaders(self):
        """Test NFLGamecenterResponseLeadersPassDistanceLeaders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
