# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_game_odds import NFLGameOdds

class TestNFLGameOdds(unittest.TestCase):
    """NFLGameOdds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLGameOdds:
        """Test NFLGameOdds
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLGameOdds`
        """
        model = NFLGameOdds()
        if include_optional:
            return NFLGameOdds(
                game_id = 2025092500,
                game_key = 59891,
                home_team_abbr = 'ARI',
                home_team_id = '3800',
                moneyline = nfl.models.money_line.MoneyLine(
                    away_price = '-125', 
                    home_price = '+105', ),
                spread = nfl.models.point_spread.PointSpread(
                    away_handicap = '-1.5', 
                    away_price = '-105', 
                    home_handicap = '+1.5', 
                    home_price = '-115', ),
                totals = nfl.models.totals.Totals(
                    over_handicap = 43.5, 
                    over_price = -105, 
                    under_handicap = 43.5, 
                    under_price = -115, ),
                updated_at = '2025-09-24T15:50:03Z',
                visitor_team_abbr = 'SEA',
                visitor_team_id = '4600'
            )
        else:
            return NFLGameOdds(
        )
        """

    def testNFLGameOdds(self):
        """Test NFLGameOdds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
