# coding: utf-8

"""
    NFL REST APIs

    Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

    The version of the OpenAPI document: 1.0.0
    Contact: john@thistlegrow.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nfl.models.nfl_replay import NFLReplay

class TestNFLReplay(unittest.TestCase):
    """NFLReplay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFLReplay:
        """Test NFLReplay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFLReplay`
        """
        model = NFLReplay()
        if include_optional:
            return NFLReplay(
                advertiser_id = '',
                author = '',
                authorizations = None,
                background = None,
                camera_source = '',
                clip_type = '',
                ctas = [
                    None
                    ],
                cta_link = '',
                cta_target = '',
                cta_text = '',
                description = '',
                display_title = '',
                duration = '8577',
                end_date = '',
                entitlement = '',
                episode_number = 56,
                expiration_date = '',
                external_id = '',
                fantasy_link = '',
                host_network = '',
                id = '',
                ids = nfl.models.replay_ids.Replay_ids(
                    away_team_id = '', 
                    game_id = '', 
                    home_team_id = '', 
                    play_id = '', ),
                images = [
                    None
                    ],
                intended_audience = '',
                intro_end = '',
                language = '',
                last_updated = '',
                mcp_playback_id = '',
                mobile_link = '',
                mobile_title = '',
                original_air_date = '',
                outro_start = '',
                play_ids = [
                    ''
                    ],
                pre_roll_disabled = True,
                promo_assets = [
                    None
                    ],
                promo_link = '',
                promo_target = '_self',
                promo_text = '',
                publish_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                radio_station = '',
                series = '',
                series_season = '',
                series_title = '',
                slug = '',
                start_date = '',
                sub_type = 'Full Game - Spanish',
                summary = '',
                tags = [
                    nfl.models.replay_tags_inner.Replay_tags_inner(
                        game_id = '', 
                        season = '', 
                        season_type = '', 
                        week = '', )
                    ],
                thumbnail = nfl.models.replay_thumbnail.Replay_thumbnail(
                    thumbnail_url = '', ),
                title = 'TNF en Espanol',
                type = 'video',
                videos = [
                    None
                    ],
                web_link = ''
            )
        else:
            return NFLReplay(
        )
        """

    def testNFLReplay(self):
        """Test NFLReplay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
