# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from griddy.nfl.models.fantay_scoring_explanation import FantayScoringExplanation


class TestFantayScoringExplanation(unittest.TestCase):
    """FantayScoringExplanation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FantayScoringExplanation:
        """Test FantayScoringExplanation
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FantayScoringExplanation`
        """
        model = FantayScoringExplanation()
        if include_optional:
            return FantayScoringExplanation(
                half_ppr_scoring = src.griddy.nfl.models.fantay_scoring_explanation_half_ppr_scoring.FantayScoringExplanation_halfPprScoring(
                    description = 'Half-PPR scoring - adds 0.5 points per reception to standard scoring', ),
                ppr_scoring = src.griddy.nfl.models.fantay_scoring_explanation_ppr_scoring.FantayScoringExplanation_pprScoring(
                    description = 'Points Per Reception scoring - adds 1 point per reception to standard scoring', ),
                standard_scoring = src.griddy.nfl.models.fantay_scoring_explanation_standard_scoring.FantayScoringExplanation_standardScoring(
                    description = 'Traditional fantasy scoring - 6 pts passing TD, 4 pts passing yards, 6 pts rushing/receiving TD, 1 pt per 10 rushing/receiving yards', )
            )
        else:
            return FantayScoringExplanation(
        )
        """

    def testFantayScoringExplanation(self):
        """Test FantayScoringExplanation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
