# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from griddy.nfl.models.gamecenter_response_pass_rushers_league_average_separation_to_qb import (
    GamecenterResponsePassRushersLeagueAverageSeparationToQb,
)


class TestGamecenterResponsePassRushersLeagueAverageSeparationToQb(unittest.TestCase):
    """GamecenterResponsePassRushersLeagueAverageSeparationToQb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GamecenterResponsePassRushersLeagueAverageSeparationToQb:
        """Test GamecenterResponsePassRushersLeagueAverageSeparationToQb
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GamecenterResponsePassRushersLeagueAverageSeparationToQb`
        """
        model = GamecenterResponsePassRushersLeagueAverageSeparationToQb()
        if include_optional:
            return GamecenterResponsePassRushersLeagueAverageSeparationToQb(
                avg = 4.573071521158667
            )
        else:
            return GamecenterResponsePassRushersLeagueAverageSeparationToQb(
        )
        """

    def testGamecenterResponsePassRushersLeagueAverageSeparationToQb(self):
        """Test GamecenterResponsePassRushersLeagueAverageSeparationToQb"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
