# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from src.griddy.nfl.models.defensive_player_stats import DefensivePlayerStats


class TestDefensivePlayerStats(unittest.TestCase):
    """DefensivePlayerStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefensivePlayerStats:
        """Test DefensivePlayerStats
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DefensivePlayerStats`
        """
        model = DefensivePlayerStats()
        if include_optional:
            return DefensivePlayerStats(
                bh_pct = 0.0625,
                catch_nd = 0.5625,
                cov = 147,
                cov_nd = 143,
                croe_nd = -0.03838,
                display_name = 'Jalen Thompson',
                game_snap = 208,
                gp = 3,
                gs = 3,
                headshot = 'https://static.www.nfl.com/image/upload/formatInstructions/league/gbb1sb2kkjlihuax2cud',
                int = 0,
                jersey_number = 34,
                nfl_id = '49410',
                ngs_position = 'C',
                ngs_position_group = 'DB',
                pass_rating_nd = 74.47917,
                position = 'CB',
                position_group = 'DB',
                qd = True,
                rec_nd = 9,
                rec_td_nd = 0,
                rec_yds_nd = 98,
                sep = 2.74855,
                short_name = 'J.Thompson',
                team_id = '3800',
                team_snap = 208,
                tg = 3,
                tgt_epa_nd = 2.0264879380119964,
                tgt_nd = 16,
                tgt_rnd = 0.11189,
                total_tg = 3,
                twf_pct = 0.125,
                yacpr_nd = 3.55556
            )
        else:
            return DefensivePlayerStats(
        )
        """

    def testDefensivePlayerStats(self):
        """Test DefensivePlayerStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
