# coding: utf-8

"""
NFL REST APIs

Regular API - NFL's public API for accessing game schedules, team information, standings, statistics, and venue data. This API provides comprehensive access to NFL data including real-time game information, team rosters, seasonal statistics, and historical data. The NFL Pro API is for accessing advanced statistics, film room content, player data, and fantasy information. This API provides comprehensive access to NFL Pro features including Next Gen Stats, Film Room analysis, player projections, and game insights.

The version of the OpenAPI document: 1.0.0
Contact: john@thistlegrow.software
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from src.griddy.nfl.models.coverage_metrics import CoverageMetrics


class TestCoverageMetrics(unittest.TestCase):
    """CoverageMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoverageMetrics:
        """Test CoverageMetrics
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CoverageMetrics`
        """
        model = CoverageMetrics()
        if include_optional:
            return CoverageMetrics(
                completion_rate_over_expected = src.griddy.nfl.models.coverage_metrics_completion_rate_over_expected.CoverageMetrics_completionRateOverExpected(
                    description = 'Difference between actual completion rate allowed and expected completion rate based on coverage situation', ),
                coverage_snaps = src.griddy.nfl.models.coverage_metrics_coverage_snaps.CoverageMetrics_coverageSnaps(
                    description = 'Defensive snaps where player was in coverage responsibility', ),
                receiver_separation = src.griddy.nfl.models.coverage_metrics_receiver_separation.CoverageMetrics_receiverSeparation(
                    description = 'Average distance between defender and receiver at time of target', 
                    unit = 'yards', ),
                targets_allowed = src.griddy.nfl.models.coverage_metrics_targets_allowed.CoverageMetrics_targetsAllowed(
                    description = 'Number of times opposing receivers were targeted while covered by this player', )
            )
        else:
            return CoverageMetrics(
        )
        """

    def testCoverageMetrics(self):
        """Test CoverageMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
