name: Publish to CodeArtifact

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: Thistle-Grow-Software/.github/.github/workflows/publish-codeartifact.yml@main
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      codeartifact-domain: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
      codeartifact-domain-owner: ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }}
      codeartifact-repo: ${{ secrets.AWS_CODEARTIFACT_REPO }}
