name: Quality Gates

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  quality-gates:
    uses: Thistle-Grow-Software/.github/.github/workflows/python-quality-gates.yml@main
    with:
      test-marker: "unit"
      codecov-enabled: true
      codecov-slug: "Thistle-Grow-Software/griddy-sdk-python"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
